### ISSUE TITLE
No conda recipe or packages?

### ISSUE THREAD

**Issue by gmarkall** [conda/constructor#1]
The instructions suggest installation with conda, but there appear to be no packages in the default channels or on anaconda.org, and there is no conda recipe in this repo. Are packages/recipes kept somewhere else?

**Comment by JanSchulz** [comment]
```
λ conda install -n root constructor
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..............
Error: No packages found in current win-64 channels matching: constructor

You can search for this package on anaconda.org with

    anaconda search -t conda constructor
```

**Comment by ilanschnell** [comment]
There are now some pre 1.0 releases on the default channel.  I'm still considering the project in alpha mode, until the 1.0 release, which will happen soon (likely next week), and will be accompanied by a blog post.
