### ISSUE TITLE
build a recipe(metapackage) instead of an installer?

### ISSUE THREAD

**Issue by hhuuggoo** [conda/constructor#10]
there are many cases where metapackages are better than installers, is there a way to build a metapackage with conda constructor?

**Comment by bkreider** [comment]
I don't think so.  A metapackage is just a conda package with an empty payload -- just requirements, not actual files.  Constructor builds a binary package of all of your requirements (conda packages).

**Comment by ilanschnell** [comment]
With https://github.com/conda/conda-build/pull/741 being merged, it is quite easy to use `conda-build` to create a meta package.  Just create a recipe (with no source), and specify what you need in your runtime dependencies, and *all* dependencies will get put into the (meta) conda package you build.

**Comment by hhuuggoo** [comment]
@ilanschnell that PR looks awesome! thanks!
