### ISSUE TITLE
Support specifying channel for python

### ISSUE THREAD

**Issue by thomasantony** [conda/constructor#108]
I have been trying to build an installer using a specific python-3.6.2 package from `conda-forge`. I have to do this because the default python 3.6 package used by Miniconda does not have SocketCAN built in. 

Is there any way to do this right now? If I add in a direct URL to the `tar.bz2` file containing the python version I want, constructor complains about a conflict. I also tried putting conda-forge at the top of the list of channels but it still used the default interpreter.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
