### ISSUE TITLE
Resolution of Build Numbers

### ISSUE THREAD

**Issue by H0R5E** [conda/constructor#112]
Hi, I believe the current stable version of constructor can not correctly resolve build numbers for anaconda packages.

I created a new build of a package which appears on anaconda cloud as so:

**dtocean-app-1.1.dev0-py27haa810f9_1.tar.bz2**

Constructor does not seem to be able to resolve the new format for package names, because in my .conda\constructor\win-64 folder the package that has been downloaded is:

**dtocean-app-1.1.dev0-py27h2861200_0.tar.bz2**

Is it something to do with the hash in the package name?

```
>constructor -V
constructor version: 1.5.5
```

**Comment by nehaljwani** [comment]
@H0R5E Which version of conda are you using?

**Comment by nehaljwani** [comment]
Also, @H0R5E could you try the cross_conda_interface branch of this repo to build constructor locally and try it out? It has a lot of changes as compared to the 1.5.5 release

**Comment by H0R5E** [comment]
Hi Nehal,

```
>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 3.0.18
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
                          C:\Users\mtopper\AppData\Local\conda\conda\envs
                          C:\Users\mtopper\.conda\envs
          package cache : C:\Anaconda\pkgs
                          C:\Users\mtopper\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/dataonlygreater/win-64
                          https://conda.anaconda.org/dataonlygreater/noarch
            config file : C:\Users\mtopper\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.12.4 CPython/2.7.13 Windows/8.1 Windows/6.3.9600
          administrator : False
```

Using the cross_conda_interface branch solved the original issue:

`fetching: dtocean-app-1.1.dev0-py27haa810f9_1.tar.bz2`

However, I did have some other problems. Firstly, I could not get it to install as load_entry_point was not able to locate ruamel_yaml, even though I explicitly installed the package through conda. If I removed ruamel_yaml from the requires.txt file in the constructor.egg.info directory, the program worked.

Secondly, constructor did not actually complete and I got the following error:

```
Checking for duplicate files ...
Error: File 'Scripts/activate' found in multiple packages: dtocean-economics-1.1.dev0-py27hf937cbc_0.tar.bz2, aneris-0.10.dev2-py27hc26d9bf_0.tar.bz2
```

**Comment by nehaljwani** [comment]
@H0R5E Yeah, the `ruamel_yaml` package needs to be fixed. You can just comment it out from `setup.py` and install `pyyaml` instead. As for the duplicate files check, you can turn make it warn instead and continue, by setting the option: `ignore_duplicate_files` to `True` in `construct.yaml`

**Comment by H0R5E** [comment]
OK, I can confirm that the installer compiles with the `ignore_duplicate_files` option set to `True`.

Can I suggest that `True` be the default for this option? All the duplicates that were found have been added by conda, not by myself, so it seems odd that I need to set something to stop the error.

```
Warning: File 'Scripts/activate' found in multiple packages: dtocean-economics-1.1.dev0-py27hf937cbc_0.tar.bz2, aneris-0.10.dev2-py27hc26d9bf_0.tar.bz2
Warning: File 'Lib/site-packages/mpl_toolkits/__init__.py' found in multiple packages: basemap-1.0.7-np110py27_0.tar.bz2, matplotlib-1.5.1-np110py27_0.tar.bz2
Warning: File 'Scripts/deactivate.bat' found in multiple packages: dtocean-economics-1.1.dev0-py27hf937cbc_0.tar.bz2, aneris-0.10.dev2-py27hc26d9bf_0.tar.bz2
Warning: File 'Scripts/deactivate' found in multiple packages: dtocean-economics-1.1.dev0-py27hf937cbc_0.tar.bz2, aneris-0.10.dev2-py27hc26d9bf_0.tar.bz2
Warning: File 'Scripts/conda' found in multiple packages: dtocean-economics-1.1.dev0-py27hf937cbc_0.tar.bz2, aneris-0.10.dev2-py27hc26d9bf_0.tar.bz2
Warning: File 'Scripts/conda.bat' found in multiple packages: dtocean-economics-1.1.dev0-py27hf937cbc_0.tar.bz2, aneris-0.10.dev2-py27hc26d9bf_0.tar.bz2
Warning: File 'Lib/site-packages/mpl_toolkits/__init__.pyc' found in multiple packages: basemap-1.0.7-np110py27_0.tar.bz2, matplotlib-1.5.1-np110py27_0.tar.bz2
Warning: File 'Scripts/activate.bat' found in multiple packages: dtocean-economics-1.1.dev0-py27hf937cbc_0.tar.bz2, aneris-0.10.dev2-py27hc26d9bf_0.tar.bz2
```

**Comment by nehaljwani** [comment]
@mingwandroid Would you like to share your thoughts on this?

**Comment by mingwandroid** [comment]
> All the duplicates that were found have been added by conda, not by myself, so it seems odd that I need to set something to stop the error.

The duplicates have been created in error by conda build in a bug that's since (recently) been fixed.

> Can I suggest that `True` be the default for this option?

You can suggest it but we will not do this for the following reasons:

1. You cannot install an installer with such overlapping files without passing -f from a shell-script based installer.
2. Since `conda` is incapable of dealing with overlapping files fixing 1. would be dangerous (if you install 2 packages with overlapping files and remove one of them the overlapping file gets removed breaking the remaining package).
