### ISSUE TITLE
constructor 1.6 missing in default channel

### ISSUE THREAD

**Issue by forman** [conda/constructor#116]
constructor 1.6 is released but not yet deployed on Anaconda default channel at https://repo.continuum.io/pkgs/free/ where there is only 1.5.5.

Therefore the new, documented `add_to_path_default` and `register_python_default` settings are not available (Windows). 

See #107 and  #87.

**Comment by nehaljwani** [comment]
A lot more development has happened in the branch cross_conda_interface and hasn't yet been merged into master. It'd be nice if you could test those changes!

**Comment by forman** [comment]
I hope I find some time to do so. 

Anyway, I suggest to document in [CONSTRUCT.md](https://github.com/conda/constructor/blob/master/CONSTRUCT.md) which are new, not-yet-deployed 1.6 features.

**Comment by csoja** [comment]
constructor v2.0.1 is available on https://repo.continuum.io/pkgs/main/
Is constructor v1.6 still needed?

**Comment by mbargull** [comment]
No, I believe this can be closed. See also: https://github.com/conda-forge/constructor-feedstock/pull/9
