### ISSUE TITLE
md5 program not found on Mac OSX

### ISSUE THREAD

**Issue by newville** [conda/constructor#118]
On OSX, I get the following when installing a package built with constructor:

```
package-X.Y-MacOSX-x86_64.sh: line 199: md5: command not found
WARNING: md5sum mismatch of tar archive
expected: 2c5732ce12f378e1f9467365b4bc767a
     got:
```
The install script has (~line 198)
```
# verify the MD5 sum of the tarball appended to this header
MD5=$(tail -n +401 $THIS_PATH | md5)
echo $MD5 | grep 2c5732ce12f378e1f9467365b4bc767a >/dev/null
if (( $? )); then
    echo "WARNING: md5sum mismatch of tar archive
expected: 2c5732ce12f378e1f9467365b4bc767a
     got: $MD5" >&2
fi

```

On OSX, `md5` is in `/sbin/md5` which is not typically in the PATH.  I think that test should be

```
MD5=$(tail -n +401 $THIS_PATH | /sbin/md5)
```

**Comment by mingwandroid** [comment]
> On OSX, md5 is in /sbin/md5 which is not typically in the PATH. I think that test should be

This is incorrect. `/sbin` and `/usr/sbin` have been on `PATH` by default on every `macOS` installation that I have ever used.

Using `openssl` is *ok*, but if we're making this change can we use something more secure than `md5`? Obviously we need to make sure whatever we pick is supported on `macOS 10.9` and every version since.

**Comment by nehaljwani** [comment]
We could use `openssl dgst -sha512`

**Comment by newville** [comment]
Thanks for looking into this, but I think you may be setting yourself for the same problem down the road.   If you want to use `/sbin/md5` or `/usr/bin/openssl gst -md5` (or sha512), use the *full path*.  Assuming the program (and the version you want) will be found in the users PATH is not highly robust.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.

For this issue in particular we now use `md5sum` on the Mac so I think we're good.

**Comment by newville** [comment]
@mcg1969 Which `md5sum` is that?  Do you mean`/sbin/md5`?  The point I was trying to make (now many years ago) and that appeared to not be understood at the time (and possibly still) was: use the FULL PATH to the executable for doing the hash sum.  Don't assume it will always be in the PATH, because, you know, someone or some script or policy might have changed that.
