### ISSUE TITLE
Error if version is not a string in construct.yaml

### ISSUE THREAD

**Issue by willingc** [conda/constructor#12]
On OS X, an error is thrown when executing ``constructor`` on ``construct.yaml`` if the version is entered as a number. ``constructor`` is expecting a string. Works fine if version is provided as a string.

Either documentation addition or changing the example 'maxiconda' would help. Overall, thanks for releasing this project. Very cool @ilanschnell.

<img width="653" alt="screen shot 2016-03-20 at 3 32 02 pm" src="https://cloud.githubusercontent.com/assets/2680980/13907774/3e02c156-eeb3-11e5-9094-2d7bdefb0b82.png">

**Comment by ilanschnell** [comment]
There is a fix for this: https://github.com/conda/constructor/commit/5af45f04ce360c5b132691c08f84aeec5e54d8f5
But a new release hasn't been made yet.

**Comment by willingc** [comment]
Thanks @ilanschnell.
