### ISSUE TITLE
Miniconda force overwrite does not overwrite

### ISSUE THREAD

**Issue by kalefranz** [conda/constructor#123]
_From @tonigi on October 24, 2017 14:34_

Running this 

    Miniconda3-4.3.27.1-Linux-x86_64.sh  -b -f  -p /tmp/ana

works the first time, but fails the second time around (while -f should force overwrite). 

    PREFIX=/tmp/ana
    installing: python-3.6.2-hdfe5801_15 ...
    mkdir: cannot create directory ‘/tmp/ana/pkgs/python-3.6.2-hdfe5801_15’: File exists

_Copied from original issue: conda/conda#6219_

**Comment by kalefranz** [comment]
@nehaljwani Is this something you have bandwidth to look at?

**Comment by nehaljwani** [comment]
This was fixed in https://github.com/conda/constructor/commit/a17d2ef2040d962c13217322607e5920699b178c . New installers will have this fix.

**Comment by nehaljwani** [comment]
@tonigi Try https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Linux-x86_64.sh

**Comment by tonigi** [comment]
Seems to work, thanks

Il 25 ott 2017 7:50 PM, "Nehal J Wani" <notifications@github.com> ha
scritto:
