### ISSUE TITLE
Feature request: option to include conda-bld channel via command line

### ISSUE THREAD

**Issue by croth1** [conda/constructor#13]
Is it possible to add a `--use-local` flag that grants access to the local repository of `conda-bld`? 

Local channels can be included by adding
```yaml
channels:
   - file:///path/to/miniconda/conda-bld
```
to `construct.yaml`

This however is not portable as it hardcodes the path of my miniconda installation. 

It would be cool to have a simple way to get access to the local repository.  This is especially useful for not yet released packages.

**Comment by ilanschnell** [comment]
The problem with allowing command line options is that the installers created become less reproducible.  Ideally, the construct directory is version controlled.  What might be worth considering is having an shorthand notation for the local conda-build channel, e.g.:
```
channels:
  - local
  - http://repo.continuum.io/pkgs/free/
```
Where, `local` expands to `file://<miniconda prefix>/conda-bld`.
