### ISSUE TITLE
Add self-check mode to the Miniconda installer

### ISSUE THREAD

**Issue by kalefranz** [conda/constructor#131]
_From @mithro on November 5, 2017 20:45_

The miniconda installer already has code for checking that the binary is the right size and has the correct hash. This is useful to make sure that the download is correct.

However, you can not easily to tell that the Miniconda file downloaded is corrupt or the install failed. It would be good if Miniconda had a "self test" mode which you could run to check that the download worked.

Maybe a `./Miniconda3-latest-Linux-x86_64.sh --verify` or `./Miniconda3-latest-Linux-x86_64.sh --check`.

_Copied from original issue: conda/conda#6264_

**Comment by nehaljwani** [comment]
@mithro I am not sure if I understand your query completely.

If you want to verify whether the downloaded installer file is corrupt or not, you can always check it by computing it's md5 sum against the values available at https://repo.continuum.io/miniconda/

**Comment by jakirkham** [comment]
My interpretation of the question asked is the user would like to make sure that when the installer completes it would be good to check the install is operational. It sounds like a good idea to me. Though am unclear on what sort of checks are useful generally vs. what checks should be specified by the person rolling the installer. Guessing there was a bad scenario that is being envisioned (or happened 😨), which would help guide this discussion.

**Comment by nehaljwani** [comment]
At the very least, there is a flag in the shell installer to test the installed packages: https://github.com/conda/constructor/commit/a2ef31573bcb9ae783d2d2361747a3ba1aa06615

**Comment by mithro** [comment]
What I want to do is download the file over an unreliable internet link and then check that the file is okay before putting it up for other local users to use.

Basically, I want to be able to verify the installer has been downloaded okay *without* trying to install it. Installing can fail for many reasons, not just a corrupt installer and I want to tell them apart.

I have a couple of times that when downloading the lastest version, it has changed on the server and I have gotten a corrupted file which is part one version and part another version (as using the "latest" link). I did not notice this until the self checks failed when trying to install.

The fact you already have this self check is awesome. I just want a simple way to run that check without having to also install.

Does that make sense?

**Comment by nehaljwani** [comment]
IIUC, The -t flag can be used only after installation. So, to test the downloaded file, you could just install it to a temporary directory with this flag and verify that the tests pass.

There is another check (at least in the shell installers) which check whether the contents are not garbage by verifying the md5sum. It then warns the user. See https://github.com/conda/constructor/blob/2.0.1/constructor/header.sh#L297-L308

I might not be completely understanding your point yet, but I don't think there is any correlation between the name of the installer file and the contents provided by it. So I don't know how one would verify whether 'latest' is indeed 'latest' or not. Suggestions welcome :)

**Comment by mingwandroid** [comment]
> However, you can not easily to tell that the Miniconda file downloaded is corrupt or the install failed.

I do not understand here. I'd it is corrupt you'll get a checksum failure (though we should use something better than md5). If the install failed you'll get a non-zero exit code.

> IIUC, The -t flag can be used only after installation.

How do you mean? You pass -t to the command line for the actual installation if you want to install while running package tests. There's no (intentional) way to run the tests on an existing installation. Some tests may fail though as we've not had a chance to make sure they do not use system packages (and on Windows, compilers) you may not have installed. You also need to be connected to the internet for them to succeed.

**Comment by mithro** [comment]
For example, how do I tell the difference between the following things in an automated fashion without looking at the stdout output? They all return non-zero exit codes....

 (a) The installer is corrupt.
 (b) The user hit ctrl-c during installation.
 (c) The user didn't have permission to install to a location

If I'm able to do a `install.sh --verify` as a totally separate step from install then I know the installer is fine and the user did something during installation which caused it to fail.

All that is needed is a way to run the size+md5sum check you listed above **without** also doing the install or accept the license and stuff.

**Comment by mcg1969** [comment]
I know this is an old issue but I think we'd still welcome a PR that could implement some of these ideas.

**Comment by mcg1969** [comment]
didn't mean to close—rather I just tagged it as an "enhacement"
