### ISSUE TITLE
AddSize error (missing float -> int cast)

### ISSUE THREAD

**Issue by speleo3** [conda/constructor#133]
In `constructor/winexe.py` the variable `approx_pkgs_size_kb` needs to be casted to `int`. That's because in Python 2, `math.ceil()` returns a float (in Python 3 it returns an `int`).

The cast fixes the following error message:
```
Calling: ['f:\\holder\\Miniconda2\\NSIS\\makensis.exe', '/V2', 'c:\\users\\holde
r\\appdata\\local\\temp\\4\\tmpccuvwb\\main.nsi']
Usage: AddSize size_to_add_to_section_in_kb
Error in script "c:\users\holder\appdata\local\temp\4\tmpccuvwb\main.nsi" on lin
e 1075 -- aborting creation process
```

**Comment by nehaljwani** [comment]
Thanks for reporting this issue @speleo3 !

Python 2, die already :sob:
