### ISSUE TITLE
Fails to include package file

### ISSUE THREAD

**Issue by joelhullcio** [conda/constructor#136]
In previous version of Constructor I was able to use the package key to include local custom conda packages.  Some of these custom packages only contain shared object library files that are dependencies to other packages.  Including these custom packages is necessary since the share libraries are guaranteed to exist on the systems where the installer will run and they are also not included in the parent package that depends on them.

Below and attached is the AssertionError thrown by Constructor 2.0.0 and and example of the custom conda package.

```
Traceback (most recent call last):
  File "/root/ana411py27/bin/constructor", line 11, in <module>
    load_entry_point('constructor==2.0.0', 'console_scripts', 'constructor')()
  File "/root/ana411py27/lib/python2.7/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)
  File "/root/ana411py27/lib/python2.7/site-packages/constructor/main.py", line 113, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/root/ana411py27/lib/python2.7/site-packages/constructor/fcp.py", line 265, in main
    dists.sort()
  File "/root/ana411py27/lib/python2.7/site-packages/conda/models/dist.py", line 230, in __gt__
platform: linux-64
conda packages download: /root/.conda/constructor/linux-64
specs: ['anaconda 5.0*', 'python 2.7*', 'conda']

    assert isinstance(other, self.__class__)
AssertionError
```
[issue.zip](https://github.com/conda/constructor/files/1462662/issue.zip)

To reproduce the issue, download and extract the attached zip file.  Run the build.sh file.

**Comment by nehaljwani** [comment]
Hi @joelhullcio , it seems to me that the package key could possibly be broken right now. However, the following construct.yaml should provide you what you want:
```
name: test
version: 1.0.0

channels:
  - http://conda.anaconda.org/anaconda
  - http://repo.continuum.io/pkgs/free
  - http://repo.continuum.io/pkgs/pro
  - http://repo.continuum.io/pkgs/r
  - file:///tmp/repo

specs:
  - anaconda 5.0*
  - python 2.7*
  - conda
  - libxdmcp ==6.0.0 h3518b6a_1 [unix]
```

**Comment by joelhullcio** [comment]
@nehaljwani Thank you for the work-around idea.  The constructor build is working now with this approach.  I am running a test install now.  Do you plan to fix the package key?

**Comment by jakirkham** [comment]
Is there a way to include the checksum in the `specs` too?

**Comment by xhahn** [comment]
There is a different error happened when I use constructor_2.0.1:
```
Traceback (most recent call last):
   File "/opt/anaconda2/bin/constructor", line 6, in <module>
    sys.exit(constructor.main.main())
  File "/opt/anaconda2/lib/python2.7/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)\n
  File "/opt/anaconda2/lib/python2.7/site-packages/constructor/main.py", line 113, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/opt/anaconda2/lib/python2.7/site-packages/constructor/fcp.py", line 277, in main
    check_dists()
  File "/opt/anaconda2/lib/python2.7/site-packages/constructor/fcp.py", line 137, in check_dists
    check_duplicates()
  File "/opt/anaconda2/lib/python2.7/site-packages/constructor/fcp.py", line 59, in check_duplicates
    (name, ', '.join(files)))
TypeError: sequence item 0: expected string, Dist found
```

Following is my construct.yaml
```
name: Myconda
version: 1.0.0

install_in_dependency_order: True

channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/

specs:
  - python 3.5*
  - conda
  - nomkl                                [not win]
  - numpy
  - scipy
  - pandas
  - notebook
  - matplotlib                          
  - urllib3 [unix]

packages:
  - file:///opt/constructor/urllib3=1.22=py35h2ab6e29_0.tar.bz2
```

the package i want to add into installer is urllib3 downloaded from [anaconda cloud](https://anaconda.org/anaconda/urllib3/files):
```urllib3-1.22-py35h2ab6e29_0.tar.bz2```

**Comment by xhahn** [comment]
@nehaljwani thank you ! And how to write the item in specs key, I have tried
 ```
 - urllib3 ==1.22 py35h2ab6e29_0 [unix]
``` 
as your adviced before, but it dose not work for me.I just got an error told me it is wrong but without any other error Info.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
