### ISSUE TITLE
Consider removing libconda support from constructor

### ISSUE THREAD

**Issue by kalefranz** [conda/constructor#139]
As @nehaljwani mentioned in #130, with libconda growing further and further out of date from conda, it might be appropriate to remove libconda support from constructor.  When constructor is using libconda, end-users will often end up with broken behavior that is subtle and not easy to trace back to libconda vs conda.

The drawback is that as of conda 4.3, conda can only be installed in the root conda environment.  This restriction is lifted in conda 4.4.

**Comment by mingwandroid** [comment]
I am in favour of getting rid of `libconda` yes. It should only come back if it were to be a dependency of `conda` itself.

**Comment by kalefranz** [comment]
> It should only come back if it were to be a dependency of `conda` itself.

And it that case I'm guessing it could very possibly be written in a language other than python.

**Comment by nehaljwani** [comment]
I want to merge #140 
But it still tries to address libconda imports. AFAIK, with >=2.0.0, constructor doesn't even work with libconda. So... should we remove this first?
