### ISSUE TITLE
stable versions?

### ISSUE THREAD

**Issue by hhuuggoo** [conda/constructor#143]
Hi - is there a recommended set of conda/conda-build/constructor versions that should be used together?

For example I recently ran into an issue where conda-build inject '.*' into my dependencies, which confuses anaconda constructor 1.5, which can't find numpy=2.8.1.*

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
