### ISSUE TITLE
/D is not properly set when /S is specified for NSIS installer

### ISSUE THREAD

**Issue by claymcleod** [conda/constructor#146]
Hi all,

On lines 306-308 of https://github.com/conda/constructor/blob/master/constructor/nsis/main.nsi.tmpl, it says

```
    # When using the installer with /S (silent mode), the /D option sets $INSTDIR,
    # and it is therefore important not to overwrite $INSTDIR here, but it is also
    # important that we do call SetShellVarContext with the appropriate value.
```

Based on my latest check, this is not working correctly. Can someone let me know if I'm missing something??

```
PS C:\Users\cmcleod\Downloads> .\Miniconda2-latest-Windows-x86_64.exe /S /D=%UserProfile%\anaconda\
PS C:\Users\cmcleod\Downloads> ls ~/ | grep anaconda
PS C:\Users\cmcleod\Downloads>
```

**Comment by nehaljwani** [comment]
I am not sure whether `%UserProfile%` will be interpolated correctly.  The command you typed will probably throw the contents of the installation to: `%LOCALAPPDATA%\Continuum\miniconda2`

I think what you really want is this:
```
PS C:\Users\nwani\Downloads> Start-Process -Wait ".\Miniconda2-latest-Windows-x86_64.exe" "/S /D=$ENV:UserProfile\anacon
da\"
PS C:\Users\nwani\Downloads> ls ~/ | findstr anaconda
d-----        12/5/2017  10:28 PM                anaconda
```

Also, while you are at it, I would recommend you to explicitly also specify the options:
```
/InstallationType=JustMe /AddToPath=0 /RegisterPython=0
```

**Comment by nehaljwani** [comment]
@claymcleod Can this issue be closed?

**Comment by claymcleod** [comment]
Yes, it can! Thank you.
