### ISSUE TITLE
Getting date in construct.yaml

### ISSUE THREAD

**Issue by jakirkham** [conda/constructor#149]
Would be nice if there was a way to get the date in `construct.yaml`.

**Comment by mcg1969** [comment]
Agreed. However does the Jinja templating capability help us here?

**Comment by jakirkham** [comment]
Ah didn't know we have Jinja templating now. Yeah I think so. We use [Jinja in `conda-forge-pinning`]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/c37a56718b6ab928734b042c508449cefd01ee9e/recipe/meta.yaml#L1 ) and it works well.
