### ISSUE TITLE
Failures in post-install scripts are silently ignored on Windows

### ISSUE THREAD

**Issue by FelixS90** [conda/constructor#150]
In the case of creating a Windows installer, a FAILING post-install batch script (just do an `exit 1` or even simpler add a _finally_ clause in run_post_install() s.t.
```
def run_post_install():
    """
    call the post install script, if the file exists
    """
    path = join(ROOT_PREFIX, 'pkgs', 'post_install.bat')
    if not isfile(path):
        return
    env = os.environ
    env['PREFIX'] = str(ROOT_PREFIX)
    try:
        args = [env['COMSPEC'], '/c', path]
    except KeyError:
        err("Error: COMSPEC undefined\n")
        return
    import subprocess
    try:
        subprocess.check_call(args, env=env)
    except subprocess.CalledProcessError:
        err("Error: running %s failed\n" % path)
    finally:
        err("Error: running %s failed\n" % path)
```
), the install process finishes with success instead of the "Failed to run post install script"-AbortRetryIgnore box.

When you replace `err(...)` with `sys.exit(...)`, the box shows up as expected, most likely because of the exit code that is different from zero in this case.

As a user, I would expect the installer to report this accordingly instead of failing silently. The error that is printed to stderr does not show up anywhere since _nsis.py is run using pythonw.exe.

_As a side note:_
Concerning issue #39 , the reason the "Failed to run post install script"-AbortRetryIgnore box shows up is that it fails with sys.exit() in the main() method of _nsis.py since (for whatever reason) the command __post_install__ seems not to be specified in the code. It seems that this file is replaced during the install process (for whatever reason, I didn't invest more time in that, but rather accidentally came across it).

In any case, I would be interested in the intention behind just printing to stderr instead of exiting with an error code different from zero (`sys.exit(1)` or `sys.exit('failed')`, similar to what is done in the main() method) in the run_post_install (as well as e.g. in rm_menus or mk_menus). Is it on purpose (I highly doubt that) or is it just a bug that was never tested against? At least, there do not seem to be any tests covering a failing post_install script (correct me, if I am wrong).

@mingwandroid @nehaljwani @ilanschnell Any comment on this is highly welcome.

Thanks a lot in advance (and a happy new year!).

**Comment by mcg1969** [comment]
I'm doing an old issue sweep and closing stale issues. This one does _not_ seem stale to me. This code is still present in the NSIS case. This seems like a simple and solid improvement for someone to tackle.

**Comment by davibicudo** [comment]
I was going to report this and came accross this stale issue. Would be nice to have a solution to this problem, since the post_install script is quite critical to the installation in many cases.
