### ISSUE TITLE
Segmentation fault on win-32 Python 2.7 due to `pillow` `Image.resize(...)`

### ISSUE THREAD

**Issue by cfobel** [conda/constructor#151]
~~**Update: note that (as @mingwandroid says below) this may only occur when using the `conda-forge` channel**~~

**Update 2: @mingwandroid , this is _not_ restricted to the `conda-forge` package.  I have reproduced it in a clean install of [`Miniconda2-4.3.31-Windows-x86.exe`][miniconda] with the following environment: [env-python-2.7.14-conda-4.4.6.yaml.zip](https://github.com/conda/constructor/files/1602455/env-python-2.7.14-conda-4.4.6.yaml.zip)**

Executing `constructor ...` on a `win-32` Python 2.7 system causes a segmentation fault during the `pillow` `Image.resize(...)` operation for the logo.

This is caused by [issue 39 with `pillow` package][i39].  A workaround exists for [`pillow` issue 39][i39], by installing `pillow==3.0.0` and `freetype>=2.8`.

However, this workaround cannot be used with `constructor`, since `constructor` [requires `pillow>=3.1.0`][1].

# Workaround

I've manually tested `constructor` with `pillow==3.0.0` on `win-32` Python 2.7 and everything seems to work ok.

Can the `constructor` requirement for `pillow` be relaxed to `pillow>=3.0.0` instead of `pillow>=3.1.0`?  @mbargull perhaps you can comment on this since it seems you added the `pillow` requirement in 320bef93d1c6c3ba8484c257ab313e14302ff18d?  If this would be ok, I would be happy to create a pull request with the change.

[i39]: https://github.com/conda-forge/pillow-feedstock/issues/39
[1]: https://github.com/conda/constructor/blob/fae60e49bf1daefdb6fca51621be4b38bc597e47/setup.py#L101
[miniconda]: https://repo.continuum.io/miniconda/Miniconda2-4.3.31-Windows-x86.exe

**Comment by mingwandroid** [comment]
You are reporting a bug against `conda-forge`'s pillow package here I think?

The packages in the `Anaconda Distribution` do not suffer from this.

**Comment by cfobel** [comment]
@mingwandroid , thanks for your quick response!

As you mentioned, the issue may be confined to `conda-forge`'s pillow package.

However, if the `pillow>=3.1.0` requirement **_can be_** relaxed to `pillow>=3.0.0` it would still be helpful to do so.  It would also arguably be more correct, if in fact no features added in `pillow==3.1.0` are actually *required* by `constructor`.

`constructor` is an amazingly useful tool and, while not required, I think it would be great to keep it available to those creating installers while using `conda-forge` packages if possible until the upstream changes to `conda-forge`'s `pillow` package is fixed.

**Comment by mingwandroid** [comment]
> constructor is an amazingly useful tool

That's not a word anyone on my team would use to describe it.

We need to hear from @mbargull about why he picked 3.1, but you should fix your bug in `pillow` as it'll break all your Win-32 users instead of this.

**Comment by cfobel** [comment]
> > constructor is an amazingly useful tool
>
> That's not a word anyone on my team would use to describe it.

Haha... @mingwandroid would you have an alternative tool that you would suggest?

>We need to hear from @mbargull about why he picked 3.1, but **you should fix your bug in pillow** as it'll break all your Win-32 users instead of this.

I completely agree that the bug should be fixed in `conda-forge`'s `pillow` package.  I have submitted an issue (see [pillow issue 39][i39] and look forward to a response from the package maintainer that will likely have more insight.

Also looking forward to hearing back from @mbargull :)

[i39]: https://github.com/conda-forge/pillow-feedstock/issues/39

**Comment by mbargull** [comment]
Relaying the question to @ilanschnell as I only added the missing requirement as given in https://github.com/ContinuumIO/anaconda-recipes/blob/66c1c1f69108fd60ca0348aaf4889534d91e7048/constructor/meta.yaml#L20.

**Comment by cfobel** [comment]
Thanks @mbargull !

**Comment by cfobel** [comment]
@mingwandroid as I've mentioned in the updated the issue description, it turns out that this is _not_ restricted to the `conda-forge` package.  I have reproduced it in a clean install of [`Miniconda2-4.3.31-Windows-x86.exe`][miniconda] with the following environment: [env-python-2.7.14-conda-4.4.6.yaml.zip](https://github.com/conda/constructor/files/1602455/env-python-2.7.14-conda-4.4.6.yaml.zip)**

[miniconda]: https://repo.continuum.io/miniconda/Miniconda2-4.3.31-Windows-x86.exe

**Comment by mingwandroid** [comment]
You can work around this by using Python 3.6 to build your installers. I don't ever run Python 2.7. I'm not going to merge the wrong fix here. Pillow is broken, pillow should be fixed, other things shouldn't be changed as a consequence of that bug.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.

I would also strongly recommend @mingwandroid's recommendation to use Python 3 only
