### ISSUE TITLE
Conda 4.4.6: `constructor --test` results in `ImportError: cannot import name fetch_repodata`

### ISSUE THREAD

**Issue by cfobel** [conda/constructor#152]
# Setup

 1. Install [`Miniconda2-4.3.31-Windows-x86.exe`][miniconda]
 2. Install `constructor`:

        conda install constructor
 3. Run `constructor` tests:

        constructor --test

Here is the test environment: [env-python-2.7.14-conda-4.4.6.yaml.zip](https://github.com/conda/constructor/files/1602455/env-python-2.7.14-conda-4.4.6.yaml.zip)

# Expected behaviour

Output similar to:

```
sys.prefix: C:\Users\chris\Miniconda2
sys.version: 2.7.14 | packaged by conda-forge | (defa ...
constructor version: 2.0.1
conda interface type: conda
conda interface version: 4.4.6
location: C:\Users\chris\Miniconda2\lib\site-packages\constructor
pillow version: 3.0.0
Checking for 'C:\Users\chris\Miniconda2\NSIS\makensis.exe'
NSIS version: v3.01
Reading: C:\Users\chris\Miniconda2\lib\site-packages\constructor\nsis\main.nsi.tmpl
.................
----------------------------------------------------------------------
Ran 17 tests in 0.003s

OK
```

# Observed behaviour

**Note: as part of `constructor` install, `conda` package was automatically updated `4.3.31-py27_0 --> 4.4.6-py27_0`.**

An `ImportError` is raised:

```
sys.prefix: C:\Users\chris\Miniconda2.7.14-x86
sys.version: 2.7.14 |Anaconda, Inc.| (default, Nov  8 ...
constructor version: 2.0.1
conda interface type: conda
conda interface version: 4.4.6
location: C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor
Traceback (most recent call last):
  File "C:\Users\chris\Miniconda2.7.14-x86\Scripts\constructor-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\main.py", line 205, in main
    tests_main()
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\tests\__init__.py", line 28, in main
    from .. import winexe
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\winexe.py", line 21, in <module>
    from .preconda import write_files as preconda_write_files
  File "C:\Users\chris\Miniconda2.7.14-x86\lib\site-packages\constructor\preconda.py", line 11, in <module>
    from conda.core.repodata import fetch_repodata
ImportError: cannot import name fetch_repodata
```

This seems to be an issue with the `conda` package API changing from `4.3.31` to `4.4.6`.

**Note: a _different_ import error occurs with `conda==4.3.31`.  See #153 for details.**

[miniconda]: https://repo.continuum.io/miniconda/Miniconda2-4.3.31-Windows-x86.exe

**Comment by nehaljwani** [comment]
This should most likely be fixed with:
https://github.com/conda/constructor/pull/140 which has been merged, but not released yet.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
