### ISSUE TITLE
conda_default_channels, conda_channel_alias, etc. should imply write_condarc

### ISSUE THREAD

**Issue by jakirkham** [conda/constructor#155]
Noticed that there is a `write_condarc` option that was added recently, which does not appear to be documented. Would be good to have something about it in `CONSTRUCT.md`.

Also noticed that `conda_default_channels` has no effect unless `write_condarc` is set to `true` (even if `write_condarc` was not specified). Seems like defining `conda_default_channels` should imply `write_condarc` even if `write_condarc` was never explicitly set.

**Comment by mcg1969** [comment]
We have definitely improved things here. In particular, the new `condarc` option does not require `write_condarc` to be explicitly set. That said, I agree with the intuition here and would welcome a simple PR that eliminates the need to specify `write_condarc` if the `conda_` options are used.

**Comment by cfrelet** [comment]
Sorry I'm not clear how to use write_condarc and conda_default_channels if I want to use a .condarc file.
Can you give a clear example?
write_condarc  : True
conda_default_channels : c:\.condarc
?

**Comment by mcg1969** [comment]
`conda_default_channels` needs to be a list; e.g.,
```
write_condarc: true
conda_default_channels:
  - C:\.condarc
```
Now to be clear, that's an odd name for a channel, so please make sure that's truly what you intend there.
