### ISSUE TITLE
Installing Miniconda with prefix into a long directory path can cause bad interpreter in shebang

### ISSUE THREAD

**Issue by kalefranz** [conda/constructor#156]
_From @mkobit on January 9, 2018 16:17_

Example:

* `mkdir -p /tmp/install-issue && cd /tmp/install-issue`
* `curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O`
* long path - `bash Miniconda3-latest-Linux-x86_64.sh -u -b -p "$PWD/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"`
* execute conda

        $PWD/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/bin/conda --version
        zsh: /tmp/install-issue/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/bin/conda: bad interpreter: /tmp/install-

* short path - `bash Miniconda3-latest-Linux-x86_64.sh -u -b -p "$PWD/test-install-dir"`
* execute conda

        $PWD/test-install-dir/bin/conda --version                              
        conda 4.3.31

The `conda` has an absolute path to the python executable of the prefix directory:

```
#!/tmp/install-issue/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/bin/python 
```

_Copied from original issue: ContinuumIO/anaconda-issues#8067_

**Comment by kalefranz** [comment]
For now, I'd use miniconda in a shorter path if you can, and then you `conda create` to create new environments as needed.  `conda create` uses `#!/usr/bin/env` if shebangs are too long.

**Comment by mkobit** [comment]
Thanks @kalefranz , that is how we are handling it now. This first cropped up for us in some of our build automation that installs to the local workspace which may be a very long path.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
