### ISSUE TITLE
Feature request: ability to specify root .condarc file values

### ISSUE THREAD

**Issue by joelhullcio** [conda/constructor#16]
Currently when an installer is run there is no .condarc file in the root env.  Often it is desirable to setup specific channels, default env packages, proxies, env paths, etc in the root .condarc especially within enterprises.

Add a section to the construct.yaml where the root .condarc values can be specified then have the installer create the root .condarc file when the installer is run.

**Comment by bkreider** [comment]
+1

The workaround is a post-install step that makes it for you.

**Comment by ilanschnell** [comment]
There is the ability to set default channels, see `conda_default_channels:` in https://github.com/conda/constructor/blob/master/CONSTRUCT.md
This works by creating a `<prefix>/.condarc`.

**Comment by mcg1969** [comment]
This feature is now available in the latest versions of constructor.
