### ISSUE TITLE
Using installer_type pkg on macOS fails due to missing attempt_hardlinks

### ISSUE THREAD

**Issue by jakirkham** [conda/constructor#160]
It seems that `attempt_hardlinks` should just default to `False`. However it appears that when `installer_type: pkg` is selected it does not pick up on the `attempt_hardlinks` setting.

```python
pkgbuild: Wrote package to /var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/miniforge_pOHjOE/cache/osx-64/built_pkgs/preconda.pkg
Traceback (most recent call last):
  File "/zopt/conda2/bin/constructor", line 6, in <module>
    sys.exit(constructor.main.main())
  File "/zopt/conda2/lib/python2.7/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)
  File "/zopt/conda2/lib/python2.7/site-packages/constructor/main.py", line 128, in main_build
    create(info, verbose=verbose)
  File "/zopt/conda2/lib/python2.7/site-packages/constructor/osxpkg.py", line 189, in create
    if info['attempt_hardlinks']:
KeyError: 'attempt_hardlinks'
```

**Comment by jakirkham** [comment]
Actually looks like PR ( https://github.com/conda/constructor/pull/157 ) should fix this. Would be good to confirm though.

**Comment by jakirkham** [comment]
Not sure if there is an intended relationship between `attempt_hardlinks` and `use_hardlinks`. Though both options do seem to exist. Unclear to the difference though. 😕

**Comment by nehaljwani** [comment]
@jakirkham `use_hardlinks` was renamed to `attempt_hardlinks` at https://github.com/conda/constructor/commit/b2891730f774b97e646a80476656e29eaca2193a
