### ISSUE TITLE
Constructor downloads noarch package if noarch package is more recent than the most recent platform-specific package

### ISSUE THREAD

**Issue by FelixS90** [conda/constructor#162]
It seems that the dependency resolution always looks for the latest version (uploaded last) of a package (no matter if this is a noarch package or a package of the specified platform).

This is a problem since the constructor docs state that constructor does NOT work with noarch packages (however, it downloads them although there are platform-specific versions available).

**Reproduction steps (17/01/2018):**

Constructor details:
```
constructor version: 2.0.1
conda interface type: conda
conda interface version: 4.3.29
pillow version: 5.0.0
NSIS version: v3.01
platform: win-64
```
construct.yaml:
```
name: someName

version: xxyyzz

installer_type: exe

channels:
  - http://repo.continuum.io/pkgs/main
  - http://repo.continuum.io/pkgs/free
  - http://repo.continuum.io/pkgs/msys2
  - https://conda.anaconda.org/aaronzs
  - https://conda.anaconda.org/clg_boar
  - https://conda.anaconda.org/conda-forge
  
specs:
  - python ==3.6.3
  - cloudpickle
  - dask
  - distributed
  - flask
  - marshmallow
  - matplotlib
  - numpy
  - pandas
  - psutil
  - pyside
  - scikit-image
  - scikit-learn
  - scipy
  - sqlalchemy
  - tensorflow ==1.4.0
  - tornado
  - waitress
  - werkzeug
  - xmlrunner

exclude:
  - pyqt

install_in_dependency_order: True
```
The output looks as follows:
```
specs: ['python ==3.6.3', 'cloudpickle', 'dask', 'distributed', 'flask', 'marshmallow', 'matplotlib', 'numpy', 'pandas', 'psutil', 'pyside', 'scikit-image', 'scikit-learn', 'scipy', 'sqlalchemy', 'tensorflow ==1.4.0', 'tornado', 'waitress', 'werkzeug', 'xmlrunner']


name: someName
version: xxyyzz
cache download location: <...>\.conda\constructor\win-64
platform: win-64
number of package: 73
    defaults::python-3.6.3-h3b118a2_4
    defaults::ca-certificates-2017.08.26-h94faf87_0
    defaults::icc_rt-2017.0.4-h97af966_0
    defaults::intel-openmp-2018.0.0-hd92c6cd_8
    defaults::vs2015_runtime-14.0.25123-3
    defaults::mkl-2018.0.1-h2108138_4
    conda-forge::openssl-1.0.2n-vc14_0
    defaults::vc-14-h0510ff6_3
    conda-forge::zlib-1.2.11-vc14_0
    conda-forge::jpeg-9b-vc14_2
    conda-forge::libiconv-1.14-vc14_4
    conda-forge::libpng-1.6.34-vc14_0
    defaults::certifi-2017.11.5-py36hb8ac631_0
    defaults::click-6.7-py36hec8c647_0
    defaults::cloudpickle-0.5.2-py36h6b1d831_0
    defaults::dask-core-0.16.1-py36_0
    defaults::decorator-4.1.2-py36he63a57b_0
    conda-forge::freetype-2.7-vc14_1
    defaults::heapdict-1.0.0-py36h21fa5f4_0
    defaults::itsdangerous-0.24-py36hb6c5a24_1
    conda-forge::libtiff-4.0.9-vc14_0
    conda-forge::libxml2-2.9.3-vc14_9
    defaults::locket-0.2.0-py36hfed976d_1
    defaults::markdown-2.6.9-py36_0
    defaults::markupsafe-1.0-py36h0e26971_1
    conda-forge::marshmallow-2.15.0-py_0
    defaults::msgpack-python-0.5.1-py36he980bc4_0
    defaults::numpy-1.13.3-py36ha320f96_0
    defaults::olefile-0.44-py36h0a7bdd2_0
    defaults::psutil-5.4.3-py36hfa6e2cd_0
    defaults::pyparsing-2.2.0-py36h785a196_1
    defaults::pytz-2017.3-py36h1d3fa6b_0
    defaults::pyyaml-3.12-py36_0
    defaults::sip-4.18-py36_0
    defaults::six-1.11.0-py36h4db2310_1
    defaults::sortedcontainers-1.5.9-py36_0
    defaults::sqlalchemy-1.2.0-py36hfa6e2cd_0
    defaults::tblib-1.3.2-py36h30f5020_0
    defaults::toolz-0.9.0-py36_0
    defaults::tornado-4.5.3-py36_0
    defaults::waitress-1.1.0-py36h7181276_0
    defaults::werkzeug-0.14.1-py36_0
    defaults::wincertstore-0.2-py36h7fe50ca_0
    conda-forge::xmlrunner-1.7.7-py_0
    defaults::cycler-0.10.0-py36h009560c_0
    defaults::html5lib-0.9999999-py36_0
    conda-forge::libxslt-1.1.32-vc14_0
    defaults::networkx-2.0-py36hff991e3_0
    defaults::partd-0.3.8-py36hc8e763b_0
    conda-forge::pillow-4.2.1-py36_0
    defaults::python-dateutil-2.6.1-py36h509ddcb_1
    defaults::pywavelets-0.5.2-py36hc649158_0
    conda-forge::qt-4.8.7-vc14_6
    defaults::scipy-1.0.0-py36h1260518_0
    defaults::setuptools-38.4.0-py36_0
    defaults::zict-0.1.3-py36h2d8e73e_0
    defaults::bleach-1.5.0-py36_0
    defaults::distributed-1.20.2-py36_0
    defaults::imageio-2.2.0-py36had6c2d2_0
    defaults::jinja2-2.10-py36h292fed1_0
    defaults::pandas-0.22.0-py36h6538335_0
    conda-forge::protobuf-3.5.1-py36_vc14_3
    conda-forge::pyside-1.2.4-py36_vc14_8
    defaults::scikit-learn-0.19.1-py36h53aea1b_0
    defaults::wheel-0.30.0-py36h6c3ec14_1
    defaults::bokeh-0.12.13-py36h047fa9f_0
    defaults::flask-0.12.2-py36h98b5e8f_0
    conda-forge::matplotlib-1.5.3-np113py36_8
    defaults::pip-9.0.1-py36h226ae91_4
    aaronzs::tensorflow-tensorboard-0.4.0rc3-py36h1eb756b_0
    defaults::dask-0.16.1-py36_0
    aaronzs::tensorflow-1.4.0-py36he4e0f4f_0
    defaults::scikit-image-0.13.1-py36hfa6e2cd_1
```

The problem here is `conda-forge::marshmallow-2.15.0-py_0` since it is a noarch package. At the time of writing this issue, this package was uploaded to conda-forge 13hours ago. However, I would expect constructor to fetch [this package](https://anaconda.org/conda-forge/marshmallow/2.13.5/download/win-64/marshmallow-2.13.5-py36_0.tar.bz2) instead (latest win-64 version at the time of writing this issue).

Is this a bug? If not, how to specifiy that the latest platform-specific version should be preferred over the latest noarch version (without manually looking for the right version and specifying it in the construct.yaml)?

**Comment by mingwandroid** [comment]
> Is this a bug

No it is an incompatibility it a missing feature.

If someone wants to submit a good PR to fix constructor so that noarch python can be used in all use cases then that's great. I don't expect anyone at Anaconda will have time for this. We just don't use noarch python due to these issues.

A PR that ignores new packages and bundles old ones is barely acceptable and if I were to accept it it would have to emit a warning each time this event happens.

**Comment by nehaljwani** [comment]
What if somehow we make constructor not consider the noarch channel at all (until it is ready for it)? :thinking:

**Comment by mingwandroid** [comment]
No not good enough IMHO. We'll just get bug reports that it's not picking up the latest packages with no indication as to why.

**Comment by ankostis** [comment]
> > What if somehow we make constructor not consider the noarch channel at all (until it is ready for it)? thinking
> 
> No not good enough IMHO. 
> We'll just get bug reports that it's not picking up the latest packages with no indication as to why.

Almost anyone using constructor knows about the notorious `noarch` issue,
demonstrated also by these bug reports:

- #243: constructor2.3 places noarch packages in `\site-packages` not `\lib\site-packages`
- PR #225: Overload Solver._prepare method to ignore noarch packages. 
- #214: Ignore noarch python packages 
- #210: conda-forge packages missing after installing
- #162: Constructor downloads noarch package if noarch package is more recent than the most recent platform-specific package
- #86: Support for noarch conda packages?

Btw, maybe you can group them under one `noarch` GitHub label, to keep track of them.

**Comment by nehaljwani** [comment]
Closing in favor of consolidating this at https://github.com/conda/constructor/issues/86
