### ISSUE TITLE
Windows uninstall is slow

### ISSUE THREAD

**Issue by kalefranz** [conda/constructor#168]
_From @lovettchris on January 30, 2018 8:27_

I'm submitting a bug report for the Anaconda Windows installer, I don't know if this is the right place.  But first I'd like to thank the team for providing such great windows support for Anaconda.  Awesome job.

The bug I think is that the uninstaller tries to print too much stuff to the screen, causing it to be very slow at deleting files.  So this UI takes for ever:

![image](https://user-images.githubusercontent.com/18707114/35555347-b5be5e04-0553-11e8-9546-9cf2c7ac637e.png)

## Current Behavior

The files are flashing by quickly but there are so many of them that the UI DrawText routine is taking all the time.  If one tries "rd /s /q" the folder can be deleted much more quickly than the Installer leads one to believe...

## Steps to Reproduce
Create 5 environments, each with lots of packages (100 or so), then uninstall Anaconda (conda install Jupyter is a good way to get lots of packages).

## Expected Behavior
The uninstaller UI could "self-throttle" the output by drawing on a separate rending thread at 30 fps whatever file name is currently being deleted, this will decouple the UI performance from the File system delete operation, and make the delete much faster.

_Copied from original issue: conda/conda#6815_

**Comment by kalefranz** [comment]
_From @Arkarbo on January 30, 2018 9:18_

Good job

**Comment by kalefranz** [comment]
_From @Arkarbo on January 30, 2018 9:18_

Rise to version

**Comment by reyemarr** [comment]
I have the same exact issue. 1hr 30 minutes and it's still going...

**Comment by kartikpodugu** [comment]
Any resolution for the issue? I am facing issue with anaconda version 5.3.1 as on 31st December 2018

**Comment by jimtodd92** [comment]
Any resolution on this issue? Its more than 2 hours since I gave uninstall and is still on..

**Comment by AlvaroPica** [comment]
I am currently facing this issue. 40 min and reading about 2h just scares me.

**Comment by Lajoyce** [comment]
Ugh...some 30mins later and I'm facing the same issue with 5.3.1 (64-bit). Uninstall is still going. Hopefully this won't take hours. Any resolution on this issue?

**Comment by soapy1** [comment]
This issue should be resolved by https://github.com/conda/constructor/pull/245. However, this will only help the uninstall for future uninstallers. In order to speed this up for older version I think your best bet is to delete the env and pkgs folder in the root of your installation before running the uninstall.
https://docs.anaconda.com/anaconda/install/uninstall/

**Comment by mystica2000** [comment]
TRY DELETING other PKGS while cmd one pkg uninstalls.by this it can speed up a bit. i tried it worked

**Comment by klaypigeon** [comment]
Holy crap your not kidding, mine has been running for about 15 minutes.  This is completely silly.

**Comment by zahs123** [comment]
hi how we make uninstall quicker?

**Comment by John-Polo** [comment]
It was running, more likely hanging, for > 20 minutes. I forced Windows to restart and the Navigator is still in the Programs list.
