### ISSUE TITLE
constructor or conda not pulling latest version of some packages

### ISSUE THREAD

**Issue by joelhullcio** [conda/constructor#170]
In the example below, constructor pulls down an older build of the package heapdict instead of the latest build.  I am suspicious that because the older version ends with a higher build number (1) than the later build (0) this is causing the issue.

This is causing a problem for our client JPM, not only this one package but others are also failing to pull the lastest build, resulting in an anaconda installer that does not contain the latest packages.

I think the fix is to increment the build number above the older builds build number and upload a new build of the packages.  Alternatively, a harder fix is to change how conda resolves package builds to account for the hash value in the build number.

Using constructor version 2.0.2 and conda 4.3.32

**Builds of heapdict on anaconda.org for OSX and py36:**

- osx-64/heapdict-1.0.0-py36h27a9ac6_0.tar.bz2 (uploaded ~4 months ago)
- osx-64/heapdict-1.0.0-py36_1.tar.bz2  (uploaded ~10 months ago)

**construct.yaml file:**
```
name: test
version: 1.0.0

channels:
  - http://conda.anaconda.org/anaconda
  - http://repo.continuum.io/pkgs/free
  - http://repo.continuum.io/pkgs/pro

specs:
  - python 3*
  - heapdict
```
**Notice in the constructor output that it uses build py36_1 (uploaded 10 months ago) instead of the later build py36h27a9ac6_0 (uploaded 4 months ago)**

constructor output:
```
name: test
version: 1.0.0
cache download location: /Users/jhull/.conda/constructor/osx-64
platform: osx-64
number of package: 18
    anaconda::python-3.6.4-hc167b69_1
    anaconda::ca-certificates-2017.08.26-ha1e5d58_0
    anaconda::certifi-2018.1.18-py36_0
    **anaconda::heapdict-1.0.0-py36_1**
    anaconda::libcxx-4.0.1-h579ed51_0
    anaconda::libcxxabi-4.0.1-hebd6815_0
    anaconda::libedit-3.1-hb4e282d_0
    anaconda::libffi-3.2.1-h475c297_4
    anaconda::ncurses-6.0-hd04f020_2
    anaconda::openssl-1.0.2n-hdbc3d79_0
    anaconda::pip-9.0.1-py36h1555ced_4
    anaconda::readline-7.0-hc1231fa_4
    anaconda::setuptools-38.4.0-py36_0
    anaconda::sqlite-3.22.0-h3efe00b_0
    anaconda::tk-8.6.7-h35a86e2_3
    anaconda::wheel-0.30.0-py36h5eb2c71_1
    anaconda::xz-5.2.3-h0278029_2
    anaconda::zlib-1.2.11-hf3cbc9b_2

fetching: python-3.6.4-hc167b69_1.tar.bz2
fetching: certifi-2018.1.18-py36_0.tar.bz2
**fetching: heapdict-1.0.0-py36_1.tar.bz2**
fetching: libffi-3.2.1-h475c297_4.tar.bz2
fetching: ncurses-6.0-hd04f020_2.tar.bz2
fetching: openssl-1.0.2n-hdbc3d79_0.tar.bz2
fetching: pip-9.0.1-py36h1555ced_4.tar.bz2
fetching: readline-7.0-hc1231fa_4.tar.bz2
fetching: setuptools-38.4.0-py36_0.tar.bz2
fetching: sqlite-3.22.0-h3efe00b_0.tar.bz2
fetching: tk-8.6.7-h35a86e2_3.tar.bz2
fetching: wheel-0.30.0-py36h5eb2c71_1.tar.bz2
fetching: xz-5.2.3-h0278029_2.tar.bz2
fetching: zlib-1.2.11-hf3cbc9b_2.tar.bz2
Checking for duplicate files ...
Reading: /opt/anaconda/lib/python2.7/site-packages/constructor/header.sh
Successfully created '/Users/jhull/projects/jeh/constructor/test-1.0.0-MacOSX-x86_64.sh'.
```

**Comment by msarahan** [comment]
The problem is that the http://conda.anaconda.org/anaconda channel merges the older "free" defaults channel and the newer "main" defaults channel.

We need to either change how mirroring is done (likely too disruptive) or bump build numbers on all of the "main" channel packages to be newer than the "free" channel packages.  We will be working on this over the next few days to identify all such packages and build updates.

**Comment by msarahan** [comment]
PS: to clarify how this happened: we changed all recipes to use conda-forge recipes instead of the old internal recipes.  This happened as part of the AD 5.0 release.  In replacing older recipes with ones from CF, we did not always catch things like build number differences.

Sorry for the trouble.

**Comment by msarahan** [comment]
heapdict and bzip2 have been rebuilt and uploaded to the main channel.  I believe the sync to anaconda.org takes place nightly.  This should be resolved for you tomorrow.

We are rebuilding several other files that will also be done by the end of the day today.

**Comment by joelhullcio** [comment]
@msarahan thank you for the quick response.  Should we be using the new "main" channel now instead "free" or both channels in our construct.yaml?

**Comment by msarahan** [comment]
Yes, that is probably best.

I would advise a channels section like this:

```
channels:
  - http://repo.continuum.io/pkgs/main
  - http://repo.continuum.io/pkgs/free
  - http://repo.continuum.io/pkgs/pro
```

The anaconda channel on anaconda.org is a merge of main and free.  They are better kept separate, so that channel priority can be respected.  I still recommend keeping free in your list, because there are some older packages that people may want.

**Comment by joelhullcio** [comment]
I think simplegeneric and pytz need to be re-built also.

**Comment by msarahan** [comment]
simplegeneric is in progress.  pytz was one we hadn't picked up yet, but will rebuild.  If you see more, please do keep posting them.

Our current list is at https://paste.fedoraproject.org/paste/jgd91rf8y-oWsE~FNaKr4w

**Comment by joelhullcio** [comment]
ipyparallel is giving us issues.  I think it needs a rebuild too.

**Comment by msarahan** [comment]
ipyparallel is not on the main channel at all - it is not troublesome for this reason.  It is also not part of the Anaconda distribution installer.  There are newer releases available that we can work on building, but I'm afraid this one will need to wait until after our release.  Ping @csoja for awareness/prioritization.

**Comment by jjhelmus** [comment]
ipyparallel 6.1.1 is now available for all platforms in the main channel.
