### ISSUE TITLE
Feature request: replace "Anaconda" by software name

### ISSUE THREAD

**Issue by forman** [conda/constructor#171]
In the panel **Advanced Installation Options** the installer refers to "Anaconda" rather than the actual software name provided by the `name` setting in the `constructor.yml` file:

![image](https://user-images.githubusercontent.com/206773/36026628-3e590268-0d98-11e8-987c-659bf7825cb6.png)

Users reported that this is very confusing, as they often never even heard of "Anaconda" and why at all they should allow Anaconda to be added to PATH instead of the software they are installing ("testomat" in the example above). 

Could you please 

- replace "Anaconda" by software name 
- or provide an option to do so, 
- or an option to skip the entire panel Advanced Installation Options.

See also comment on #38 by @ostueker from Apr 28, 2017.

**Comment by jaimergp** [comment]
Disclaimer: I am not a developer of the `constructor` project.

The name "Anaconda" is hardcoded all over the place in the [`nsis` files](https://github.com/conda/constructor/tree/master/constructor/nsis). This should be replaced by a environment variable call (like `${PY_VER}` is being used) or a template placeholder to be replaced, but it is not being done now.

Submit a PR with these changes! I could do it as well, but I won't be able to do so until next month approximately.

**Comment by forman** [comment]
@jaimergp Thanks for the investigation

**Comment by forman** [comment]
@nehaljwani @speleo3 Thanks! :)
