### ISSUE TITLE
Environment variables in construct.yaml

### ISSUE THREAD

**Issue by jaimergp** [conda/constructor#174]
Hi, I was expecting that some of the [environment variables available in meta.yaml for conda-build](https://conda.io/docs/user-guide/tasks/build-packages/environment-variables.html) were available in `constructor`, but they are not. 

I see that there is initial support for Jinja, and I tried to pass an `os.environ` copy to the jinja env [here](https://github.com/conda/constructor/blob/master/constructor/jinja.py#L28). This works, but to make all the conda-build env vars available, the code in [conda_build.environ](https://github.com/conda/conda-build/blob/master/conda_build/environ.py) should be ported over. Is this a good idea? I am particularly looking for the `GIT_*` tags to automate the version field like `version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}`.

-- EDIT --

I have forked and implemented basic Git support. It does not check as much as the conda build implementation (from where I copied the main logic), but seems to work for me.

Potential PR here: https://github.com/jaimergp/constructor/tree/jinja-env

**Comment by mcg1969** [comment]
@jaimergp I know this is an old one but I'd be happy to review a new PR based off of the significantly rewritten Constructor 3.x. That said the Jinja support hasn't changed much so I suspect your own changes wouldn't need to be modified much

**Comment by jaimergp** [comment]
Sure! It's been a while since I last used this but I might need in the future again, so I'll add this to my list. Can't promise a time estimate, though 😬
