### ISSUE TITLE
Bug: the cx_oracle package does not install correctly on Windows 64

### ISSUE THREAD

**Issue by joelhullcio** [conda/constructor#18]
The cx_oracle package gets included in the installer correctly but it does get fully installed so it cannot be imported.

This sample construct.yaml will reproduce the issue.  Build and installer and install it on Windows.

name: test
version: 1.0.0

channels:
  - http://repo.continuum.io/pkgs/free
  - http://repo.continuum.io/pkgs/pro

specs:
  - python
  - cx_oracle

**Comment by ilanschnell** [comment]
Still not sure that the exact problem with the package was, but the repackaged one works.
