### ISSUE TITLE
Do not ERROR when exclude item not found

### ISSUE THREAD

**Issue by joelhullpei** [conda/constructor#181]
In Constructor version 2.0.2 it will error out if an item in the exclude list is not found in the list of constructor files.   I think the default behavior should be to do nothing since the items is meant to be excluded anyway.  If there is a use case for erroring out then make that an option in the spec.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
