### ISSUE TITLE
Unexpected non-ASCII character

### ISSUE THREAD

**Issue by awacha** [conda/constructor#184]
Hi,

using constructor 2.0.3 installed from the standard conda channels, I found that it complains if one of the files (the LICENSE file in my project) contains an unexpected non-ASCII character, namely the 'á' from my name. Although I could use 'a' instead (without the acute accent), it might hit other people and other files as well, where non-ASCII characters might not be replaceable.

Thank you for considering this!

Andras

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
