### ISSUE TITLE
Properly populate info/repodata_record.json file

### ISSUE THREAD

**Issue by kalefranz** [conda/constructor#203]
In the constructor release for Anaconda 5.2, we got to tackle https://github.com/conda/constructor/issues/138.  For Anaconda 5.3, we need to make sure that extracted package directories in the package cache have a full `info/repodata_record.json` file.

Once that's the case, then it will be safe for installers to delete the tarball from the package cache.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
