### ISSUE TITLE
PyAppShare: cross-platform desktop python apps in a moment. With shortcuts

### ISSUE THREAD

**Issue by kiwi0fruit** [conda/constructor#205]
The problem I tried to solve in the [PyAppShare](https://github.com/kiwi0fruit/pyappshare) is almost the same as (conda) constructor use case. May be you could adapt something. In particular the [Shortcutter](https://github.com/kiwi0fruit/shortcutter) module for cross-platform shortcuts creation (it needs more testing on macOS though).

**Comment by mcg1969** [comment]
@kiwi0fruit, I'm grateful for the suggestion! It has been a long time and I'm trying to clean up issues so we can focus the community on the core priorities. However, w e would absolutely welcome specific enhancement requests and pull requests!
