### ISSUE TITLE
conda-mobile needs android/iOS support in constructor 

### ISSUE THREAD

**Issue by kiwi0fruit** [conda/constructor#206]
There is a nice project for using conda in Android/iOS: [conda-mobile](https://github.com/codelv/conda-mobile). The are [some interface issues](https://github.com/codelv/conda-mobile/issues/9) in it. And in order to fix these issues the convenient way it should be done the similar to (conda) constructior way (see [this](https://github.com/codelv/conda-mobile/issues/9#issuecomment-400174899)).

Is somebody interested in adding part of the conda-mobile toolchain to (conda) constructor or helping to implement packaging the right way (packages without prefixes, etc) in conda-mobile?

**Comment by mingwandroid** [comment]
No, this sounds like an itch you need to scratch.

To give some hopefully useful opinion on this `toolchains` should not be something that `conda`, `conda-build` nor `constructor` know anything about.

**Comment by mcg1969** [comment]
@kiwi0fruit that's an interesting project! I do agree with @mingwandroid this sounds like it warrants a separate project, and should not necessarily be merged into constructor. However if there are very specific, sufficiently generic enhancements that can be made to constructor that benefit _all_ platforms and conda-mobile too, we could consider them.
