### ISSUE TITLE
Update option in generated installer says 'installing'

### ISSUE THREAD

**Issue by alep** [conda/constructor#207]
This is straight forward:

When you call an installer created with constructor with -u, which in the help says 'update' the message displayed says 'installing' instead of update and it seems like a new installation

Basically `-u` option in the `header.sh`   recalls ./install.py which I guess redisplays 'installing message' instead of something saying 'updating' or 'reinstalling'

**Comment by nehaljwani** [comment]
I could settle for 'reinstalling'.
