### ISSUE TITLE
Better error message on Linux when using platform

### ISSUE THREAD

**Issue by bburan** [conda/constructor#224]
I did not realize that constructor only creates installers for the host platform. So, if I want to build an installer for Windows, I need to have access to a Windows machine. I was trying to (on a Linux computer), run the following:

    constructor . --platform="win-32"

I get the following error:

    platform: win-32
    Error: Can only create .pkg installer on Windows.

At first, I assumed I had configured something wrong so I tested on a Windows machine and it worked. It would be good to do the following:

* Document whether any form of cross-compiling for other architectures is possible
* Create a better error message (e.g., the error message could have said `Can only create exe installers using Windows`).

**Comment by hmaarrfk** [comment]
I could have sworn that I was able to create a cross platform installer for linux-aarch64 on linux-x86_64

though recent experiments suggest that this is not possible

https://github.com/conda-forge/miniforge/pull/1

**Comment by mcg1969** [comment]
Thanks to @isuruf we're back to having cross-platform installers.
