### ISSUE TITLE
Feature request: disable destop menu shortcuts

### ISSUE THREAD

**Issue by jschueller** [conda/constructor#237]
Hello,
I wondered if there is an option to disable installation of shortcuts in the destop menu for the windows installer ?

**Comment by dakcarto** [comment]
@jschueller, you can set the `menu_packages` key:
https://github.com/conda/constructor/blob/master/CONSTRUCT.md#menu_packages

However, this defines a subset that will have menus installed, while excluding all others. Maybe you can set `menu_packages` to an empty list or possibly a non-existent package name, to ensure _no_ menu items are created at all?

**Comment by jschueller** [comment]
Sounds like exactly what I want, thanks for the pointer!
