### ISSUE TITLE
Include urls.txt in package set

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#24]
It would be good for `conda` to know the channels from which the packages were taken when performing the initial installation. The easiest way to accomplish this is to include a `urls.txt` file into the package.

**Comment by mcg1969** [comment]
A simple fix is to add this line to `shar.create`:
```
    t.add(join(info['_download_dir'], 'urls.txt'), 'pkgs/' + 'urls.txt')
```
But this includes the entire `urls.txt` file, so if someone has built multiple constructors it will contain more URLs than necessary. With a bit more effort a custom `urls.txt` could be created.

**Comment by mcg1969** [comment]
I've confirmed that the above fix works well with https://github.com/conda/conda/issues/2526 to deposit the package URLs into `conda-meta` for later use.

**Comment by ilanschnell** [comment]
Version 1.3.0 creates installers which include `pkgs/urls`, which contains `<url>#<md5>`.  E.g.
```
$ cat pkgs/urls 
http://repo.continuum.io/pkgs/free/osx-64/python-2.7.9-0.tar.bz2#22dfaa90ad2811cd661b222cb9be36eb
http://repo.continuum.io/pkgs/free/osx-64/grin-1.2.1-py27_3.tar.bz2#8847fe0bbf6068012ea785ee355280c1
```
Although constructor always creates the file with both URL and MD5, the MD5 is optional in this new file.

It would be awesome if conda adopted the new format!

**Comment by ilanschnell** [comment]
Version 1.3.1 will also include the current `pkgs/urls.txt` format (with just URL) to stay compatible with current conda version.
