### ISSUE TITLE
Allow the "All Users" install location to be customized

### ISSUE THREAD

**Issue by danieljfarrell** [conda/constructor#247]
On the "Selection Installation Type" page the user can select:

```
Install for:
    [x] Just me (recommended)
    [ ] All Users (requires admin privileges)
```

In `construct.yaml` the `default_prefix` populates the default path for "Just me (recommended)" option. The "All Users" option default is different. Is is possible to control this path default too?

**Comment by mcg1969** [comment]
The default value of the All Users prefix is here:
https://github.com/conda/constructor/blob/master/constructor/nsis/main.nsi.tmpl#L41
It's not super straightforward to set INSTDIR, but it would be great to offer this capability.
