### ISSUE TITLE
Conda App Store and Conda Runtime Environment

### ISSUE THREAD

**Issue by kiwi0fruit** [conda/constructor#251]
I'm aware [how great](https://github.com/kiwi0fruit/pyappshare) it is to distribute crossplatform desktop apps via Conda.

I wonder if this could be turned into even more convenient end-user experience. Like a crossplatform App Store. And what is needed is not that many:

A small superviser app that automatically manages per-app envs (updates them, restores when Conda breaks them and itself without ability to repair, restores even root env, clears deleted env remnants and unused packages). 

Automatic updates for apps is specifically important. This should be possible as each app version would be sha-256 frozen deps. Package that creates crossplatform shortcuts is also needed. Like [shortcutter](https://github.com/kiwi0fruit/shortcutter) but much better.

That's the stuff that now is performed by power users of Conda ecosystem. But it can be automated via superviser app so that Conda distributed apps would  be available to common users.

**Comment by soapy1** [comment]
Is anaconda navigator the kind of thing you are looking for? 
https://docs.anaconda.com/anaconda/navigator/

**Comment by kiwi0fruit** [comment]
Sometimes conda root environment breaks. Rarely but it happens. There
should be a way for an installation to fix itself automatically. So no.
Definitely not a Conda navigator. And GUI for installing packages is not
the main idea. It's about app centered experience (that can even be website
only like Chocolatey). So the environment management in this UX should be
hidden and should not require manual fixing (that can now still be needed).
The latter can be achieved via fixing Conda to be more stable (I don't know
how hard it is) or via automating power user behavior in some kind of
supervisor app.

>
I've just written this and remembered about apt package manager vs. Ubuntu
and Gnome app stores. Different UX.

**Comment by kiwi0fruit** [comment]
Linked discussion: https://github.com/conda/conda/issues/8545
