### ISSUE TITLE
Enhancement request: set installation defaults

### ISSUE THREAD

**Issue by briantoby** [conda/constructor#254]
I would like to override the defaults used by the Windows installer. 

1. Advanced options: I would like to override the defaults so that neither the "Add to path" or "Register" are checked; even better would be be able to set this and remove the step from the install sequence. 

2) Install location: it is not clear to me how the default location is selected (sometimes it defaults to a Anaconda directory and other times a folder in ~), but I want to change the default destination to use a name not based on the package name and control the default location.

3) Just me/All users: this one is not a big deal, but I'd rather get rid of this option and always use "Just me."

Constructor is great, but this would allow the self-installers to be a bit more versatile.

**Comment by speleo3** [comment]
1. Already exists:
https://github.com/conda/constructor/blob/master/CONSTRUCT.md#initialize_by_default
https://github.com/conda/constructor/blob/master/CONSTRUCT.md#register_python_default
```
initialize_by_default: False
register_python_default: False
```
2. There is `default_prefix`, but implementation appears to be incomplete: #247

**Comment by mcg1969** [comment]
#3 is a great idea, and I think it is possible. I'm going to create a separate enhancement issue for this and close this one out, given that it looks like #1 and #2 are at least partially solved and/or covered by other issues.
