### ISSUE TITLE
Allow channels to be empty if channel_urls is not

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#261]
https://github.com/conda/constructor/blob/7e4d2f455c695227fdc9a25a75e8841917bf8862/constructor/fcp.py#L232-L233

Since the channels in the `src` entries of `channels_remap` are included in the source channel list, there should be no need to include them in `channels` as well. But if you are remapping _all_ of your channels, you exercise the error above if you don't also include at least one of those channels in the `channels` list.

**Comment by jjhelmus** [comment]
fixed in #315
