### ISSUE TITLE
`constructor --test` fails in 3.0.0

### ISSUE THREAD

**Issue by jakirkham** [conda/constructor#265]
Running `constructor --test` now fails with 3.0.0. The error message leaves the cause unclear. FWIW this worked in the past releases of Constructor.

```
$ constructor --test
usage: constructor [-h] [--debug] [--output-dir PATH] [--cache-dir PATH]
                   [--clean] [--platform PLATFORM] [--test] [--dry-run] [-v]
                   [-V] [--conda-exe CONDA_EXE]
                   DIRECTORY
constructor: error: too few arguments
```

**Comment by msarahan** [comment]
It's because the argparse stuff changed.  I think I'll change it back to having directory as an optional positional argument.

**Comment by jakirkham** [comment]
Ah ok. No worries. Thanks for taking a look. 🙂
