### ISSUE TITLE
channels is required (docs issue?)

### ISSUE THREAD

**Issue by cab938** [conda/constructor#266]
The docs indicate that channels are not required:

https://github.com/conda/constructor/blob/master/CONSTRUCT.md

When running without channels I get this error:

(base) brooksch@si:~/Downloads/constructor$ constructor .
platform: linux-64
Error: 'channels' is required

**Comment by mcg1969** [comment]
Good catch. It turns out that either channels or channels_remap must be empty. But neither are required. The autogen approach doesn't handle that nuance
