### ISSUE TITLE
Windows 10 Menu shortcuts are not created

### ISSUE THREAD

**Issue by AIWintermuteAI** [conda/constructor#270]
First of all, thank you for great work! It is a very useful project. Unfortunately I encountered some issues.

System:
Conda 4.7.11, Windows 10 Pro 1809 17763.615

I can successfully create a new installer with following .yaml file. But after installation, no menu shortcuts appear. 

```
Preparing transaction: ...working... done
Executing transaction: ...working... done
Delete file: C:\Users\Admin\ChaihuoPy\pkgs\env.txt
Output folder: C:\Users\Admin\ChaihuoPy\conda-meta
Extract: history
Creating ChaihuoPy menus...
Execute: "C:\Users\Admin\ChaihuoPy\pythonw.exe" -E -s "C:\Users\Admin\ChaihuoPy\Lib\_nsis.py" mkdirs
Running post install...
Execute: "C:\Users\Admin\ChaihuoPy\pythonw.exe" -E -s "C:\Users\Admin\ChaihuoPy\Lib\_nsis.py" post_install
Created uninstaller: C:\Users\Admin\ChaihuoPy\Uninstall-ChaihuoPy.exe
Completed
```
[construct.yaml.txt](https://github.com/conda/constructor/files/3499969/construct.yaml.txt)
I also enclose the full installation log.
[log.docx](https://github.com/conda/constructor/files/3499966/log.docx)

**Comment by mcg1969** [comment]
I believe you need to include the `console_shortcut` package on Windows to get those menus to be created.

**Comment by mcg1969** [comment]
And `powershell_shortcut` if you want the Powershell menu.

**Comment by mcg1969** [comment]
In other words, what you really want is:
```
specs:
  - python 3.5*
  - console_shortcut # [win]
  - powershell_shortcut # [win]
  - conda
```
The menuinst package will be pulled in by dependency here.
