### ISSUE TITLE
DEFAULT_PREFIX not respected for JustMe, IsDomainUser=0

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#271]
https://github.com/conda/constructor/blob/329020236da0828b4574c2c25133b8b17aea7246/constructor/nsis/main.nsi.tmpl#L452-L461

Is there a reason it must be this way? I wanted to set `default_prefix` on Windows, and it was having no effect in my tests; this proved to be why. If we remove the check for `IsDomainUser`, keeping the ElseIf branch, the behavior is as I expected.

**Comment by mingwandroid** [comment]
Looking at the git blame it's been this way since the code was imported (from whereever that was!)..

I think Ilan may be the only person who knows.

**Comment by mcg1969** [comment]
OK, I'm going to fix this. I actually think the If/Then is exactly backwards.
