### ISSUE TITLE
Is the install_in_dependency_order option still needed?

### ISSUE THREAD

**Issue by jlstevens** [conda/constructor#275]
My understanding of constructor 3.0 is that it is now using conda fairly directly behind the scenes. Does that mean the `install_in_dependency_order` option is no longer needed?

This option is shown in some of the examples and I am wondering if it is still respected or whether packages will always be installed in the appropriate order determined by conda.

**Comment by mingwandroid** [comment]
Very likely that is the case, yes. Pinging @nehaljwani for a quick confirmation (hi Nehal!)

**Comment by nehaljwani** [comment]
From what I understand, that option is no longer useful.

**Comment by mcg1969** [comment]
@jlstevens I think both this option and `attempt_hardlinks` are obsolete
