### ISSUE TITLE
Errors when installing miniconda to an unnormalised prefix

### ISSUE THREAD

**Issue by chrisburr** [conda/constructor#284]
## Current Behavior
Installing miniconda/anaconda into an unnomalised path results in the unnomalised path becoming part of the installation (e.g. `//home/myuser/miniconda`).

This has caused a reproducible relocation issue with a conda-forge package on macOS where anaconda was installed into `//anaconda3`. https://github.com/conda-forge/root-feedstock/issues/53

### Steps to Reproduce
```bash
# Install miniconda on macOS with a prefix which starts with //
conda create --name test-no-norm root python=3.7
conda activate conda
curl http://root.cern.ch/files/WM.root > test.root
root test.root
# See errors of the form
# Error in <TFile::TFile>: file anaconda3/envs/roottest/lib/libNet_rdict.pcm does not exist
```

## Expected Behavior
The install prefix given by the user should be automatically normalised.

## Environment Information
macOS with the latest miniconda installer.
Also seen with an older Anaconda install.

**Comment by mcg1969** [comment]
I've confirmed that the un-normalized prefix is making it into the metadata with shell installers.

**Comment by mcg1969** [comment]
This is _supposed_ to normalize things:
```
https://github.com/conda/constructor/blob/master/constructor/header.sh#L335-L336
```
But it doesn't. Interesting

**Comment by mcg1969** [comment]
It seems to normalize _almost_ everything but extra leading slashes

**Comment by mcg1969** [comment]
https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap04.html#tag_04_11
> A pathname that begins with two successive slashes may be interpreted in an implementation-defined manner, although more than two leading slashes shall be treated as a single slash.
Interesting. I was not aware of this.

**Comment by mcg1969** [comment]
@chenghlee @mingwandroid see above. We should make sure our Anaconda/Miniconda installers are tweaked to resolve this POSIX idiosyncracy.

**Comment by chrisburr** [comment]
Thanks for fixing this @mcg1969!

That's a interesting POSIX quirk to try and remember as Python's path manipulation functions also do this correctly:

```python
In [1]: from os.path import join, normpath

In [2]: normpath("//tmp")
Out[2]: '//tmp'

In [3]: join("//", "tmp")
Out[3]: '//tmp'

In [4]: join("/", "/tmp")
Out[4]: '/tmp'

In [5]: join("//", "/tmp")
Out[5]: '/tmp'
```

Apparently Cygwin actually uses this feature for network shares so it's something to be careful with but I think #397 will do the correct thing in all situations.
