### ISSUE TITLE
Specify forcing single user install in construct.yaml?

### ISSUE THREAD

**Issue by scottwsides** [conda/constructor#298]
Is there a way to force installing for a single user rather than choosing during the package extraction?

**Comment by msarahan** [comment]
Not at present. We'd be happy to review a PR if you're interested in implemening this.

**Comment by scottwsides** [comment]
I don't have time now. Maybe later. What would be involved in this?

**Comment by mcg1969** [comment]
This is a duplicate of newly-created issue #396! Hopefully someone can take it up.
