### ISSUE TITLE
How to NOT edit .bash_profile by default

### ISSUE THREAD

**Issue by scottwsides** [conda/constructor#299]
Is there a way to have the installers made by constructor to NOT edit the .bash_profile? This makes scripting and generally everything else very difficult to manage when using conda tools (which are in almost every other way excellent). I'm constantly cleaning by .bash_profile for things that keep getting written to it over and over.

**Comment by msarahan** [comment]
silent install: https://docs.anaconda.com/anaconda/install/silent-mode/#linux-macos

**Comment by scottwsides** [comment]
I already use the -b batch option when using miniconda installer. The .bash_profile gets edited when I unpack a pkg installer created by conda constructor. Is there a way to turn that off?

**Comment by msarahan** [comment]
On Mac? Don't use the pkg for scripted installs. Use a shell installer instead.

**Comment by scottwsides** [comment]
In this context...what is a shell installer? I want the pkg installer that
Mac creates. I just don't want it to pollute my .bash_profile
*Dr. Scott W Sides*
(303) 718-7028

**Comment by scottwsides** [comment]
During the pkg installer, one can choose to not change the PATH and the bash_profile. would be nice to have a parameter in the construct.yaml file so this is unchecked by default.

**Comment by speleo3** [comment]
@scottwsides Does this work for you?
```yaml
initialize_by_default: False
```
https://github.com/conda/constructor/blob/master/CONSTRUCT.md#initialize_by_default

**Comment by scottwsides** [comment]
I don't believe so. I've tried both and it seems the same each time. Again, if one clicks off the PATH option in the "Customize" install selection then doesn't pollute the bash_profile... its just that you have to do it through the installer pkg.
