### ISSUE TITLE
Issue if version number is of the form major.minor

### ISSUE THREAD

**Issue by astrofrog** [conda/constructor#3]
If I use a version number such as:

```
version: 1.0
```

then ``constructor`` crashes with the error:

```
Error: key 'version' points to <class 'float'>,
       expected <class 'str'>
```

But using:

```
version: 1.0.0
```

works fine.

**Comment by ilanschnell** [comment]
It will work when you say:
```
version: "1.0"
```

**Comment by ilanschnell** [comment]
https://github.com/conda/constructor/commit/96272d888cdebc1f86b2cb400c3f079090f28fcb allows you to also say:
```
version: 1.0
```
