### ISSUE TITLE
Global .condarc settings can break constructor

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#302]
Got a report from a user that a constructor installer failed as follows:
```
PREFIX=<REDACTED>
Unpacking payload ...
                                                                                                                     
CustomValidationError: Parameter ssl_verify = '<REDACTED>' declared in <<merged>> is invalid.
ssl_verify value '<REDACTED>' must be a boolean, a path to a certificate bundle file, or a path to a directory containing certificates of trusted CAs.
```
This is a bit surprising since constructor should be staying offline and not care. I need to verify if perhaps the provided .pem file is missing. Moving the user's .condarc file out of the way fixed the issue. But again I'd argue it should have no effect at all.

**Comment by mcg1969** [comment]
Perhaps exporting a CONDARC environment variable that points to nothing will do the trick

**Comment by ceejatec** [comment]
Conda itself will honor things in $CONDARC *in addition* to things specified in ~/.condarc. I presume constructor works the same way. There doesn't seem to be a "ignore user's .condarc" option for conda unfortunately.

**Comment by pelson** [comment]
I just came across this one. It meant that I was able to break an installer that I'd constructed (my condarc had strict ``channel_priority: strict`` and the installed failed because it had resolution conflicts)

**Comment by mcg1969** [comment]
Yeah I think we need to make sure that the standalone conda executable isn't even looking at condarc.

**Comment by mcg1969** [comment]
We can get it to ignore `~/.condarc` by overriding the HOME environment variable during execution.

To test, I created a file `fake-condarc` with a config setting `verbosity: 2`, and a `~/.condarc` with a config setting `verbosity: 1`. Then I looked at the verbosity level in several ways:
- `./conda.exe config --show`: `verbosity: 1`
- `CONDARC=fake-condarc ./conda.exe config --show`: `verbosity: 2`
- `CONDARC=nonexistent ./conda.exe config --show`: `verbosity: 1`
- `HOME=/fake ./conda.exe config --show`: `verbosity: 0`

So what this tells me is that `CONDARC` alone cannot prevent `conda.exe` from looking at `~/.condarc`, but setting `HOME` can.

**Comment by mcg1969** [comment]
Grr, that won't work, because then `HOME` won't be available to write `environments.txt` into.

**Comment by mcg1969** [comment]
OK, here's what will work.

1. Create a fake home directory with `.conda` subdirectory. I chose `$PREFIX/pkgs/.fake`
2. Copy the current value of `~/.conda/environments.txt` into `$PREFIX/pkgs/.fake/.conda/environments.txt`
3. Do the conda install but with Set `$HOME` and `$CONDA_PREFIX` set to this fake home directory
4. Copy the new value of `environments.txt` into its original location. Note that if `~/.conda` did not already exist, it needed to have been created _anyway_.
5. Clean up

It's a bit cumbersome but it works.

**Comment by mcg1969** [comment]
To verify this, add `verbosity: 3` (for example to your `~/.condarc`) and run an installer. The extra logging will reveal that `~/.condarc` is being picked up. With the fix I'm developing, it will not.

**Comment by mcg1969** [comment]
#374 implements this for windows, mac, and linux. If this issue matters to you, and the PR hasn't been merged yet, please check it out and offer feedback.
