### ISSUE TITLE
Installation PREFIX on windows

### ISSUE THREAD

**Issue by scottwsides** [conda/constructor#308]
How can I script finding the installation PREFIX in a post_install.bat script on windows. Presumably the exe installer is not in a default environment so I need the PREFIX to execute the correct activate script to start the base environment. Does anyone have this magic code?

**Comment by ericpre** [comment]
For example, the following should work to activate the environment:
```
call %PREFIX%\\Scripts\\activate.bat
```

**Comment by scottwsides** [comment]
YEs... if you know %PREFIX%. Thats the point. AFAIK, PREFIX is not known during the post_install step for the windows installer. Currently I'm getting this from a hack... CONDA_PKG_DIRS is known and one can derive the top level installation PREFIX variable from that.

**Comment by ericpre** [comment]
Indeed, PREFIX should be defined when the post install script is called. Is it not the case for you?
Linux and macosx works in a similar way, even if different installer are used.

**Comment by scottwsides** [comment]
I don't believe PREFIX is defined. On linux and mac I have to parse it out with

```
if [ xxx$PREFIX == 'xxx' ]; then
    PREFIX=$(echo "$2/__NAME_LOWER__" | sed -e 's,//,/,g')
fi
```

Didn't know how to translate this piece of magic into the black magic of windows bat scripting language.

**Comment by scottwsides** [comment]
My workaround for this is to use CONDA_PKG_DIRS and back out what PREFIX is. I'll close for now
