### ISSUE TITLE
installer fails when packages specified by `exclude`

### ISSUE THREAD

**Issue by bburan** [conda/constructor#310]
If I include the following in my `construct.yaml`:

      exclude:
          - openssl
          - pyopenssl
          - cryptography

The installer fails. If I don't include this, the installer works. In reviewing the details, I see that it's attempting to download these packages:

```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

<snip>

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cryptography-2.8           |   py37h7a1dbc1_0         570 KB
    openssl-1.1.1d             |       he774522_3         5.7 MB
    pyopenssl-19.0.0           |           py37_0          83 KB
    ------------------------------------------------------------
                                           Total:         6.3 MB

<snip>

Downloading and Extracting Packages
cryptography-2.8     | 570 KB    |            |   0% 
pyopenssl-19.0.0     | 83 KB     |            |   0% 
openssl-1.1.1d       | 5.7 MB    |            |   0% 
RuntimeError('EnforceUnusedAdapter called with url http://repo.anaconda.com/pkgs/main/win-64/cryptography-2.8-py37h7a1dbc1_0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
RuntimeError('EnforceUnusedAdapter called with url http://repo.anaconda.com/pkgs/main/win-64/pyopenssl-19.0.0-py37_0.conda\nThis command is using a remote connection in offline mode.\n',)
RuntimeError('EnforceUnusedAdapter called with url http://repo.anaconda.com/pkgs/main/win-64/openssl-1.1.1d-he774522_3.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
```

Let me know if it'd be helpful to have the full install log.

**Comment by forrestwaters** [comment]
Please see my comment here: https://github.com/conda/constructor/issues/319#issuecomment-576316765
Is there a reason you're wanting to exclude packages? The fact that it tried to download those packages (as opposed to reporting `PackagesNotFoundError`) was a conda bug that is now fixed

**Comment by bburan** [comment]
Yes. If we're preparing a conda install that may be downloaded by parties outside the US, we need to exclude cryptography packages to avoid running afoul of US export restrictions.

**Comment by msarahan** [comment]
Excluding packages doesn't mean that the functionality is just disabled. It
means that software built with those dependencies simply will not work. If
you need to provide installers without cryptography libraries, you're going
to need special builds of any package that ordinarily utilizes cryptography
libraries. This is likely a large job.
