### ISSUE TITLE
Including data files

### ISSUE THREAD

**Issue by scottwsides** [conda/constructor#312]
Is there a way to simply include a single file in the pkg installer? It could appear in the top level package installer or somewhere else.... but it would merely be present in the installation. It would not necessarily be a python module to be 'installed'.

**Comment by mingwandroid** [comment]
You can create a `build/noarch: generic` package that contains only data files and add that to constructor. Read more here: https://www.anaconda.com/condas-new-noarch-packages/

Please close if this is good enough.

**Comment by mingwandroid** [comment]
Oh, here is a modern example recipe: https://github.com/conda-forge/font-ttf-ubuntu-feedstock/blob/master/recipe

**Comment by scottwsides** [comment]
Thanks for the response and the example meta.yaml file. I've figured out a way to easily make a separate recipe package that includes a single file... then include that as a spec in the constructor construct.yaml file. I'll close out
