### ISSUE TITLE
How to activate constructed environment? Missing Scripts/activate 

### ISSUE THREAD

**Issue by danieljfarrell** [conda/constructor#313]
I have successfully constructed an installer on Windows 10.

However, how do I activate the constructed environment?

Normally I would do something like, `'anaconda root'\Script\activate.bat` which would setup all the correct paths to use the python environment. But the whole point of constructed environments is that they are portable and don't depend on an anaconda installation.

**Comment by msarahan** [comment]
The activation scripts are part of the conda package. If you don't include that with your installer, there are no activate scripts and you must manage PATH yourself some other way. It's probably much easier to just include conda. You might also want console_shortcut, which will give you Anaconda prompt directly into your installed environment. It won't work without conda in your installer, though.

**Comment by danieljfarrell** [comment]
Thanks! That’s clear. I will try that and maybe add comments below if I find anything useful that needs adding.
