### ISSUE TITLE
feature: pass options to pre and post install steps

### ISSUE THREAD

**Issue by bkreider** [conda/constructor#32]
This is a hard requirement for the AEN installers.  I had created the PR in cas-installer for this feature.  It was probably taken out because it isn't the cleanest implementation (ie: how to tell the difference between options sent to constructor vs. the pre/post scripts?) 

My implementation ended up passing all options onto the pre/post install scripts, so if your pre/post script depending on an option and constructor adds a new option, you could shadow the option.  

One option would be to define a namespace that is reserved for constructor and pass everything else through.  You'd need to switch to long options though.  Something like:  

`./my-installer.sh --constructor-batch --constructor-prefix /opt/install_path --pre-server-name 192.168.1.1 --post-do-cool-stuff=1`

**Comment by ilanschnell** [comment]
Why did AEN make the switch from `cas-installer` to `constructor`?  This is a feature which I consider wrong, as it encourages people to do things with `constructor` which it was never designed for.  A much better solution would be to separate the install process from the configuration process.

**Comment by bkreider** [comment]
>  This is a feature which I consider wrong, as it encourages people to do things with constructor which it was never designed for. 

That's why it is an enhancement:  to design it for this.  Is doing multiple steps to install software better for the person designing constructor or better for the person installing the software? I'm not sure how it is better (for the customer) to require them to jump through more hoops when there is an easy alternative. 

> Why did AEN make the switch from cas-installer to constructor?

They haven't, but I've been told that cas-installer is no EOL and it certainly doesn't work with Conda 4.0.  If it is easier to maintain cas-installer at the same time as constructor, the end result for AEN is the same.

**Comment by ilanschnell** [comment]
Constructor is for creating installers which install a conda environment, not for configuration steps.  This feature is not going to be added to constructor.  I was against adding this feature to cas-installer as well.  If you want to, I can update cas-installer to work with the new `libconda`, such that it becomes independent of conda (just like constructor).

**Comment by bkreider** [comment]
> If you want to, I can update cas-installer to work with the new libconda, such that it becomes independent of conda (just like constructor).

That would be good, because cas-installer is a blocker to shipping AE-Notebooks.

**Comment by damianavila** [comment]
>If you want to, I can update cas-installer to work with the new libconda, such that it becomes independent of conda (just like constructor).

Yes, please... if you can do that, otherwise we are blocked in AEN, as @bkreider said.

**Comment by ilanschnell** [comment]
I've tagged a new 1.4.0 version of `cas-installer`, and uploaded a Linux-64 bit package to:
https://anaconda.org/anaconda-server/
This depends on `libconda` and can be installed into any environment.

**Comment by damianavila** [comment]
@malev ^^^

Thanks @ilanschnell, we will try it.
