### ISSUE TITLE
Long path issue on windows

### ISSUE THREAD

**Issue by ericpre** [conda/constructor#325]
The default installation folder is given by "DEFAULT_PREFIX" and for single user on windows, its default value is `%LOCALAPPDATA%\Continuum\installer_name`, from: https://github.com/conda/constructor/blob/d52b5ef4cf2357b74e6d954d5f13851533909965/constructor/winexe.py#L106-L108

This does not work when installing jupyter lab (and its npm deeply nested folder structure) on windows system not supporting long path (more than 260 characters).

This may be a collateral consequence of https://github.com/conda/constructor/pull/316 and maybe the default value should be tweak.

As a workaround, using the following in `construct.yaml` work fine:
```
default_prefix: '%USERPROFILE%\installer_name' # [win]
```

**Comment by msarahan** [comment]
I think this is a good change to make.  People will likely still hit the NPM garbage, but at least it will be a bit better.
