### ISSUE TITLE
Installing Anaconda on AWS ubuntu fails with md5: command not found

### ISSUE THREAD

**Issue by avissens** [conda/constructor#328]
Hi!
I'm trying to install Anaconda on my EC2 instance.
These are steps:
```
wget https://repo.anaconda.com/archive/Anaconda3-2019.10-MacOSX-x86_64.sh
bash Anaconda3-2019.10-MacOSX-x86_64.sh
```
This is the error I get:

```
Anaconda3-2019.10-MacOSX-x86_64.sh: line 323: md5: command not found
WARNING: md5sum mismatch of tar archive
expected: d1e7d1722d2a83a749c1b23d2e4cf4e5
     got: 
Unpacking payload ...
Anaconda3-2019.10-MacOSX-x86_64.sh: line 357: /home/ubuntu/anaconda3/conda.exe: cannot execute binary file: Exec format error
Anaconda3-2019.10-MacOSX-x86_64.sh: line 359: /home/ubuntu/anaconda3/conda.exe: cannot execute binary file: Exec format error

```
Could anyone please suggest a fix?
Thanks!

**Comment by forrestwaters** [comment]
Looks like you may be trying to use the Mac installer on linux? Please try: https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh

**Comment by avissens** [comment]
Thank you! You are right. I copied the wrong path.
Now I have a different problem. Maybe you can help me with this?
First I got this error:
`ERROR: File or directory already exists: '/home/ubuntu/anaconda3'`
I removed the directory and all hidden files:
```
rm -rf /home/ubuntu/anaconda3
rm -rf ~/.condarc ~/.conda ~/.continuum
```
And tried to run my previous commands again. 
Now it is stuck on `Unpacking payload ...` Nothing happens, the terminal froze.
Have I missed a step while cleaning the directory?

**Comment by mcg1969** [comment]
This is actually not the right forum for this issue—this is the issue tracker for the open-source installer constructor package. Anaconda and Miniconda use a different pipeline. I think you may want this:
https://github.com/ContinuumIO/anaconda-issues
