### ISSUE TITLE
Error when requesting Python 3.8

### ISSUE THREAD

**Issue by applio** [conda/constructor#336]
When attempting to produce a conda installer containing Python 3.8, constructor v3.0.0 succeeds in producing a viable installer on Windows.

Using the same, simple `construct.yaml`, constructor fails with an error message on Linux:
```
Checking for duplicate files ...
Error: File 'lib/python3.8/__pycache__/_sysconfigdata_x86_64_conda_cos6_linux_gnu.cpython-38.pyc' found in multiple packages: pycosat-0.6.3-py38h7b6447c_0.conda, python-3.8.2-hcf32534_0.conda
```

Triggers a similar error on MacOS:
```
Checking for duplicate files ...
Error: File 'lib/python3.8/__pycache__/_sysconfigdata_x86_64_apple_darwin13_4_0.cpython-38.pyc' found in multiple packages: python-3.8.2-hc70fcce_0.conda, pycosat-0.6.3-py38h1de35cc_0.conda
```

The simplistic `construct.yaml` file used:
```
name: nolovefor38conda
version: 4.1.2

install_in_dependency_order: True

channels:
  - http://repo.anaconda.com/pkgs/main/

specs:
  - python 3.8*
  - conda

welcome_image: nolovefor38conda.png                  [win]
```

Modifying the above `construct.yaml` to instead request Python 3.7 or 3.6 succeeds on all platforms.  This suggests that the issue is triggered by the conda package for Python 3.8 (or possibly pycosat).  Whether that is correct or not, the issue remains that out-of-the-box, constructor currently appears to have difficulty producing a viable installer for Python 3.8 if one follows the documentation / examples for constructor.

**Comment by mingwandroid** [comment]
Thanks, will take a look

**Comment by mingwandroid** [comment]
Hmm, definitely not good. constructor is right (and it is right to complain). Both these packages carry the same file (by filepath) so it cannot know what to do.

We need pycosat to not have this file.

**Comment by mingwandroid** [comment]
This should be fixed now. Please re-test and report back if you can. I'll re-open if it doesn't work for you. On macOS and Linux, pycosat should now be 0.6.3 build 1. Cheers.

**Comment by applio** [comment]
Confirmed -- that fixed it on both problematic platforms.  I am now automatically picking up pycosat 0.6.3's _1 and I no longer trigger the error.

Thanks @mingwandroid !

**Comment by mingwandroid** [comment]
Thanks!

**Comment by david-zwicker** [comment]
I think I ran into the same error, albeit with different packages that I wanted to install:

```
Error: File 'lib/python3.8/__pycache__/_sysconfigdata_x86_64_apple_darwin13_4_0.cpython-38.pyc' found in multiple packages: fastcache-1.1.0-py38h1de35cc_0.conda, python-3.8.5-h26836e1_1.conda, gmpy2-2.0.8-py38h6ef4df4_3.conda
```


Here is the `construct.yaml` I used:
```yaml
name: py-pde
version: latest
installer_type: pkg

install_in_dependency_order: True

channels:
  - http://repo.anaconda.com/pkgs/main/
  - https://conda.anaconda.org/conda-forge
  
specs:
  - python 3.8
  - conda
  - py-pde
```

I'm currently running this on macOS in case this is relevant.
