### ISSUE TITLE
constructor doesn't update .bash_profile

### ISSUE THREAD

**Issue by maschull** [conda/constructor#337]
Maybe I don't understand. I thought that the installer would update the PATH so my program would be available but it doesn't seem to do that on a MacOS. Also I noticed that on linux it updates the PATH but only 1 program. If I install more than one program using the constructor created installer it only updates the .bashrc file for 1 file at a time.

**Comment by mcg1969** [comment]
I know this is a bit stale, but I think we need more specifics here. The installers does in fact run `conda init` by default, to make sure conda is properly initialized. Conda does not allow multiple environments to be on path;
