### ISSUE TITLE
Uninstall fails if WebEx Teams is installed

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#344]
There seems to be a conflict between WebEx Teams and the NSIS uninstaller. See the attached screenshots. The user has confirmed that shutting down WebEx Teams before uninstalling allows it to proceed. Is there anything different that can be done to avoid this workaround?

![img1](https://user-images.githubusercontent.com/2797735/83377494-3f91ce80-a39b-11ea-87fb-af4ef2117477.JPG)
![img2](https://user-images.githubusercontent.com/2797735/83377495-402a6500-a39b-11ea-89e8-4d58d2c12219.png)
![img3](https://user-images.githubusercontent.com/2797735/83377497-40c2fb80-a39b-11ea-8553-f3756e6b3850.jpg)
![img4](https://user-images.githubusercontent.com/2797735/83377498-40c2fb80-a39b-11ea-970d-0a55a6620248.jpg)

**Comment by jjhelmus** [comment]
Setting `CONDA_DLL_SEARCH_MODIFICATION_ENABLE` to `1` prior to running the installer might be a workaround to this problem.  My guess is that WebEx Team is installing DLLs into either system32 or a directory that is on PATH.  Windows will load those in preference to the libraries shipped in an installer.  The `CONDA_DLL...` activates an option in the Python shipped by Anaconda to switch the search order from which libraries are loaded.

**Comment by mcg1969** [comment]
Thanks @jjhelmus . I'm going to close this because I don't see a reasonably way for us to solve this inside constructor itself.
