### ISSUE TITLE
Miniconda3-latest-Linux-x86_64.sh does not tolerate spaces in the path to it

### ISSUE THREAD

**Issue by yarikoptic** [conda/constructor#347]
Please pardon if this is not the repository for the installer script... please move if needed.
It seems that if installer is under a path which has some spaces in one of the parent directory names -- it errors out!

I would recommend, if possible, to check any shell script components "mix into" it with `shellcheck` to ensure proper `""`ion etc

Origin: https://travis-ci.org/github/datalad/datalad/jobs/703768392#L766

This is a dedicated matrix environment where we test that datalad (and thus git, git-annex) operates correctly if there are spaces in the path.

Although there it is potentially an issue on our end as well (due to eval etc -- yet to troubleshoot/fix).  But now I have caused it fail differently locally in a similarish scenario so unlikely a fix on our end will be enough:

```shell
lena:/tmp/p a
$> TMPDIR="$PWD/tmp" bash ./Miniconda3-latest-Linux-x86_64.sh -b -p HERE
PREFIX=/tmp/p a/HERE
Unpacking payload ...
Collecting package metadata (current_repodata.json): done                                                        
Solving environment: done
...
Preparing transaction: done
Executing transaction: done
./Miniconda3-latest-Linux-x86_64.sh: line 449: /tmp/p: Is a directory
TMPDIR="$PWD/tmp" bash ./Miniconda3-latest-Linux-x86_64.sh -b -p HERE  10.52s user 2.85s system 99% cpu 13.459 total
```

**Comment by yarikoptic** [comment]
actually it is exactly what we see in our travis failed run if I specify full path prefix:
```
$> TMPDIR="$PWD/tmp" bash ./Miniconda3-latest-Linux-x86_64.sh -b -p "$PWD/HERE"
ERROR: did not recognize option 'a/HERE', please try -h
```
so there is multiple issues.

**Comment by mcg1969** [comment]
This is actually not the right forum for this issue—this is the issue tracker for the open-source installer constructor package. Anaconda and Miniconda use a different pipeline. I think you may want this:
https://github.com/ContinuumIO/anaconda-issues
