### ISSUE TITLE
Feature request: implement post_install scripts on Windows

### ISSUE THREAD

**Issue by briantoby** [conda/constructor#35]
At present, only Mac/Linux installers can run post_install scripts. Adding the ability to launch post_install .bat files (or a fix for #34 would be very helpful.)

**Comment by ilanschnell** [comment]
I've been working on this, and master now has this ability.  But master also has a new dependency `libconda`, which isn't released yet.  It will be a few days until one can `conda install constructor` and get `libconda` as well.

**Comment by briantoby** [comment]
thanks.

On Jul 6, 2016, at 11:48 AM, Ilan Schnell <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been working on this, and master now has this ability. But master also has a new dependency libconda, which isn't released yet. It will be a few days until one can conda install constructor and get libconda as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/conda/constructor/issues/35#issuecomment-230814394>, or mute the thread<https://github.com/notifications/unsubscribe/AI_yaGEoKb3o3_Nco5HLHgV8VruCbqeEks5qS849gaJpZM4JFe6Q>.

********************************************************************
Brian H. Toby, Ph.D.                            office: 630-252-5488
Advanced Photon Source Chief Computational Scientist
Senior Physicist/Computational X-ray Science Group Leader
9700 S. Cass Ave, Bldg. 401/B4192                 cell: 630-327-8426
Argonne National Laboratory
Argonne, IL 60439-4856         e-mail: brian dot toby at anl dot gov
********************************************************************
"We will restore science to its rightful place, and wield technology's wonders... We will harness the sun and the winds and the soil to fuel our cars and run our factories...  All this we can do. All this we will do."

**Comment by ilanschnell** [comment]
I released version 1.3.0 today.  From the changelog:
```
  * add ability to run `post-link` scripts (inside conda packages) on Windows
  * add ability to run post install `.bat` scripts on Windows
```
You can `conda install constructor`.  Here is how the Windows post link scripts are used, as part of one of the examples: https://github.com/conda/constructor/blob/master/examples/grin/construct.yaml#L34

**Comment by forman** [comment]
How would I best bundle Python scripts that should be executed by the post_install script or any other installer resources dealt with during post_install, e.g. icon images? 
I can imagine including a conda resource package that includes all install extras could solve this. Is this the intended way to achieve this?

**Comment by briantoby** [comment]
fixed, I think
