### ISSUE TITLE
channels in constructor should behave the same as in condarc

### ISSUE THREAD

**Issue by srossross** [conda/constructor#36]
It is confusing and inconvenient that `.condarc` acceptss `defaults` or `sean` but constructor requires a full url.

This also makes it harder do create installers with private packages because it does not respect `anaconda login`.

**Comment by kawing-chiu** [comment]
+1 for this. Also a simple path like `./my_repo/` works in other commands like `conda search -c ./my_repo/ --override-channels` but not in `construct.yaml`.

**Comment by mcg1969** [comment]
Constructor 3.x is significantly better in this regard. I think it's safe to consider this fixed. But do feel free to open a new issue.
