### ISSUE TITLE
Cross-platform installer builds don't work.

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#366]
The `--platform` flag no longer works because of the new use of conda-standalone

**Comment by mcg1969** [comment]
@jlstevens actually, I'll bet you can build a Linux installer with macOS and vice-verse _if_ you supply an explicit `--conda-exe` value that points to the proper platform version.

**Comment by mcg1969** [comment]
Actually, I tried it, and for the life of me I can't convince conda to pull the package for the correct platform when building cross-platform. I think we need to disable the `--platform` option

**Comment by jlstevens** [comment]
I had the same inclination that maybe supplying `--conda-exe` would do the trick. What I found *very* confusing is that conda was trying to use `conda.exe` on linux from an installer built on OSX. Surely `.exe` is the extension for windows binaries?

At any rate, disabling the `--platform` flag seems safest unless there is a reason that cross-platform building of installers is a priority.

**Comment by chrisburr** [comment]
I've just tried this with constructor 3.0.2 and it seems to work if I run on `linux-64` the below commands and then copy to native `linux-aarch64` or `osx-64`.

```bash
$ CONDA_SUBDIR=linux-aarch64 conda create --name conda-standalone-linux-aarch64 conda-standalone
$ CONDA_SUBDIR=linux-aarch64 constructor . \
      --platform=linux-aarch64 \
      --conda-exe=$CONDA_PREFIX/envs/conda-standalone-linux-aarch64/standalone_conda/conda.exe
```

Is it just that this needs the `CONDA_SUBDIR` variable? Or is there another problem?
