### ISSUE TITLE
pre_install and post_install are not always run in a bash-like shell

### ISSUE THREAD

**Issue by chrisburr** [conda/constructor#367]
## Problem

In https://github.com/conda/constructor/blob/master/CONSTRUCT.md it claims:

> ##### `pre_install`
> Path to a pre install script. This is available for Unix only, and must be a Bash script.
> 
> ##### `post_install`
> Path to a post install script. This must be a Bash script for Unix and a `.bat` file for Windows.

However the code actually runs the script in the current shell:

https://github.com/conda/constructor/blob/9ae44d4355da774220cd3aebf6ea40f58b51f37e/constructor/header.sh#L500-L503

This makes it quite hard to write pre/post install scripts that will reliably work on Linux and macOS.

## Proposed solutions

I see three options:

1. Allow the `pre_install.sh`/`post_install.sh` to be executable and just run them directly

2. Check the basename of the shell binary, and only allow known-good values such as `sh` and `bash`. If this isn't the use the fallbacks:

https://github.com/conda/constructor/blob/9ae44d4355da774220cd3aebf6ea40f58b51f37e/constructor/header.sh#L43-L52

3. Fix the documentation to make clear than the scripts must be able to run in any possible shell (bash/sh/fish/csh/xnosh/...)

I'm inclined towards 2. If people agree I can implement it in a PR.

**Comment by mcg1969** [comment]
Good find, @chrisburr. Just to be clear, though, if you always run the installer _itself_ with the same shell on both Linux and macOS, wouldn't that ensure correctness? I really appreciate your thoughtful set of options—but not sure I agree with your top choice. Let's put this out to the community for feedback, using https://github.com/apex/gh-polls

[![](https://api.gh-polls.com/poll/01EGV1DCKHFYRJRYEMZXQ1Y4WE/Directly%20execute%20pre-%20and%20post-install%20scripts)](https://api.gh-polls.com/poll/01EGV1DCKHFYRJRYEMZXQ1Y4WE/Directly%20execute%20pre-%20and%20post-install%20scripts/vote)
[![](https://api.gh-polls.com/poll/01EGV1DCKHFYRJRYEMZXQ1Y4WE/Limit%20running%20shell%20to%20bash%20and%20or%20sh)](https://api.gh-polls.com/poll/01EGV1DCKHFYRJRYEMZXQ1Y4WE/Limit%20running%20shell%20to%20bash%20and%20or%20sh/vote)
[![](https://api.gh-polls.com/poll/01EGV1DCKHFYRJRYEMZXQ1Y4WE/Clearly%20document%20current%20behavior)](https://api.gh-polls.com/poll/01EGV1DCKHFYRJRYEMZXQ1Y4WE/Clearly%20document%20current%20behavior/vote)

**Comment by jjhelmus** [comment]
Note that `/bin/sh` is not always `bash`, on most *nux systems it should be Bourne compatible shell but `dash`, `ash` or even `zsh` can be found.

**Comment by mcg1969** [comment]
Useful: https://superuser.com/questions/502984/writing-shell-scripts-that-will-run-on-any-shell-using-multiple-shebang-lines#503009

**Comment by chrisburr** [comment]
> Just to be clear, though, if you always run the installer itself with the same shell on both Linux and macOS, wouldn't that ensure correctness?

Yes. That might actually be the best option though the documentation should be amended with my next point as the shebang is `#!/bin/sh`.

> Note that /bin/sh is not always bash, on most *nux systems it should be Bourne compatible shell but dash, ash or even zsh can be found.

Indeed, if this option is chosen the documentation should be updated to say something like:
```diff
+ This must be a Bash script
- This must be a script that is compatible with any POSIX-compliant  shell
```

**Comment by mcg1969** [comment]
The more I think about it the more I think #2 is actually not enough. I suspect that we have all been guilty of introducing unintended Bash-isms into our shell scripts that we wanted to be POSIX compliant. If we do this, and we run the installer with a non-Bash `sh`, we will still have failures, because RUNNING_SHELL will be respected incorrectly.

So I think we need to basically do all three:
- If the shebang is present, respect it
- If the shebang is not present, use RUNNING_SHELL but not allow anything but `bash` or `sh`
- Document that for best results, either provide a shebang or use only POSIX-compatible shell commands.

**Comment by mcg1969** [comment]
I do like the idea of ripping out most of the shell detection code :-)

**Comment by mcg1969** [comment]
What if we just do that? That is: use `/bin/bash` if possible, `/bin/sh` otherwise.

**Comment by chrisburr** [comment]
I think it's better not to assume a shell is in `/bin` as there are systems where this isn't the case (IIRC NixOS doesn't have it).

> If the shebang is not present, use RUNNING_SHELL but not allow anything but bash or sh

How about using the same shell binary as the one that is executing the installer script by sourcing it in a subshell? It will be definitely be POSIX compliant. i.e. something like:

```bash
if [ -x "$PREFIX/pkgs/post_install.sh" ]; then
    # Script is executable so run it directly
    if ! "$PREFIX/pkgs/post_install.sh"; then 
        printf "ERROR: executing post_install.sh failed\\n" >&2 
        exit 1 
    fi
else
    # Else source it in a POSIX-compliant subshell
    if ! ( . "$PREFIX/pkgs/post_install.sh" ); then
         printf "ERROR: executing post_install.sh failed\\n" >&2 
         exit 1
    fi
fi
```

> I suspect that we have all been guilty of introducing unintended Bash-isms into our shell scripts that we wanted to be POSIX compliant.

Definitely. In case you've never come across it, having [`shellcheck`](https://www.shellcheck.net/) integration in your editor is a great way to avoid this.

**Comment by mcg1969** [comment]
I don't feel comfortable switching to `source`, but I think your if/then logic would make sense if we replace the source with a restricted `bash/sh` running shell.

How would you propose that `constructor` itself behave here? I think the simplest change is to reproduce the state of the executable bit on the `post_install.sh` script as it is stored in the constructor source directory.

**Comment by chrisburr** [comment]
I just noticed there is some kind of templating already in there so it could use that rather than looking for the executable bit. So something like:

```bash
#if has_post_install
#if execute_post_install_as_binary
if ! "$PREFIX/pkgs/post_install.sh"; then
#else
if ! sh "$PREFIX/pkgs/post_install.sh"; then
#endif
....
#endif
```

**Comment by mcg1969** [comment]
Yep, the logic can definitely be baked into the templating. Good find.
