### ISSUE TITLE
Constructor should use package cache

### ISSUE THREAD

**Issue by srossross** [conda/constructor#37]
A great optimization that would work well with continuous integration would be to use the local package cache if available

**Comment by ilanschnell** [comment]
The local package cache?  Not sure what you mean.  When you install the `pkgs` is created as part of the install process.

**Comment by srossross** [comment]
It would be good to keep the files packaged in the installer loaded in the package cache so that way running `construct` twice would only download the packages once.

**Comment by ilanschnell** [comment]
Yes, that's already the case.  The packages are cached in `~/.conda/constructor/`.

**Comment by srossross** [comment]
Ah, sorry I was fooled because it does not use the same cache that `conda install` uses.
