### ISSUE TITLE
new release post 3.0.2

### ISSUE THREAD

**Issue by hmaarrfk** [conda/constructor#375]
A few new features have been added and fixes.

most notably:
https://github.com/conda/constructor/pull/342#issuecomment-667227179

A new release would be appreciated, I mostly don't want the comment above to get lost.

@jakirkham @jschueller

**Comment by mcg1969** [comment]
Yep, this is a good idea. Let me work on it

**Comment by mcg1969** [comment]
@scopatz I wonder if you could offer a bit of assistance or advice on this, specifically how best to leverage Rever at this point. I must confess that being unfamiliar with the tool I have not leveraged the news support for instance—although it doesn't seem other authors have, either. Perhaps we can engineer a compromise solution for this release, with a proper disciplined use of rever for subsequent PRs/

**Comment by scopatz** [comment]
Ahh yeah, if you don't care about news that can just be commented out in the `$ACTIVITIES` list. Also, if you want me to run the release and we can figure out how to give me permissions to do that, I 'd be happy to.  Basically, the main rever cycle is to run:

```sh
$ rever check
$ rever X.Y.Z
```

Check should tell you if you have the proper env and permissions to run the release before actually running it.  Again, I am happy to help however I can!

**Comment by mcg1969** [comment]
Thanks. I'll do this, with a static changelog update for now

**Comment by mcg1969** [comment]
I think we need a fix equivalent to #376 before we release. Working on it today

**Comment by mcg1969** [comment]
3.1.0 has been tagged.
