### ISSUE TITLE
Feature request: Startmenu and Desktop shortcuts

### ISSUE THREAD

**Issue by forman** [conda/constructor#38]
I'm trying to use constructor to bundle and distribute my Python application.

On Windows, it seems that constructor unconditionally installs menu items found as JSON files in the `Menu` folder of the Miniconda3 root installation. Could you please make this an optional behaviour?

On the other hand it would be great if constructor users could provide their own JSON files which would be turned into Windows Startmenu and Desktop shortcuts, e.g. for launching their applications with a preconfigured Python environment. 

The same applies of course to OS X Dock entries and Ubuntu Desktop shortcuts. However, from looking at the code it seems easy to enable this for Windows by conditionally enhancing the NSIS script.

Thanks
-- Norman

**Comment by forman** [comment]
Ok, I now figured out how packages create at least Startmenu entries on Windows: Let their `bld.bat`  copy an icon and a menu JSON into *their* `Menu` folder. The doumentation at http://conda.pydata.org/docs/building/build.html does not mention this very useful feature.

**Comment by ilanschnell** [comment]
The startmenus are basically handled the same way conda handles them, which is by calling out to the `menuinst` package.  The easiest way not to install menus is by removing `menuinst` from the list of conda packages included.  This is done by adding the following to the `constuct.yaml` file:
```
exclude:
  - menuinst
```

**Comment by forman** [comment]
@ilanschnell Thanks for the tip! What is the actual problem with the `menuinst/darwin.py` and `menuinst/linux.py`? They don't look bad to me at all.

**Comment by ilanschnell** [comment]
I'm not even sure if there is a problem.  `menuinst` was forked from `appinst` about 3 or 4 years ago, which did support Linux and Mac.  We did that support menu installation on Windows, but we have never tested or done anything with the Linux and Mac code.
The code itself will probably work for Linux and Mac, but the interface might have changed.  Also `appinst` at the time only supported Python 2, so this code might have Python 3 issues.

**Comment by forman** [comment]
Ok found https://github.com/ContinuumIO/menuinst/issues/19 and forked the repo. We'll give it a try and maybe it will receive a pull request later on.

**Comment by ostueker** [comment]
I have a related question:  Is there a way to influence the name of the Windows Start Menu folder that is created (using menuinst and create_shortcuts packages)?

I'm creating a custom conda installer with constructor an the Start Menu folder is always called "Anacona 3 (64bit)", which places the shotcuts in the same place with other Anaconda installations.

**Comment by bburan** [comment]
I figured out how to add entries to the Windows start menu by configuring my conda package properly (e.g., add a `windows-menu.json` and a `bld.bat` script that copies the contents of the `windows-menu.json` to the correct folder). When I test this using the base conda environment, the entry appears in the start menu. However, when I try to create an installer using constructor, it does not create the menu items. Do I need to do this by via a post-install script?

**Comment by mcg1969** [comment]
The `menu_packages` option now provides control over what menus are created.
https://github.com/conda/constructor/blob/master/CONSTRUCT.md
