### ISSUE TITLE
Construct.md  document: `environment` specifier suggests 'name', not 'path'

### ISSUE THREAD

**Issue by okz** [conda/constructor#385]
Construct.md  sugest `environment` specifier is supposed to be the 'name' of the environment.  Command line failures suggests this should be the 'path': 

```
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/mirico/miniconda3/bin/conda', 'list', '--prefix', 'clads', '--json']' returned non-zero exit status 1.
```

Passing the path of the environment does seem to  work. 

## `environment`

_required:_ no<br/>
_type:_ string<br/>
"Name" of the environment to construct from.If this option is present, the specs argument will be ignored. Using this option allows the user to curate the enviromment interactively using standard conda commands, and run constructor with full confidence that the exact environment will be reproduced.

**Comment by mcg1969** [comment]
Thank you for the report!

**Comment by mcg1969** [comment]
Actually I'm not sure about this one. Here is the relevant code:
https://github.com/conda/constructor/blob/master/constructor/fcp.py#L205
```
    list_flag = "--prefix" if isdir(environment) else "--name"
```
Where is the environment you've created living, relative to the current directory?

**Comment by okz** [comment]
hah.. I should have looked at the code...

The environment name matched the package I was developing, and I usually keep the constructor.yaml in the repo's root folder, which has the package subdir with the same name as well..

Maybe the definition should suggest 'name' or 'path' of the environment? 

or maybe a sub heading specifying name, or path: 

```
environment: 
    name: <env-name>
     # or
    path: <env-path>
```

**Comment by mcg1969** [comment]
I do admit it's trying to be a little smart. Conda doesn't even try to be this smart :-) Will think of a good way to document this.
