### ISSUE TITLE
pkg on mac requires conda in specs

### ISSUE THREAD

**Issue by scopatz** [conda/constructor#386]
On v3.1.0, it appears that generated pkg files require `conda` itself to be listed in the specs. The failure occurs towards the end in the "Running package scripts..." part of the installation.  This indicated to me that the standalone version of conda is not being used during this phase for some reason, and it is instead looking in the newly created environment.

This can be reproduced with a simple construct.yaml whose only spec entry is `python`.  A pkg file created in this way will fail to install. If you then add `conda` as a second spec, the pkg file will complete the install process.

**Comment by mcg1969** [comment]
Hmm, thanks for finding this—honestly it's a gap in my testing because we include conda in virtually all builds.

**Comment by mcg1969** [comment]
I think it's the "Add conda initialization to the shell" step—which of course should not even be considered if conda is not included. I found that if I disable that script, the install completes successfully. Should be an easy fix
