### ISSUE TITLE
Spurious(?) Post-Install Error Message on Windows

### ISSUE THREAD

**Issue by briantoby** [conda/constructor#39]
Adding wxpython to the grin demo package (see attached .yaml) causes the windows self-installer to display an error message "Failed to run post install script". There is no evidence that wxpython has a post-install script.  

<img width="179" alt="g2installwarning" src="https://cloud.githubusercontent.com/assets/9433704/17273447/6d2d1b3c-567a-11e6-95fb-17487b6865fa.png">

[construct.yaml.txt](https://github.com/conda/constructor/files/392122/construct.yaml.txt)

**Comment by jgmorrison** [comment]
Issue has been verified as we are able to reproduce this. Tested on 2 separate packages(including Grin example) and they both give the error "Failed to run post-install script".

>Running post install...
Execute: "C:\Users\builder\g2conda\pythonw.exe" -E -s "C:\Users\builder\g2conda\Lib\_nsis.py" post_install
Execute: "C:\Users\builder\g2conda\pythonw.exe" -E -s "C:\Users\builder\g2conda\Lib\_nsis.py" addpath
Created uninstaller: C:\Users\builder\g2conda\Uninstall-Anaconda.exe
Completed


Issue does not occur if WXPython is removed from construct.yaml.

**Comment by ilanschnell** [comment]
I was able to reproduce the problem, but I haven't had time to investigate further.

**Comment by briantoby** [comment]
nag, nag, nag,...

This is still causing problems for users, who (justifiably) think something is wrong when "Failed to run post install script" pops up and thus headaches for me. I am not sure I want to take on building the wxpython package myself, but I am at least willing to look at its conda package .yaml file to to see if there are any obvious indications of what might be causing this.

**Comment by briantoby** [comment]
this seems to be fixed
