### ISSUE TITLE
ALLUSERSPROFILE from build machine is used

### ISSUE THREAD

**Issue by isuruf** [conda/constructor#391]
Instead of on the user's machine

**Comment by mcg1969** [comment]
Hmm, good find. Is there some escaping that we're missing?

**Comment by isuruf** [comment]
I don't think so. https://nsis-dev.github.io/NSIS-Forums/html/t-280131.html says that `$%AllUsersProfile% ` is the wrong thing to use here.

**Comment by mcg1969** [comment]
I'm not sure I understand the solution they are proposing. Any chance I can trouble you for a PR? Or at least more detail on what I need to change?

**Comment by mcg1969** [comment]
I can work on it this weekend.

**Comment by isuruf** [comment]
I think we'll have to use ReadEnvStr to read the env variable from the user. I have zero experience with writing nsis scripts, so I'll probably be useless.
