### ISSUE TITLE
Did tag 3.1.0 get recreated?

### ISSUE THREAD

**Issue by hmaarrfk** [conda/constructor#393]
Seems like the sha256 changed according to conda-forge's build system
https://github.com/conda-forge/constructor-feedstock/pull/42

**Comment by jakirkham** [comment]
It seems to [exist]( https://github.com/conda/constructor/releases/tag/3.1.0 ).

That said, GitHub autogenerates archives for the tag on-demand. As a result, if there are any changes in that process (including timestamps of files in the archive), the checksum will differ. So these checksum changes do happen periodically unfortunately.

To avoid these kinds of issues, it helps when projects upload an archive and attach it to the release as an artifact. That way we are able to download something stable. Though not many projects do this.

**Comment by hmaarrfk** [comment]
i see, thanks for the explination
