### ISSUE TITLE
Build proper documentation

### ISSUE THREAD

**Issue by mcg1969** [conda/constructor#398]
If someone is looking to take on an easy contribution to this repository, building proper documentation would be extremely helpful. I'm thinking particular something that would into, say, `conda.github.io/constructor`.

**Comment by epassaro** [comment]
Hi. I would like to contribute on this.

I made an example [GitHub workflow](https://github.com/epassaro/constructor/pull/2/files) and [this is the result](https://epassaro.github.io/constructor)

Did I understand correctly the purpose of this issue?

**Comment by FaustinCarter** [comment]
I'd like to add a plug to include the information from #404 in whatever documentation is built.
