### ISSUE TITLE
Windows Uninstall removes menu items from other installs

### ISSUE THREAD

**Issue by FaustinCarter** [conda/constructor#403]
I have Miniconda installed in `%UserProfile%\Miniconda3` and my custom installed conda made with constructor in `%UserProfile%\MyCustomConda`. When I run `%UserProfile%\Uninstall-MyCustomConda.exe`, during the step where it removes any menu items (i.e. in `%UserProfile%\MyCustomConda\Menu`), it _also_ uninstalls all the menus defined in `%UserProfile%\Miniconda3\Menu`. This is definitely a bug!

**Comment by mcg1969** [comment]
Agreed!
