### ISSUE TITLE
Use of PREFIX in post_install script

### ISSUE THREAD

**Issue by FaustinCarter** [conda/constructor#404]
It would be useful to be able to activate the newly installed conda environment in the post_install script, but there is currently no way of knowing where the user chose to install it. Is there some way to call post_install from a shell that has some appropriately named env var reflecting this information?

**Comment by mingwandroid** [comment]
$(dirname "${BASH_SOURCE[0]})") or equivalent should work.

**Comment by FaustinCarter** [comment]
Ah, thanks very much. For the Windows users the activation script would be at `%~dp0..\Scripts\activate.bat`.

It would be helpful to add a note to the documentation under the pre/post install script items.

**Comment by mcg1969** [comment]
Great solution, @pelson . I think it would be wise for this to be included in documentation. To that end I'll leave the issue open and label it a documentation issue.

**Comment by sthiele** [comment]
How does it work on windows? My my post_install.sh looks like this:
```sh
#!/bin/sh
pip install cameo==0.11.15 cobra==0.18.1 qtconsole==4.7.7
```
I want the additional packages installed into the newly created environment.

**Comment by mingwandroid** [comment]
You cannot use a shell script on Windows like this. You need to use batch files. The env set by your attempt to call a batch file from a shell script (bash knows nothing of %~dp0) will not work. Even though it is possible to launch a batch file from a shell script (using e.g. MSYS2 or WSL) the environmental changes it makes are not passed back to the calling shell environment.

I also recommend not using pip at install time, it defeats the purpose somewhat of using constructor. Can you not use conda packages and bundle them?

**Comment by sthiele** [comment]
> You cannot use a shell script on Windows like this. You need to use batch files. The env set by your attempt to call a batch file from a shell script (bash knows nothing of %~dp0) will not work. Even though it is possible to launch a batch file from a shell script (using e.g. MSYS2 or WSL) the environmental changes it makes are not passed back to the calling shell environment.

Thanks, this makes sense.

> I also recommend not using pip at install time, it defeats the purpose somewhat of using constructor. Can you not use conda packages and bundle them?

I know. I wish I could get all my dependencies via conda but unless I package them myself they are not available for windows.

**Comment by pelson** [comment]
fwiw, on linux I bundle wheels into a conda metapackage. I then call the necessary pip install command (pointing at the bundled files from the conda package) in a post-install of the constructed installer. It isn't pretty, but it works effectively, and means that the resulting installer remains an entirely "offline". In practice, this kind of thing could be built into conda and/or constructor if there was sufficient appetite.

IMO there is a lot of value in improving the story for installing **pure Python wheels** (i.e. distributions where we know we don't need a compiler) with conda in general... this would unlock the ability to install thousands of packages that haven't been and probably wont be packaged with conda[-forge].

**Comment by sthiele** [comment]
An update from my side my post_install.bat script now looks like this.
```bat
call %~dp0..\Scripts\activate.bat
pip install cameo==0.11.15 cobra==0.18.1 qtconsole==4.7.7
```

**Comment by sthiele** [comment]
> ```
> call %~dp0..\Scripts\activate.bat
> pip install cameo==0.11.15 cobra==0.18.1 qtconsole==4.7.7
> ```

Though, what would be the equivalent to activate the environment in a shell script?

**Comment by sthiele** [comment]
In my `post_install.sh` i activate the environment like this:
```
#!/bin/sh
source $PREFIX/etc/profile.d/conda.sh
conda activate $PREFIX
```

**Comment by mcg1969** [comment]
I don't understand why you would do that. What purpose does that serve? Once the installer is done, this will just go away.

**Comment by mcg1969** [comment]
Oh, sorry, I think I misunderstood, @sthiele ... I realize you are taking additional steps _after_ that activation

**Comment by FaustinCarter** [comment]
> For those finding this through google, in Linux you are also given `$PREFIX` and any other variable which is exported in the template in https://github.com/conda/constructor/blob/master/constructor/header.sh.

`%PREFIX%` is also available on Windows. It gets set [here](https://github.com/conda/constructor/blob/1d1ee2d553af9e48c249483990ee52afa71f129c/constructor/nsis/_nsis.py#L181).

**Comment by FaustinCarter** [comment]
This issue should stay open. Documentation is still needed.
