### ISSUE TITLE
[question] is there any plan for a new release?

### ISSUE THREAD

**Issue by xmnlab** [conda/constructor#407]
Hey everyone!

I am having problems fixed by https://github.com/conda/constructor/pull/401 and I am wondering if is there any plan for a new release that would include that.

Thanks!

**Comment by mcg1969** [comment]
Thanks for the ping, @xmnlab . I do think we're likely due for a new release. However, note that each master commit is built into a conda package, and available in the `dev` subchannel. So for instance,
```
conda install ctools/label/dev::constructor
```
should get you the latest build including all of the recent merged PRs.

**Comment by xmnlab** [comment]
that sounds interesting! thanks @mcg1969 !

**Comment by mcg1969** [comment]
3.2.0 has been tagged.

**Comment by xmnlab** [comment]
@mcg1969 thanks for letting me know!
