### ISSUE TITLE
Ignore excluded packages that do not exist

### ISSUE THREAD

**Issue by joelhullcio** [conda/constructor#41]
When the exclude list includes a package that doesn't exist the build will fail.  Instead of failing just ignore the package and continue.  This shouldn't be an error case since the package is suppose to be excluded.  At a minimum only output a warning but don't fail.

Example constructor.yaml that will fail.

```
name: test
version: 1.0.0

channels:
  - http://repo.continuum.io/pkgs/free
  - http://repo.continuum.io/pkgs/pro

exclude:
  - abc123

specs:
  - python 2.7.12
  - anaconda 4.1.1
  - conda
```

**Comment by ilanschnell** [comment]
Please help me understand why you want to change the current behavior.  I think the build should fail if the package does not exist, because if you might have a type in the package name.
