### ISSUE TITLE
Windows: Install to %USERPROFILE% is not appropriate for roaming profiles

### ISSUE THREAD

**Issue by benpapworth** [conda/constructor#412]
This fix did correct some bad logic with domain user selection:
https://github.com/conda/constructor/commit/d5a4ceba3bbec5f7568ba42311809787347fcc11

But, making the default for domain users install to %USERPROFILE% is a bad choice because the installation (which can grow to Gbs in size) will now be in the roaming profile by default; therefore sync'd with network at each login/logout. As soon as conda install becomes large enough, this will timeout and break the roaming sync process. Most end users will not be aware of this subtle problem until it significantly slows their log-in/log-out time or breaks their roaming profile synchronization.

It would be more appropriate to:
* Not ignore DEFAULT_PREFIX, if defined, for JustMe installs, or provide a DEFAULT_JUSTME_PREFIX to allow installer writers to control the option.
* The default install location should be %LOCALAPPDATA%, as this is not on the roaming profile, but is still owned by the domain user on the workstation. This will avoid future roaming profile sync problems.

**Comment by benpapworth** [comment]
Updating HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\ExcludeProfileDirs with extra directories might be an option too, but care would have to be taken to understand whether this is also part of the roaming configuration, and therefore at risk of race conditions on update overwrites when multiple simultaneous logins are active.

**Comment by mcg1969** [comment]
Thank you for the feedback! I've tagged your issue and will leave it open. Despite my recent streak of commits I'm personally going to be unable to fix this in the near term, but if someone can contribute a PR I am absolutely happy to review.

**Comment by benpapworth** [comment]
Thank you, I am hoping to contribute myself at some point.

Many thanks on making an excellent package manager, which I think should be pushed as the standard for Python.

All the best,
Ben

**Comment by benpapworth** [comment]
@ericpre @mcg1969 thank you for your contribution; this will help to prevent a lot of issues for users with domain accounts.

**Comment by ericpre** [comment]
@benpapworth, your bug report and suggestion was very good and clear, so it was very easy/quick to fix really!
