### ISSUE TITLE
How can I protect myself against bad changes from upstream repository channels?

### ISSUE THREAD

**Issue by ceejatec** [conda/constructor#414]
Yesterday and again today, a change in repo.anaconda.com broke our Windows builds. We have a 
[construct.yaml](https://github.com/conda/constructor/files/5539990/construct.yaml.txt) which includes "six 1.15.0" and "wheel 0.33.1", and yesterday they uploaded a new version of "six 1.15.0" which is broken - it contains a file which is duplicated from the wheel package. I filed https://github.com/ContinuumIO/anaconda-issues/issues/12156 about that. I was able to work around it by backing up to six 1.14.0.

Today they did it again with a new version of win_inet_pton that contains the same bad duplicate file. In this case, there are now two win_inet_pton 1.1.0 packages on repo.anaconda.com:

win_inet_pton-1.1.0-py37_0.tar.bz2
win_inet_pton-1.1.0-py37haa95532_0.tar.bz2

The first one works, the second is broken. However, in construct.yaml, I can't find any way to specify which of those I want. Well, I can specify the complete explicit URL, but that means that my construct.yaml is no longer cross-platform compatible. In this particular case that's good enough, since the win_inet_pton package is Windows-only, but in general that's very awkward at best.

I guess I'm looking for best practices here to avoid being bitten by bad upstream changes in future. I had expected that specifying fully explicit version numbers in construct.yaml would be sufficient, but evidently it is not because they can re-publish those same versions with new errors. Are there other suggestions?

**Comment by mcg1969** [comment]
There are multiple reasons why new builds of a package with the same version number might be posted. In fact, on occasion, it is even necessary to patch the metadata of existing package builds.

But note that you can specify more than just the version number—you can also specify the _build string_ as well. This will definitely make it more likely that you can capture exactly the packages that you want. For instance, in the case of six 1.15.0, I notice that there is a `noarch` version with the `py_0` build string from 5 months ago—that is likely the one that you were using before—and the newer ones are now built for a specific OS and Python version, and have build strings like `py38h06a4308_0`. By specifying a `py_0` build string in your construct.yaml specification, you can actually make sure you do not get the newer package version.

I hope this helps for now!

**Comment by mcg1969** [comment]
My other recommendation would be to include `ignore_duplicate_files: true` in your construct.yaml. Duplicate files are often benign but construct.yaml does tend to error on the side of being picky.
