### ISSUE TITLE
Request: Support 'local' Channel in channels_remap

### ISSUE THREAD

**Issue by benpapworth** [conda/constructor#416]
In the channels_remap, I would like to ask if 'local' meta-channel could be supported as a 'src'. This is the common channel name for local package builds in conda and conda-build.

During remapping, the 'local' channel should remap file:// URL of CONDA_BLD_PATH (generated by conda.common.url.path_to_url) as the src string to remap to the target channel.

The reason I think it would be useful as a specific target is because, if the URL is written out by hand in the constructor.yaml, it has to exactly match the URL generated by conda.common.url.path_to_url. This is not easy to get right across platforms, and the path maybe unstable under some CI configurations. My osx-64 build, for example, always has a few lowercase directory names in the path for some inexplicable reason!

My current workaround is to generate the constructor.yaml from a jinja2 template where I can generate the remap with file URL using that conda.common.url.path_to_url and environment variable CONDA_BLD_PATH.

But I think it's common to include a local package that contains scripts used during installation, and remap that to a channel in the repository, so supporting the local meta-channel would be useful to other mini-installer writers.

Also, I discovered that since constructor 3.1, if the file URL is not exactly correct, some recent refactoring means that it causes a KeyError on this line:
  preconda.py
  write_index_cache
  del repodatas['%s/%s'] % (src, subdir)]

Before 3.1, the incorrect URL meant some of my platforms didn't perform remapping, so this KeyError was useful to discover the file URL issues! However, I believe that this KeyError should be caught and reported as a warning to say that no packages using src were remapped.

**Comment by mcg1969** [comment]
Isn't this a straight duplicate of #269?

**Comment by mcg1969** [comment]
Ah, no, it's not, nevermind!

**Comment by benpapworth** [comment]
Using the jinja2 templating support - https://github.com/conda/constructor/pull/413 - I would suggest making the required functions available in the jinja2 templating:

Add something like this to constructor/jinja.py:
`from conda.common.url import path_to_url`
`env.globals['conda_path_to_url'] = path_to_url`

construct.yaml could then use this in remap to generate the correct file URL:
`{{ conda_path_to_url( 'C:\\foo\\bar' ) }}`

If the conda.base.context Context object was similarly exposed, perhaps context.local_build_root as the path would facilitate inserting the local package path into the remap?
`{{ conda_path_to_url( context.local_build_root ) }}`

This might help to address the issues in #269
