### ISSUE TITLE
Update CHANGELOG for v3.2.0

### ISSUE THREAD

**Issue by FaustinCarter** [conda/constructor#418]
@mcg1969 @isuruf @hmaarrfk @gabrielcnr 
The changelog needs updating, so I've atted all the folks who contributed since 3.1.0. I pasted the template here and figure we can use this issue to edit it together. I've included the fixes/features I was responsible for already. If you can't edit this issue, just copy/paste the template to the next comment to add your updates.

**Edit 1/4/2021:** I went through the comments and added them into this template so it is now up-to-date. Any NSIS  or PKG items?

2020-11-14   3.2.0:
-------------------
  * COMMON:
    - `construct.yaml` file now reads environment variables during the Jinja2 parsing stage. Env vars can be included like: `{{ environ["ENV_VAR"] }}` (#413).
    - Fixed bug where constructor crashed if a listed spec was in a noarch-only channel (i.e. without a subdir for the specific platform) (#409).
    - Avoid adding newly installed environment to the list of global conda environments if conda isn't included in the installer itself. (#372)

  * SHELL:
    - The user-shell initialisation phase of the installer is no longer included in the install script if there is no conda available in the installed environment.
    - The "test" option is only available if conda is installed in the environment. Previously this would fail in this situation.

  * NSIS:
    - ?

  * PKG:
    - ?

**Comment by hmaarrfk** [comment]
* Avoid adding newly installed environment to the list of global conda environments if conda isn't included in the installer itself. (https://github.com/conda/constructor/pull/372)

**Comment by mcg1969** [comment]
Agreed. @pelson @ericpre perhaps we can collaborate inside this issue to assemble a good changelog for 3.2.0 and 3.2.1.

**Comment by pelson** [comment]
I assume SHELL is linux?

```
SHELL:

 * The user-shell initialisation phase of the installer is no longer included in the install script if there is no conda available in the installed environment.
 * The "test" option is only available if conda is installed in the environment. Previously this would fail in this situation.

```

**Comment by ericpre** [comment]
## UNRELEASED 3.2.1:
NSIS:
- change the default prefix for domain user to `%LOCALAPPDATA%` and the option `default_prefix_domain_user` to set its default value
- Fix default installation folder all users and add option `default_prefix_all_users` to set its default value
- Partial fix for removing menu shortcut of other distribution when uninstalling

**Comment by FaustinCarter** [comment]
@mcg1969 It's been about 5 months since a release, so I went through all the accepted PRs and assembled the following list for 3.2.1, based off @ericpre's starting suggestions above. If folks are happy with this, reply below and I'll open a PR for the changelog updates, and then maybe we can get 3.2.1 out the door? I'm not sure what the release schedule is here, but I'm happy to help in any way I can (since I'd like to get some of these fixes rolled out!).

I made some assumptions about where to stick some of these bullet points, so feedback is welcome.

# UNRELEASED 3.2.1:

### Common:
- Fixed bug in platform selector regex parsing that was incompatible with using jinja-templated env vars and platform selectors on the same line #428
- New option in construct.yaml (`batch_mode`) to make passing the `-b` flag the default option #440
- New option in construct.yaml (`check_path_spaces`) to suppress the "Destination Folder contains spaces" warning on Windows #431 
- Duplicate package files found at environment creation during build on Windows now raises a warning rather than crashing #435

### Shell:
- aarch64 installer now properly checks if system is aarch64 #441

### PKG:
- Initialize all shells post-install on OSX #444

### NSIS:
- change the default prefix for domain user to %LOCALAPPDATA% and the option default_prefix_domain_user to set its default value #415
- Fix default installation folder all users and add option default_prefix_all_users to set its default value #419
- Partial fix for removing menu shortcut of other distributions when uninstalling #420
- Fix a typo in informational message #424
- Support for custom `nsis_templates` through the `nsis_template` variable. #423

**Comment by mcg1969** [comment]
I fully support a new release, and can fast-track it

**Comment by mcg1969** [comment]
@FaustinCarter just making sure you see this... I know _I_ am the one that tends to be delayed here but I'm keen to hit an approve button here :-) So when you can get to it, do let me know, and cc: me on the PR.
