### ISSUE TITLE
default_prefix is not working for pkg

### ISSUE THREAD

**Issue by xmnlab** [conda/constructor#432]
Hi everyone!

'default_prefix' is not working for "pkg" package for me. Is it a known problem? thanks

**Comment by hoechenberger** [comment]
I'm experiencing the same issue.

**Comment by jaimergp** [comment]
#469 partially solves this issue, but PKGs don't have that much flexibility for install locations...

**Comment by xmnlab** [comment]
thanks for the update @jaimergp !
