### ISSUE TITLE
Pkg post-install is not working in the same way that sh post-install

### ISSUE THREAD

**Issue by xmnlab** [conda/constructor#438]
hi everyone!

We are constructing a package for pkg and sh that use a post-install script https://github.com/Quansight/omnisci-datascience-installer/blob/master/constructor/post-install.sh

sh recipe https://github.com/Quansight/omnisci-datascience-installer/blob/master/constructor/sh/construct.yaml
pkg recipe https://github.com/Quansight/omnisci-datascience-installer/blob/master/constructor/pkg/construct.yaml 

and for some reason we had some problems with just pkg:
  - pkg post-install doesn't recognize PREFIX, so we needed to force manually PREFIX and PATH
  - for some reason some libs are not working properly with pkg that works fine with sh

is there any recommendation or guide for pkg?

**Comment by jaimergp** [comment]
I think you need to try something like this:

https://github.com/conda/constructor/blob/7a6cf1d65035c41d5c8f4bb519a5eb8cff8ff9e4/constructor/osx/post_extract.sh#L7-L9

**Comment by xmnlab** [comment]
got it, thanks @jaimergp !
