### ISSUE TITLE
redirect post-install, pre-uninstall script output to a logging file

### ISSUE THREAD

**Issue by bkreider** [conda/constructor#446]
redirect post-install, pre-uninstall script output to a logging file

The windows text area that has output is too small to show all of the command output.  Catching all of the output at once would be nice.

**Comment by jaimergp** [comment]
You can "select all", and copy to a text editor, I think?

**Comment by bkreider** [comment]
I can't remember, but I think the scrollback buffer is limited, so I don't think "select all" would get everything.
