### ISSUE TITLE
Pre-install script implementation on all platforms

### ISSUE THREAD

**Issue by scottwsides** [conda/constructor#451]
I know that this has been mentioned before, but it looks like those tickets havent been followed up in sometime. Are there any plans to have a pre-install script for linux/Mac/windows? This would be wildly helpful for making real installers. 

In lieu of that... how can I get constructor to check things on a users platform BEFORE conda env installation?

**Comment by ericpre** [comment]
Is it not already answered in https://github.com/conda/constructor/issues/56?

**Comment by scottwsides** [comment]
Yes... its answered... I just didnt like the answer ;-) I wanted to know if
its going to be made to actually work in the near future.
*Dr. Scott W Sides*
(303) 718-7028

**Comment by ericpre** [comment]
@mcg1969's comment in https://github.com/conda/constructor/issues/56#issuecomment-699559345 clealy says that if someone comes up with a PR, it will be considered.

**Comment by mcg1969** [comment]
Thanks, Eric. Scott, I'm sorry your definition of a "real installer" is not congruent with ours. No doubt constructor has room for improvement but it is serving its purpose well for a lot of us. I reiterate what I said in the other issue about welcoming a PR, and will close this a duplicate.

**Comment by scottwsides** [comment]
That wasn't an insult on constructor. I like it very much... it would just be great if all the features available for windows worked cross platform. And I saw about the PR... again, I just wondered whether anyone here was thinking about doing that (I don't have time or expertise) Thanks!

**Comment by mcg1969** [comment]
Gotcha. Tone is hard to gauge over text and I misread. Sorry about that. Honestly Windows is the weakest platform here. We need a real champion for it.
