### ISSUE TITLE
Option to Disable Creation of Start Menu Items (Icons) on Windows

### ISSUE THREAD

**Issue by RoyiAvital** [conda/constructor#452]
I'm installing Mini Conda on Windows in order to satisfy other applications needs.  
Namely I don't want it to be installed globally. It means I a m after a portable installation of it on Windows.

I use the following flags: `/S --no-shortcuts /NoRegistry=1 /AddToPath=0 /RegisterPython=0 /D=$INSTALL_PATH`.
I assume the flags, specifically --no-shortcuts` will prevent the installaer from adding items and icons to the Windows 10 start menu.
Yet it still does.
Is there a way to install Mini Conda with no global effects? No registry, no icons, no change of Path, etc...

Related to issue https://github.com/conda/conda/issues/10585.

**Comment by ericpre** [comment]
Fixed in https://github.com/conda/constructor/pull/455.

**Comment by RoyiAvital** [comment]
@ericpre , Thank You!
It would be great to be able to have a complete portable mode of `conda`.

**Comment by ericpre** [comment]
If with "portable", you mean that you change the location of the distribution after it has been installed, then I suspect this is not an easy task. Other people will know better than me, but I would expect that there are a number of path used by conda which are not relative to the root directory of the installation folder and therefore changing the location of the distribution would break the distribution itself.

**Comment by RoyiAvital** [comment]
So far it seems the only issue is that there is no way to make it keep all settings files in the installation folder or any given path for that matter. It just use `%USERPROFILE%` or something like that.

IT would be great to have an option to control those.

**Comment by ericpre** [comment]
To clarify this issue and its status:
- there is no `--no-shortcuts` option to the installer: using `--no-shortcuts` as mentioned by @RoyiAvital above does nothing with respect the windows start menu shortcuts. #455 only fixes a related issue which consists in create windows shortcut as defined in https://github.com/conda/constructor/blob/master/CONSTRUCT.md#menu_packages
- @RoyiAvital, I suspect that your use of "portable" is misleading: in my understanding portable means that you can move the distribution around, run it from external drive, etc. Please clarify.
- the flags `/NoRegistry=1 /AddToPath=0 /RegisterPython=0` should be working as expected. If not, it would be good report separetely

> So far it seems the only issue is that there is no way to make it keep all settings files in the installation folder or any given path for that matter. It just use `%USERPROFILE%` or something like that.

Can you specify which settings are you referring to? Many python libraries are going to create their own settings and create files in different place and I am wondering what is the relevance for `conda` and `constructor`.

**Comment by RoyiAvital** [comment]
Yea, I totally agree. 
I opened this issue only for the option to work properly: Prevent from the installer creating shortcuts.
Though I didn't get if this fix just removes them after creation or completely skips this step.

Portable, in my book, means configuration is done by files and the location of the files can be set by user. For instance, it could be set to be in the same folder as the installation.

On my system, though I use the flags: `/NoRegistry=1 /AddToPath=0 /RegisterPython=0` when I use Conda I get `.conda` on my user folder. I wish there was a way to set the location of it manually.
