### ISSUE TITLE
Release 3.2.2

### ISSUE THREAD

**Issue by jakirkham** [conda/constructor#460]
Would it be possible to create a new `constructor` release? This would be useful for `conda-standalone` ( https://github.com/conda-forge/conda-standalone-feedstock/pull/18 )

cc @ericpre

**Comment by jakirkham** [comment]
cc @jezdez (since you had mentioned `conda-standalone` at the Conda community meeting recently)

**Comment by jakirkham** [comment]
cc @chenghlee

**Comment by jaimergp** [comment]
Can we add the PKG branding one to the list too? 

* #469

**Comment by mcg1969** [comment]
We've tagged 3.2.2. We did not get everything in that is listed here, unfortunately
