### ISSUE TITLE
[Windows] Let silent mode installer exit with errorlevel 1 when destination path contains spaces

### ISSUE THREAD

**Issue by a-cesari** [conda/constructor#463]
Dear all, 
I noticed that if installing Anaconda on Windows via the GUI gives me a waring if trying to install on a path with spaces. 
However if I try to do the same with the silent install method the installation goes on without giving any error. 
As in our script we would like to stop if trying to install anaconda in a path with spaces, is there the possibility to implement this in the constructor? i.e. let the installation exit with %errorlevel% = 1 when spaces are detected?
Or, which is also ok for me, could you point to me which file should I modify to implement this change in my fork?

Thanks a lot,
Andrea

**Comment by jaimergp** [comment]
Hi @a-cesari!

The logic for Windows mainly consists of [this NSIS script](https://github.com/conda/constructor/blob/main/constructor/nsis/main.nsi.tmpl). Check the usage of the `CheckForSpaces` in different sections and make sure it's called when the installer is also run in silent mode.
