### ISSUE TITLE
Most of your examples have maxiconda README

### ISSUE THREAD

**Issue by DOH-Manada** [conda/constructor#470]
The various README files in the examples directory need to be updated to reflect the actual content they are referencing, not just copy/paste the maxiconda example.

**Comment by jezdez** [comment]
Would you mind elaborating what you mean by that?

**Comment by kenodegard** [comment]
@jezdez looks like the various README examples are copies of the maxiconda example, see https://github.com/conda/constructor/search?q=maxiconda

**Comment by jezdez** [comment]
> @jezdez looks like the various README examples are copies of the maxiconda example, see https://github.com/conda/constructor/search?q=maxiconda

Gotcha, thank you, I updated the issue description accordingly.
