### ISSUE TITLE
Cut new release so constructor works with pyyaml >= 6

### ISSUE THREAD

**Issue by FaustinCarter** [conda/constructor#476]
Constructor 3.2.1 is limited to environments where pyyaml is pinned to be less than version 6. There is a fix in the source code (master branch) to allow constructor to work on pyyaml versions >= 6. This is issue is a request for a new release (3.2.2) so that constructor no longer fails with a `TypeError` when paired with the most recent version on pyyaml.

**Comment by mcg1969** [comment]
@FaustinCarter I'm game to facilitate this—do you think  I can trouble you to do a changelog/authorship PR?

**Comment by mcg1969** [comment]
I'm going to go through the PRs and review and merge any quick fixes

**Comment by FaustinCarter** [comment]
> @FaustinCarter I'm game to facilitate this—do you think I can trouble you to do a changelog/authorship PR?

This is ready to go (unless you merge in any new PRs) in #478. Hit me up if you do merge any new PRs and need me to run another update.

**Comment by mcg1969** [comment]
Thank you! I don't think I intend to merge anymore, including mine. I should get to this tomorrow

**Comment by FaustinCarter** [comment]
By the way, are there some notes anywhere on the release process? I'd be happy to help with future releases if there is a checklist somewhere to follow. I use constructor pretty heavily at my day job, so I'm motivated to help keep it current.

**Comment by mcg1969** [comment]
I know the conda ecosystem team overall is trying to drive towards a more community-driven approach. But I suspect constructor is a bit further down the list of priorities... Indeed, I myself have been away for awhile, and hopped on because the holiday afforded an opportunity! @jezdez might have a better sense of where we are in managing this one better.

**Comment by mcg1969** [comment]
3.2.2 is tagged

**Comment by FaustinCarter** [comment]
> 3.2.2 is tagged

It looks like it got tagged as 3.3.2. Is that going to cause any issues other than the mismatch with the changelog file? If it won't cause problems, I can open a PR to change the number in the changelog file.

**Comment by mcg1969** [comment]
No, I'll fix the tag

**Comment by mcg1969** [comment]
I've also added a comment to the conda-forge 3.3.2 PR so hopefully it won't get built
