### ISSUE TITLE
install() got an unexpected keyword argument 'root_prefix'

### ISSUE THREAD

**Issue by alessioarena** [conda/constructor#480]
I'm trying to build my first distribution using conda constructor, but I'm having issues adding the menu items of a package I developed.

When installing I get the following error
![image](https://user-images.githubusercontent.com/33886395/148324179-8515cfad-1f7b-4f05-87ef-12fe8d02b375.png)

I tried to debug it but I am failing to understand where to look at.
It seems that line 130 in `_nsis.py` is calling `menuinst.install`. I then checked the installed version of `menuinst` as part of the deployment, and this is the last version available (1.4.18) and the `install` function indeed has a root_prefix keyword.

I also checked every other conda environment I have installed in my development machine and they all have the latest `menuinst` version.

So, then the questions are:

- How should I exactly reproduce that menu creation step after the installation?
- Is constructor somehow using an embedded version of `menuinst`? Is this out of date?

**Comment by alessioarena** [comment]
Digging around it looks like `conda constructor` is creating a temporary environment to perform the installation, and this uses menuinst 1.4.17 (hence the issue). 
How can you control the specifications for this environment?

**Comment by ericpre** [comment]
This is most likely because a new build of conda-standalone is required - WIP in https://github.com/conda-forge/conda-standalone-feedstock/pull/26.
In the mean time, you have two possible workarounds:
- use constructor 3.2.1
- disable creating start menu during installation and install the menu after the distribution is installed.

**Comment by alessioarena** [comment]
Thanks for this. I downgraded to version 3.2.1 and it worked.

I was keen to tackle option 2, but I found the documentation being insufficient for `post_install` scripts.
For example, are there any available variables to use?

**Comment by jaimergp** [comment]
@alessioarena - the current docs include more info! :) Closing this for now.
