### ISSUE TITLE
Uninstall information in HKCU when running silent installer as admin

### ISSUE THREAD

**Issue by wulmer** [conda/constructor#49]
Hi, I tried running an installer (created by constructor) with the `/S` option from an admin console. While the installation went well, I noticed that the uninstaller registry entry is located under `HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall`. 

When I run the installer without `/S`, the uninstall information is written under `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`.

In my opinion, the location of the uninstaller entry should not change depending on the mode, so I consider this a bug.
I have checked the NSI source code and I think it has to do with the automatic detection of the install mode. While `$InstMode` might be correctly guessed as `${ALL_USERS}` (didn't verify this), the uninstaller entry is written to `WriteRegStr SHCTX "${UNINSTREG}" ...`. I am guessing that using `SHCTX` here might not always reflect the choice taken by the automatic `$InstMode` guessing mechanism.

**Comment by wulmer** [comment]
I have pinned down the problem to the `InstModeChanged` function in `main.nsi.tmpl`. In non-silent mode, the shell var context is set in [line 235](https://github.com/conda/constructor/blob/master/constructor/nsis/main.nsi.tmpl#L235) to the correct installation mode, but in silent mode, the call to `SetShellVarContext` never happens.

I think the ` ${IfNot} ${Silent}` block which is meant for protecting the `/D` command line option should not include the calls to `SetShellVarContext` as they don't have to be protected in silent mode.

I will prepare a PR for this change.

**Comment by speleo3** [comment]
@wulmer can this be closed? #60 is merged

**Comment by wulmer** [comment]
Sorry, yes, of course. Have been away for a few days...
