### ISSUE TITLE
prepend path in .bashrc file

### ISSUE THREAD

**Issue by hans-permana** [conda/constructor#51]
Hi all,

At the end of an installation (in Linux), the installer asks whether to prepend the install location to the PATH in the .bashrc file. For an update (with -u), and if the user always selects 'yes', multiple entry will be added to the .bashrc file. Will it be possible to ignore this when it is an update? Or better, will it be possible to add a little script to find out whether the same path has previously been added to .bashrc. If it has, do nothing.

Thanks,
Hans

**Comment by mcg1969** [comment]
Constructor 3.0 uses `conda init` now, which is a bit more intelligent about these things.
