### ISSUE TITLE
channel priority for constructor

### ISSUE THREAD

**Issue by csoja** [conda/constructor#54]
Feature request to add channel priority for constructor

**Comment by joelhullcio** [comment]
Can we get this feature officially added to Constructor soon?  It would be very helpful.

**Comment by darkdreamingdan** [comment]
Can someone explain this bug in a bit more detail?  If I add a list of channels into constructor, and a list of specs, how are channels currently prioritised? Randomly?

**Comment by jjhelmus** [comment]
Currently all channels listed in the `construct.yaml` file are given equal priority.  The solver examines all of the packages in all channels with no preference for the source.  Note that the solver used comes from `libconda` not `conda` and may give different results that those produced from the equivalent `conda create --no-channel-priority` command.

I also believe there may be an issue with the current behavior where packages with identical names coming from different channels may clobber each other when constructor creates an index of all available packages.

**Comment by jakirkham** [comment]
Is there any reason to not just use `conda` during construction?

**Comment by jjhelmus** [comment]
> Is there any reason to not just use conda during construction?

conda (the python package) is only accessible from the root environment.  If constructor used `conda` to solve the package spec, then constructor would need to be installed in the root environment.  Using `libconda` allowed constructor to be installed in any environment.

**Comment by jakirkham** [comment]
Sure. Am just concerned that using such an old version of `conda` in the form of `libconda` is incurring some significant penalties. Plus its concerning that two different packages are trying to be solvers. Are there any thoughts or plans as to how to mitigate these two issues?

**Comment by jjhelmus** [comment]
> Are there any thoughts or plans as to how to mitigate these two issues?

Yes, see #79

**Comment by mingwandroid** [comment]
New constructors are ready and version 2 has been made, thanks @nehaljwani 

Apart from needing to install constructor in your root env there are no other downsides AFAICT and if that's something you do not want then you can always remove it afterwards.

**Comment by mingwandroid** [comment]
My opinion on libconda is that it's fine for it to make a comeback, but if it does then `conda` needs to depend upon it, cc @kalefranz.

**Comment by hajapy** [comment]
I am not sure why this issue was closed as it seems constructor does not respect channel priority the same way conda does yet. https://github.com/conda/constructor/pull/79 is still open and in my opinion is greatly needed!
