### ISSUE TITLE
Make metadata env vars available to Windows post-install scripts

### ISSUE THREAD

**Issue by FaustinCarter** [conda/constructor#556]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Constructor allows a post-install script to be run after installation. On Linux systems and MacOS shell installers, the `header.sh` script manages the calling of the post-install script and exports the following additional env vars that are available to the post-install script:

https://github.com/conda/constructor/blob/a16696aa79db71fde01756cb5e03ac9c60678428/constructor/header.sh#L21-L23

It would be very useful to make this metadata available for the Windows and MacOS pkg installers as well.

For Windows the variables can be set via `Kernel32::SetEnvironmentVariable` in the NSIS template and they will be available for the post-install script.

### Why is this needed?

I'd like to have a way for users (and sysadmins!) to quickly know which version of the installer they used. One easy way is to write the version information to a text file in `$PREFIX` during post-install. Maybe there are other cool ways to get this info, but the only place I've found on Windows where the installer version exists is in a registry key that points back to the uninstaller. In order for this to be possible, some metadata needs to be available in the post-install script environment.

**Comment by jaimergp** [comment]
Working on this in #558, Windows and PKG included.
