### ISSUE TITLE
Feature request: implement pre_install scripts on Windows

### ISSUE THREAD

**Issue by goanpeca** [conda/constructor#56]
Hi @ilanschnell 

I am making a check for windows users installing Anaconda Fusion via constructor installer and I was using but it seems this can't be done :-| (yet?)

```
Checking for 'C:\Users\builder\Anaconda3\NSIS\makensis.exe'
NSIS version: v3.0
Error: Cannot run pre install on Windows, sorry
```

**Comment by ilanschnell** [comment]
There is no way to run a pre-install on Windows (and there probably never will be), however post-install is supported on Windows.  The problem with pre-install is that (at least part of the installation) has to be done so the pre-install script can be run.  While this is easy on Unix, this is much more complicated on Windows.

What do you require the pre-install script for?  Could it be done using a post-install script?

**Comment by goanpeca** [comment]
I want to avoid installing Anaconda Fusion if conda is already installed (Either by an existing anaconda or miniconda installation)

**Comment by mcg1969** [comment]
Given the architectural reasons why we can't do this, I'm going to close as a wontfix. If someone comes with a PR that somehow makes this work, I'm open to it.
