### ISSUE TITLE
Add More Information Upon Installation re: Terminal Prompt Displaying `(base)`

### ISSUE THREAD

**Issue by beeankha** [conda/constructor#562]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

[extracted from [conda issue # 10928](https://github.com/conda/conda/issues/10928)]

While we do not want to _default_ to not showing the `(base)` env name displayed on the terminal prompt (which is what the issue linked above is requesting) as this is expected behavior, it would be ideal to add a more detailed message upon `conda` or `miniconda` installation saying that this will happen, as well as also possibly update the documentation.

### Why is this needed?

It would provide more information upon installation and would explain why the terminal prompt has changed.

**Comment by jaimergp** [comment]
I guess we are talking about this block:

https://github.com/conda/constructor/blob/de1ce16c62ff4d748e2d4a8046e923d3136e14db/constructor/header.sh#L577-L625

It should also say something about the initialization on batch mode, if it applies.

We also have `conclusion_text` now, which would allow installer providers to specify their own text, but I agree this is too tied to `conda` to depend on just plain text messages which are not aware of the context or options used.
