### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by hmaarrfk** [conda/constructor#577]
Shall we make a new release? The news section is somewhat getting full and we are hitting some caching issues at conda-forge when trying to create our Miniforge and Mambaforge installers. I presume others are seeing the same.

Thank you for considering!

**Comment by jaimergp** [comment]
Yes, I'd like to cut a new release!

Given the amount of changes, I am inclined to go through a RC cycle though. What do you think?

**Comment by jaimergp** [comment]
We can probably wait for the next `conda` (22.11), which will have the necessary [changes](https://github.com/conda/conda/pull/12043) to finally merge #449.

**Comment by jaimergp** [comment]
Oh, and we need this merged https://github.com/conda-forge/nsis-feedstock/pull/20 for the uninstaller signing stuff!

**Comment by jaimergp** [comment]
And we should probably look into #576

**Comment by dbast** [comment]
rc releases have the drawback that they often won't see enough testing, so they are then not really useful to get feedback.

The interested people can already use the latest code from main via `conda install ctools/label/dev::constructor` without a  special rc release (we currently do that internally within anaconda for testing).

Can we do like a real 3.4.0 release now followed by some small 3.4.1, 3.4.2, ... releases? There is always some new PR to wait forever, but those can go into the small releases.

People running into issues can still use an older releases version like the current 3.3.1., which is one of the biggest advantages of versioned releases: being able to use old/new/specific versions at any time.

**Comment by jaimergp** [comment]
Hello readers, if you are watching this issue, please know that we are probably cutting a new release (`3.4.0`) this week, as soon as tomorrow if everything goes well.

The list of changes is [_quite something_](https://github.com/conda/constructor/tree/main/news), so please take a look in case you have any comments!

**Comment by FaustinCarter** [comment]
@jaimergp Any reason not to bump this to 4?

**Comment by jaimergp** [comment]
> @jaimergp Any reason not to bump this to 4?

The "API" (e.g. the config file) is mostly the same. We have added features in a backwards compatible way, afaik. I would expect v4 for a totally different input file, for example.
