### ISSUE TITLE
_conda.exe hardcoded into nsis template

### ISSUE THREAD

**Issue by FaustinCarter** [conda/constructor#586]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

It's not clear to me if this is a bug report or a feature request, but best as I can tell, when using constructor on Windows and providing an alternative conda-standalone executable, if the exe is not named `_conda.exe` then it won't get found. The NSIS template does add the custom exe to `$INSTDIR` here: https://github.com/conda/constructor/blob/fd028c8bf10981de32ea4775eadb9863897c536d/constructor/nsis/main.nsi.tmpl#L969, but it then goes on to call `$INSTDIR\_conda.exe` throughout the remainder of the template. This should either be well documented, or else the name of the executable should be set to the name of the exe passed in at build time using the `--conda-exe` flag.

(I also will admit that I might be totally wrong about this, and somewhere whatever exe is getting passed in is getting renamed to `_conda.exe`, but I couldn't find that anywhere!)

**Comment by jaimergp** [comment]
The NSIS preparation scripts will rename the executable to `_conda.exe` so it's not a problem ([see this line](https://github.com/conda/constructor/blob/fd028c8bf10981de32ea4775eadb9863897c536d/constructor/winexe.py#L333)), but I agree it's a bit misleading to have that mechanism.

**Comment by FaustinCarter** [comment]
Oh man, thanks! That's what I get for not carefully reading everything.
