### ISSUE TITLE
Missing files in NSIS 3.01 (with constructor 1.5.2)

### ISSUE THREAD

**Issue by wulmer** [conda/constructor#59]
When I try to build a constructor package, a few NSIS plugin DLLs are missing:

    Plugin not found, cannot call UAC::_

When I copy the `UAC.dll` from `NSIS/Plugins/x86-unicode/` to `NSIS/Plugins/x86-ansi/`, the next error message appears:

    Plugin not found, cannot call untgz::extract

So I copied the `untgz.dll` and then the installer build worked. But it seems the DLLs are not compatible and when I execute the installer, it fails extracting the zip files.

Is it possible to provide a new `nsis` package with all the necessary plugins?

**Comment by wulmer** [comment]
I downloaded some (older) DLLs from the NSIS website and put them in the right place and it (somehow) worked. Not sure if I have the right plugin DLL versions.
I would appreciate if the `nsis` package would come with the necessary DLLs (in the right versions) included.

**Comment by waterbug** [comment]
I have been bitten by this bug as well!

**Comment by msarahan** [comment]
We moved our installers to be unicode installers.  We stopped including ASCII plugins accordingly, as we are no longer using them.  

There's two ways to "fix" this:

* We can put the ASCII plugins back (but I don't think we'll commit to supporting them)
* You can change your installer to be unicode.

The code for that is:

``Unicode "true"``

up at the top of your .nsi input file.

I think the latter is the preferable long-term solution, but I'm open to feedback.

**Comment by wulmer** [comment]
Thanks @msarahan for this info. I would like to use the Unicode mode then.
But isn't the `.nsi` input file auto-generated by `constructor` (based on `main.nsi.tmpl`) ?
I haven't found a hint on how to activate the Unicode mode. Do I have to manually edit site-package's `main.nsi.tmpl`  or is there a switch in `constructor` to activate Unicode mode?

**Comment by msarahan** [comment]
Great point. Sorry, this needs a small PR to constructor to add that. For now, hacking the site-packages tmpl file should get you up and running at least.

**Comment by wulmer** [comment]
Do you already have an idea how this PR should be implemented? Perhaps I could help...

**Comment by msarahan** [comment]
I believe this should be sufficient: https://github.com/conda/constructor/pull/61

Do you mind testing that PR?

**Comment by waterbug** [comment]
On 01/31/2017 08:08 AM, Mike Sarahan wrote:
> I believe this should be sufficient: #61
> <https://github.com/conda/constructor/pull/61>
>
> Do you mind testing that PR?

I'll try it today.

**Comment by wulmer** [comment]
Thanks for fixing this so quickly. I'll wait for the next constructor release to test these new features.

**Comment by ilanschnell** [comment]
Constructor 1.5.3 was released today, with the fix.  Thanks to @msarahan!
