### ISSUE TITLE
.sh installers do not work with sh

### ISSUE THREAD

**Issue by dbast** [conda/constructor#596]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

.sh installers created from current constructor:main branch have `#!/bin/sh` as shebang, but actually fail when called via `sh installer.sh` or `./installer.sh` with
  ```
  #16 13.80 ./miniconda.sh: 444: [[: not found
  #16 14.81 
  #16 14.81 CondaFileIOError: '/opt/conda/pkgs/envs/*/env.txt'. [Errno 2] No such file or directory: '/opt/conda/pkgs/envs/*/env.txt'
  ```

though, `bash installer.sh` … shellcheck tells:
  ```
  In Miniconda3-py310_22.11.1-1-Linux-aarch64.sh line 444:
      if [[ -f "${env_pkgs}channels.txt" ]]; then
         ^-- SC3010 (warning): In POSIX sh, [[ ]] is undefined.
  ```
(shellcheck also has lots of more warnings) … we should add some tests that lints the embedded installer code via shellcheck / checks for bashisms.

**Comment by jaimergp** [comment]
The [installation instructions always mentioned `bash`](https://conda.io/projects/conda/en/stable/user-guide/install/linux.html) so I wasn't aware we offering any POSIX guarantees. That said, if we can do the same with POSIX compat without making it super cumbersome, then I'd be ok with such a PR. 

+1 on the linters. Not just shell, but also Python. The whole project needs some consistency in style, docstrings and whatnot... I didn't do it during all the previous work to minimise diffs, but once we are done with shipping features, we should start work on this.

**Comment by jaimergp** [comment]
Oh, and I noticed recently the scripts do not use `set -eu` so we might be ignoring some errors.

**Comment by dbast** [comment]
We can also change the shebang to `#!/bin/bash`, if doing all the logic via POSIX sh compatibility turns out to be too cumbersome.

Agreed to linting and `set -eu`. Several projects in the conda org have a nice `.pre-commit-config.yaml` + workflow that can be used without much work. Though the .sh header template has be rendered first before applying some linting (so pre-commit does not help here), thats why a test that renders+lints is maybe easier to handle.
