### ISSUE TITLE
Version numbers for Windows must be in X.X.X.X format for NSIS

### ISSUE THREAD

**Issue by bheklilr** [conda/constructor#6]
When trying out constructor today I stumbled across an undocumented behavior with version numbers on Windows platforms.  The NSIS system expects the version number to be in the format X.X.X.X, so version numbers given in the `construct.yaml` file must also be in that format.

I would be happy with a warning from constructor that NSIS is going to reject the version number, or if a semantic version number has already be specified in the `construct.yaml` file for `.0` to be appended to the version number string until it's in the appropriate format.

It would also be nice if the version field was automatically interpreted as a string rather than an int or a float, although this is simple and fast to fix after seeing the error message.

**Comment by bheklilr** [comment]
I just saw that there is a [closed issue](https://github.com/conda/constructor/issues/3) for the version number being interpreted as a string, sorry about the redundant comment.

**Comment by bheklilr** [comment]
Some more information that I've found [here](http://nsis.sourceforge.net/Docs/Chapter4.html#versioninfo).  The function `VIProductVersion` requires the format `X.X.X.X` where each number fits in 16 bits since it's setting a [`DWORD` field in the `FIXEDFILEINFO` part of the version resource](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646997%28v=vs.85%29.aspx).  There is the `VIAddVersionKey` which can be used as `VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductVersion" "version_string"` that accepts any string so far as I can tell.

Would it be better to set the `ProductVersion` using `VIAddVersionKey` instead?  This may not provide all of the functionality gained by `VIProductVersion`, I don't know enough about NSIS and Windows binaries to tell.  At the very least an error could be thrown when the `construct.yaml` file is parsed if the version number can't be automatically converted into four 16 bit numbers padded with 0s, that way the user of constructor would have more information about why their build isn't working.

**Comment by ilanschnell** [comment]
This should be fixed in 1.3.0, which came out today.

**Comment by bheklilr** [comment]
Looks like it's actually working with constructor 1.2.1.  I currently can't get constructor 1.3.0 or 1.3.1 working for some reason, and since it's Friday night I'm not going to work on it right now.  The error I keep getting when simply running `constructor --version` is

```
Traceback (most recent call last):
  File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\Scripts\constructor-script.py", line 3, in <module>
    from constructor.main import main
  File "C:\Users\bheklilr\AppData\Local\Continuum\Miniconda3\lib\site-packages\constructor\main.py", line 13, in <module>
    from libconda.config import subdir as cc_platform
ImportError: No module named 'libconda'
```

I noticed that 1.2.1 required conda 4.1, but

    > conda --version
    conda 4.1.6

I was able to test it using constructor 1.2.1 and it correctly appends `.0`s until the version string is in the correct format, so at least this particular error is fixed.  From my messing around with 1.3.1 I think I'm going to end up opening a couple issues within the next week since I've noticed a few other issues outside of the scope of this thread.

---

For confirming that it does work with 1.2.1 I built using the `construct.yaml`

```yaml
name: test_constructor_fix
version: 1.2.3

channels:
  - http://repo.continuum.io/pkgs/free

specs:
  - python 2.7*
```

and then checked under the details tab of the properties of the generated executable.  The file version showed up as "1.2.3.0", so it looks like this particular issue is fixed.  Thanks!

**Comment by ilanschnell** [comment]
Constructor 1.3.0 depends on `libconda` (https://github.com/ilanschnell/libconda), which is also available on the default conda repository (`repo.continuum.io`) now, so you can `conda install libconda`.  The conda package for `constructor 1.3.0` lists `libconda` as a dependency.

**Comment by bheklilr** [comment]
Gotcha, I had tested from source and not via `conda install`.  Got the dependencies worked out and 1.3.1 also works just fine.
