### ISSUE TITLE
Post-install fails to execute correctly

### ISSUE THREAD

**Issue by H0R5E** [conda/constructor#63]
Hi, I have distributed a software for Windows using Constructor which has a post-install.bat script. The script is used to write a registry key which other installers can inspect to find the chosen installation path.

On some systems (none I have access to) it seems like the script is not being run or is not running correctly and the registry key is not being written (rather than being written incorrectly). I have attached the script in question (renamed to *.txt).

[post_install.txt](https://github.com/conda/constructor/files/775082/post_install.txt)

I was wondering if there is any logging that can be viewed to see the result of running the script? My only other ideas were that there was some permissions or anti-virus blocking occurring.

I have the corresponding issue here: DTOcean/dtocean-issues#3

Many thanks,

Mat

**Comment by kawing-chiu** [comment]
I am having the same issue. My `post-link.bat` script runs correctly when using `conda install`. But after packaging into a constructor package, it stops to work. And I can't find any way to debug the issue.

**Comment by mingwandroid** [comment]
@H0R5E, @kawing-chiu, you'd need to use `procmon.exe` from Microsoft to debug this, or try looking in the `Event Viewer` in the `Windows Control Panel` for any messages.

I would encourage using quotes around variables though as ones which contain spaces won't work if left unquoted.

**Comment by kawing-chiu** [comment]
@mingwandroid Thanks! Your are genius. It is indeed the path issue (containing space). I tracked down the issue by activate the contructor's env and install package inside it.

There is one thing quite strange though: Inside the contructor package's environment, one of my package is listed in the output of `conda list` as installed from `<pip>`:
```
my_package                 0.1.0dev8             <pip>
```
Why would this happen? Now I cannot use `conda uninstall my_package` to uninstall it.

**Comment by mingwandroid** [comment]
@kalefranz, any ideas about this?

**Comment by mingwandroid** [comment]
@kalefranz I believe the reporter is stating that the package is a conda package and part of their installer made by constructor, @kawing-chiu, can you confirm that (or otherwise)?

**Comment by kawing-chiu** [comment]
@mingwandroid Yes you're right. The `my_package` is a conda package built by me locally, and part of the constructor installer. If it is installed in a normal conda environment, it will shown up as
```
my_package                 0.1.0dev8             local
```

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
