### ISSUE TITLE
Non-ASCII characters in target path might affect package extraction

### ISSUE THREAD

**Issue by jaimergp** [conda/constructor#634]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

> Comes from https://conda.discourse.group/t/install-miniconda3-for-windows/169/11

Conclusions from the 1:1 investigations:

- Latest Miniconda for Windows x64 (as of today) could not get installed in a path with non-ASCII characters. In the reported issue, the Windows username is `Ángel`. 
- Installation worked better with the "All Users" option (packages were extracted and linked correctly), but it crashed BAD when the uninstaller was supposed to be written. No error dialogue or anything, just a vanished installer after a sub-second flash of a red-cross dialog. 
- If the installation happened into an ASCII compliant path, no errors were reported even in "Just Me" mode. However, this observation was only made after an accidental computer restart. 

### Conda Info

```shell
N/A
```

### Conda Config

```shell
N/A
```

### Conda list

```shell
N/A
```

### Additional Context

* The user had attempted several installations with different degrees of success, but they had all failed. This included Miniconda, Anaconda, Mambaforge (which used the current `constructor`, but also previous versions with old conda-standalones).
* An old VS Code extension ([maybe this one](https://github.com/DonJayamanne/pythonVSCode)) had apparently installed a CPython into `C:\Python` and added that to PATH. This is bad practice, but the installer should be able to run regardless. This might not be related, but it's worth investigating, because it might be another issue to fix.

I'm also attaching some of the logs collected during the investigation:

- [miniconda-justme.txt](https://github.com/conda/constructor/files/10514763/miniconda-justme.txt)
- [miniconda2.txt](https://github.com/conda/constructor/files/10514764/miniconda2.txt)
- [mambaforge.txt](https://github.com/conda/constructor/files/10514766/mambaforge.txt)

It looks like the problem comes from `conda-package-handling` and/or `libarchive`. @dholth Have you seen errors like this during your tests? Check the miniconda logs; mambaforge errors are different, probably because of the previous failed installs leaving `.condarc` files around... aka #568.

**Comment by dholth** [comment]
These errors `xz-5.2.8-h8cc25b3_0\.cph_tmpw8doj7mq\info-xz-5.2.8-h8cc25b3_0.tar.zst` would be libarchive-related (conda-package-handling 1.x series) since 2.x doesn't put the `.tar.zst`in a temporary directory.

I'm not sure where multiprocessing is used, the recent parallel-download-and-extract from 22.11 conda uses threads.

**Comment by hmaarrfk** [comment]
@celliern reported a similar issue in https://github.com/conda-forge/miniforge/issues/484
