### ISSUE TITLE
Fix bugs in interactive mode due to unbound variables

### ISSUE THREAD

**Issue by dbast** [conda/constructor#635]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

This https://github.com/conda/constructor/pull/600 enabled `set -u` which leads to unbound variables in the interactive mode of the installers, e.g. the recent released https://github.com/conda-forge/miniforge/releases/download/22.11.1-0/Miniforge3-22.11.1-0-MacOSX-arm64.sh ... This was not caught during automated testing as automated testing is done in batch mode.

Errors are like:
```
installation finished.
Do you wish the installer to initialize Miniforge3
by running conda init? [yes|no]
Miniforge3-22.11.1-0-MacOSX-arm64.sh: line 394: DEFAULT: unbound variable
```

and 

```
Please, press ENTER to continue
>>> 
Miniconda3-py39_XXXXXX.sh: line 126: $1: unbound variable
```

**Comment by hmaarrfk** [comment]
This is due to the fact that the variable `DEFAULT` can be left in an undefined state due to the new logic:
https://github.com/conda/constructor/blob/main/constructor/header.sh#L534

**Comment by dbast** [comment]
The first error gets fixed by https://github.com/conda/constructor/pull/636

The second error in above description is unrelated and seems like a broken License was embedded in the header.sh, to be investigated internally first.
