### ISSUE TITLE
Use `pydantic`-based schema validation for the input file

### ISSUE THREAD

**Issue by jaimergp** [conda/constructor#640]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Use a `pydantic` model to express, document and validate the input file schema. Right now, our logic is an incomplete implementation with ad-hoc, but partial, validation of the input. It's difficult to maintain, the default values are not clear and it adds unneeded complexity. 

I'd argue for a `menuinst`-inspired implementation of the `construct.yaml` schema, as it is being done in the [CEP-draft of `menuinst`](https://github.com/conda/menuinst/blob/cep-devel/menuinst/_schema.py).

### Why is this needed?

* Clearer intent
* Easier to maintain
* JSON schemas automatically available
* Default values are documented and enforced
* Sophisticated validation logic
* Better error messages for malformed input

### What should happen?

The `pydantic` classes replace the current `construct.py` logic in a drop-in fashion. The `info` dictionary can still be generated from the schema class, so the impact is not as dramatic as it sounds. It does add an extra dependency to `constructor`, but I think the benefit is large enough to make it an acceptable compromise.

**Comment by goanpeca** [comment]
Plus the latest pydantic is rust based (or the one coming?) so it would be fast too :)

**Comment by goanpeca** [comment]
Would love to work on this !
