### ISSUE TITLE
Convert the test suite to 100% pytest-based

### ISSUE THREAD

**Issue by jaimergp** [conda/constructor#641]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Our current test infrastructure uses some pytest logic, but the main logic happens in the `run_examples.py` script, which depends on the content of `examples/`. This is a homemade, ad-hoc script that has grown a bit too much, with many features and cases. Every time we add a new variable to check it's shoehorned in and it is not getting any better.

I suggest we use a `pytest`-only test infra, powered by fixtures and other pytest goodies. The good folks at MNE (@larsoner more specifically) did suggest something along these lines a while ago ([see comment here](https://github.com/conda/constructor/pull/525#issuecomment-1177568197) for more details and ideas).

This would allow us to test better, clearer and more efficiently. Debugging should also get easier thanks to the `-k` flag.

### Why is this needed?

* Better development experience
* Long-term maintainability
* Readability of the test infra

### What should happen?

* All the examples should be covered by a pytest case, with a docstring explaining what we are aiming for in that test.
* Post-installation checks wouldn't need the `post_install.sh` hacks, and could be done with pytest idioms. Testing with Bash makes me feel bad :D

**Comment by goanpeca** [comment]
I can also help with this! :)
