### ISSUE TITLE
The generated `pkgs/envs.txt` does not honour `info['channel_remap']`

### ISSUE THREAD

**Issue by jaimergp** [conda/constructor#654]
The generated `pkgs/envs.txt` does not honour `info['channel_remap']`, so the generated installer fails for locally built channels, by reclaiming the path of the package from the environment running constructor.

The problem seems in `preconda.py`.

Files `pkgs/urls.txt` and `pkgs/urls` are written using `get_final_url(info, url)` (within `all_final_urls_md5s` --> this honours channel_remap; but `pkgs/envs_txt` uses `info["_urls"]` directly.

You have the remap info already in `final_urls_md5s`, so the solution -hopefully- is as simple as:

Replace
```python
    # base environment file used with conda install --file
    # (list of specs/dists to install)
    write_env_txt(info, dst_dir, info["_urls"])
```
with
```python
    # base environment file used with conda install --file
    # (list of specs/dists to install)
    write_env_txt(info, dst_dir, final_urls_md5s)
```

Equal change is required for sub environment:

replace 
```python
        write_env_txt(info, env_dst_dir, env_info["_urls"])
```
with
```python
        write_env_txt(info, env_dst_dir, env_urls_md5)
```

==> generated installer than works in my cases

_Originally posted by @EisW in https://github.com/conda/constructor/issues/559#issuecomment-1443747083_

**Comment by jaimergp** [comment]
Thanks for the report @eisw. We'll track the progress here. If you have time to open a PR with a couple tests, that'd be awesome, but no pressure :D

**Comment by EisW** [comment]
In my honest opinion the PR should be finished now. 
Did I miss something?

**Comment by EisW** [comment]
Can you trigger CI, to see if it works now? Or can I trigger it myself?
