### ISSUE TITLE
Add same feature as in conda: use_only_tar_bz2: True

### ISSUE THREAD

**Issue by bkreider** [conda/constructor#681]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Create a setting for only using tar bz2 files like in conda/.condarc: `use_only_tar_bz2: True`

### Why is this needed?

This isn't a common problem, but sometimes it is desirable to force building using only tar.bz2 format conda packages.

### What should happen?

A user would set this setting to `True` and the installer would only use tar.bz2 format conda packages when building the installer.

**Comment by jaimergp** [comment]
You can export `CONDA_USE_ONLY_TAR_BZ2=True` for this :)
