### ISSUE TITLE
Anaconda references in `OptionsDialog.nsh`

### ISSUE THREAD

**Issue by mbargull** [conda/constructor#69]
In `constructor/nsis/OptionsDialog.nsh` the installation is still referred to as "Anaconda" which should be changed at some point.
Furthermore, and more importantly, the `AddToPath`-option's text says:
```
         $\nIf unchecked, then you must use the Anaconda Command Prompt \
         $\n(located in the Start Menu under $\"Anaconda (${ARCH})$\")."
```
Which might be misleading for end users if the corresponding menu entries are not provided by every installer.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.

@mbargull it also looks like #213 fixes this

**Comment by mbargull** [comment]
Thanks for the followup Michael!
