### ISSUE TITLE
constructor requires bzip2

### ISSUE THREAD

**Issue by JeremyEnns** [conda/constructor#70]
On a fresh install of CentOS 7

When running the bash installer created by constructor, the following error occurs:

tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

Workaround is to run:
yum install bzip2

Can we make constructor more self sufficient and either provide its own bzip2 so its able to extract its own packages, or can it at least do a check if bzip2 is installed and throw a warning that you must install bzip2 before using this installer?

**Comment by bkreider** [comment]
This is a problem for Repo and AEN.  In AEN we were going to check for it ourselves in a pre-install script but it is something constructor should do itself.  https://github.com/ContinuumIO/aen-issues/issues/779

**Comment by JeremyEnns** [comment]
The AEN and Repo teams are utilizing constructor to build out all of our enterprise installers now, this would look much nicer if our installers were able to function without needing to install other things first but if its not easy to package in bzip2 to the installer then a warning would likely be acceptable.

**Comment by damianavila** [comment]
> The AEN and Repo teams are utilizing constructor to build out all of our enterprise installers now, this would look much nicer if our installers were able to function without needing to install other things first but if its not easy to package in bzip2 to the installer then a warning would likely be acceptable.

Just a correction here... AEN is still using cas-installer.

**Comment by ilanschnell** [comment]
I've added a warning to the installer when `bzip2` is not installed, so the user has a better idea what is going on.  This will be part of constructor 1.5.5, which I'm releasing right now.
