### ISSUE TITLE
conda-libmamb-solver must be installed in the environment with constructor

### ISSUE THREAD

**Issue by moorepants** [conda/constructor#720]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have the libmamba sovler set as my default solver in my base environment. The documentation says:

"The specs will be solved with the solver configured for your base conda installation, if any. Starting with conda 22.11, this behavior can be overriden with the CONDA_SOLVER environment variable."

I then created a new environment with only constructor in it (as the getting started documentation recommends) with:

`conda create -n constructor constructor`

but then when running constructor I get this error:

```
Traceback (most recent call last):
  File "/home/moorepants/miniconda/envs/constructor/bin/constructor", line 6, in <module>
    from constructor.main import main
  File "/home/moorepants/miniconda/envs/constructor/lib/python3.11/site-packages/constructor/main.py", line 17, in <module>
    from .conda_interface import SUPPORTED_PLATFORMS, cc_platform
  File "/home/moorepants/miniconda/envs/constructor/lib/python3.11/site-packages/constructor/conda_interface.py", line 61, in <module>
    _Solver = context.plugin_manager.get_cached_solver_backend()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moorepants/miniconda/envs/constructor/lib/python3.11/site-packages/conda/plugins/manager.py", line 197, in get_solver_backend
    raise CondaValueError(
conda.exceptions.CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
```

I discovered that the libmamba solver should also be installed in the constructor environment.

I suggest adding that to the documentation somewhere, i.e. that you must have constructor and conda-libmamba-solver in the same environment.

### Conda Info

```shell
NA
```

### Conda Config

```shell
NA
```

### Conda list

```shell
NA
```

### Additional Context

NA

**Comment by millsks** [comment]
Ran into the same issue today.

**Comment by jaimergp** [comment]
Since conda 23.10 depends on conda-libmamba-solver, this won't be an issue for new installs. We'll add some clarifying text in the docs, though. Thanks.
