### ISSUE TITLE
Rename `conda.exe` in sh installers

### ISSUE THREAD

**Issue by marcoesters** [conda/constructor#741]
The `conda-standalone` executable is extracted into `conda.exe`. This can be confusing for users, support, and also to security programs. There is a documented instance of Arconis quarantining this file: https://github.com/ContinuumIO/anaconda-issues/issues/13311

This may be a general problem with Arconis: https://forum.acronis.com/forum/acronis-cyber-protect-home-office-forum-formerly-acronis-true-image-2021/quarantine-exe-files

The binary should probably not have an `exe` extension. It can be named `_conda`, equivalent to the Windows `_conda.exe` binary.

**Comment by jaimergp** [comment]
There are changes in #474 that will rename and _keep_ conda.exe around as `_conda.exe` (in Unix, it's deleted after the installation). We can rename to `_conda` if that's preferred. If you have time to review that one 🙏

**Comment by marcoesters** [comment]
I think renaming it to `_conda` might be better. Some security programs might get spooked to find a `.exe` files on a MacOS

**Comment by marcoesters** [comment]
The issue in the problem I linked was that `conda.exe` was quarantined during the installation.

I will find some time in the next few days to review the PR.

**Comment by jaimergp** [comment]
> I think renaming it to _conda might be better. Some security programs might get spooked to find a .exe files on a MacOS

Done :)

**Comment by jaimergp** [comment]
Done in #474. Shell installers bundle `_conda` instead of `conda.exe` now.
