### ISSUE TITLE
Check disk space before installing

### ISSUE THREAD

**Issue by marcoesters** [conda/constructor#749]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Check if enough disk space is available before installing

### Why is this needed?

The installation will fail if not enough disk space is available. In this case, the error is not always descriptive: https://github.com/ContinuumIO/anaconda-issues/issues/13334

A full disk can cause additional problems, so remaining disk space should not be occupied by failed installation artifacts.

### What should happen?

The installation should not start when not enough disk space is available.

**Comment by jaimergp** [comment]
See #751
