### ISSUE TITLE
Windows: output to stdout during command line installation

### ISSUE THREAD

**Issue by marcoesters** [conda/constructor#764]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

While a decision has not been made about a replacement for `NSIS` (#646), it might be worth exploring adding `stdout` output to the Windows command line installer.

This could be a good start: https://forums.winamp.com/forum/developer-center/nsis-discussion/261756-write-to-command-line-when-silent#post3290436

### Why is this needed?

There is currently no way to debug failures in command line installers. Using log files causes other issues (e.g., writing outside the installation directory with GUI installers when the "Browse..." button is clicked).

### What should happen?

There should be an additional flag that allows users to output to stdout (or suppress output to stdout).

**Comment by jaimergp** [comment]
I saw there are a few examples in Github if we [search for `System::Call 'kernel32::AttachConsole`](https://github.com/search?q=%22System%3A%3ACall+%27kernel32%3A%3AAttachConsole%22+NOT+is%3Afork&ref=opensearch&type=code). The most complete examples seem to be:

- [Errors reported to stdout if silent](https://github.com/tauri-apps/tauri/blob/24aaf0f5af5907d14d6e2e72afabf8f7d1428513/tooling/bundler/src/bundle/windows/templates/utils.nsh#L43-L51)
- [Printing the installer help to stdout](https://github.com/saltstack/salt/blob/bfc78d7646fd12443337d5840dfb2927dd889f37/pkg/windows/nsis/installer/Salt-Minion-Setup.nsi#L1823-L1839)
- [Logging utilities including stdout output](https://github.com/gyunaev/birdtray/blob/4523bd98682f3bb26fdf15e4e5460791674f0cbd/installer/Log.nsh)
- [Error reporting in red](https://github.com/surrealdb/surrealist/blob/3d30e17e24c45061423e94d4fd2a5b9e261d7b54/src-tauri/res/installer.nsi#L446-L452)
- [Hybrid CLI/GUI help message](https://github.com/perfwatcher/collectm/blob/da65aa200791dbf3c3bdd34374ed2985d9ad6a86/src/collectm.nsi#L43-L67)
- [A dual logging macro](https://github.com/ow2-proactive/agent-windows/blob/acce7d904eb5a823da694c2cf3e58051e1b89b2a/installer_script.nsi#L323-L335)

So I think we won't be able to forward _every_ message from NSIS to stdout, but we can definitely print our custom messages to stdout there.
