### ISSUE TITLE
Constructor and "installers" can not handle packages that track features.

### ISSUE THREAD

**Issue by hsparra** [conda/constructor#77]
The current version of constructor does not appear to work if one of the packages in the specs tracks a feature. As an example, in one situation the error message is
```
Error: Dependency missing in current linux-64 channels:
- mycerts ==1.0.4 ->@my
```
The construct.yaml file contains the channels where "mycerts" is located.

**Comment by looooo** [comment]
I think I ran into the same issue:
```
channels:
  - https://conda.anaconda.org/conda-forge    # hosts freetype2.7
```
```
Error:  Dependency missing in current linux-64 channels: 
  - occt 7.1.0* -> freetype 2.7.*

```

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
