### ISSUE TITLE
File or directory already exists

### ISSUE THREAD

**Issue by biaebia1** [conda/constructor#804]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I tried to install anaconda but when i selected the pasta:
![image](https://github.com/conda/constructor/assets/172998625/751b46ea-33e8-4e7d-80b9-f4a518e16310)

ERROR: File or directory already exists: '/root/anaconda3'
If you want to update an existing installation, use the -u option.

### Conda Info

```shell
conda: command not found
```

### Conda Config

```shell
conda: command not found
```

### Conda list

```shell
conda: command not found
```

### Additional Context

even with sudo, still conda: command not found

**Comment by marcoesters** [comment]
Can you verify if the directory already exists?

If so, then that is expected behavior. Installers created by `constructor` do not install existing directories. Please remove the existing installation or choose another directory in this case.
