### ISSUE TITLE
Install procedure can/should change for conda 4.4

### ISSUE THREAD

**Issue by kalefranz** [conda/constructor#81]
Rather than prepending the root env to PATH in `~/.bash_profile` etc, that entry can be changed to either

    . <CONDA_ROOT>/etc/profile.d/conda.sh

or

    . <CONDA_ROOT>/etc/profile.d/conda.sh
    conda activate root

The first makes the `conda` command available, but the root environment isn't automatically on PATH.  The second (obviously) also activate the root environment.

Another option is for .bash_profile is

    . <CONDA_ROOT>/[bin|Scripts]/activate root

None of these changes are a requirement for conda 4.4.  If nothing changes, `source activate` will work as before, and then the `conda activate` command also becomes available after `source activate` is ran the first time.

For cmd.exe, nothing needs to change with the "Anaconda Prompt" shortcut.

**Comment by mcg1969** [comment]
Closed as a pre-3.x issue likely to be obsolete.
