### ISSUE TITLE
Remove old constructor conda packages in conda-forge channel?

### ISSUE THREAD

**Issue by megies** [conda/constructor#82]
There's some old 1.3.x constructor conda packages in `conda-forge` channel, but it seems distribution was completely handed over to Anaconda `defaults` channel.. for people that have `conda-forge` as top priority channel this means that by default old constructor packages get installed if you don't pay close attention.. (I didn't pay too much attention until bumping into already fixed #57)

I would propose to remove all constructor conda packages from `conda-forge` channel, since all versions are readily available through `defaults`.

**Comment by mbargull** [comment]
Hi @megies, this is not related to constructor itself but its packaging at `conda-forge`. Your best bet is to close this issue and raise it over at https://github.com/conda-forge/constructor-feedstock/issues .
