### ISSUE TITLE
AIC files fail to execute on Windows

### ISSUE THREAD

**Issue by bheklilr** [conda/constructor#84]
I stumbled across the feature in Anaconda Repository where you can grab the Anaconda and Miniconda installers, then using `anaconda-server-admin update-installers` these can be bundled so that they will point at an alternate repository, following the [configuration management documentation](https://docs.continuum.io/anaconda-repository/admin/custom-anaconda-installers#bundled-installers).  I also came across [this gist](https://gist.github.com/kalefranz/7fba5b3a4165751ca780c5ebb277f229) discussing how the bundled installers are supposed to work.  Having had issues in the past with getting conda installs configured properly, I was excited to see a built-in solution.

Unfortunately, after trying it out I found that it had no effect.  The bundled .zip file seemed fine and had two files in it: `100_anaconda_config.aic` and `200_conda_config.aic`.  These files appeared to have the correct contents that included my server name and default channels, but when Miniconda-latest-Windows-x86_64.exe was run it didn't seem to have an effect.  No .condarc file was created in the home directory or prefix directory, and no anaconda config file was created in the appropriate location either.  The directory structure of `$PREFIX/etc/anaconda-client` was not created either.  `conda config` commands did not show any deviations from the defaults.

This feature would be awesome to have working properly.  Is there anything I can do to help debug this issue and figure out why it's not working properly?

**Comment by csoja** [comment]
I passed this one to our support group as it is related to the Anaconda Repository and not related to constructor.  Closing this issue.
