### ISSUE TITLE
Is it possible to disable installer prompts about adding to PATH and registry (on Windows)?

### ISSUE THREAD

**Issue by ceball** [conda/constructor#87]
The prompts about adding python to the path and registering python (on Windows) are a little confusing to end users (who are expecting to be installing an application). When building a standalone application, it would be great if I could specify that those prompts should not appear (and set both options to false).

**Comment by forman** [comment]
Same here. Unfortuantely, the PATH setting is checked by default so that most unexperienced users install our application as their new default Python, which is an unwanted side effect.
#66 could help, then we could tell users to uncheck PATH setting.

**Comment by nehaljwani** [comment]
This was addressed in https://github.com/conda/constructor/commit/2b2406cdca08e6f0d258e8a41109b7eac16bffe0 in the branch cross_conda_interface

**Comment by mcg1969** [comment]
This is definitely possible in 3.x.
