### ISSUE TITLE
Ability to send option flags to post-install script

### ISSUE THREAD

**Issue by mrclary** [conda/constructor#882]
### Checklist

- [x] I added a descriptive title
- [x] I searched open requests and couldn't find a duplicate

### What is the idea?

@jaimergp,
Is there a way for the `post-install` script to determine whether the installer is running in silent (`.exe` with `/S`) or batch (`.sh` with `-b`) mode?

Otherwise, is it possible to implement a feature in which command-line arguments provided to the installer (`.exe`, `.sh` or `.pkg`) are passed to the `post-install` script?

### Why is this needed?

For our Spyder installer, the post-install script is designed to launch Spyder automatically upon completing the install. It is desirable to forego this behavior if the Spyder installer is executed from the command-line in either batch or silent mode.

The ability to pass command-line arguments to the post-install script could provide more flexibility for developers that use the post-install script.

### Additional Context

spyder-ide/spyder#22730

**Comment by mrclary** [comment]
> This is trickier to do cross-platform. Might be trivial for `.sh` installers, tricky for `.exe` and almost impossible for `.pkg`. If all you need is to detect whether the installer is being run in silent, I think that's way easier.

I understand regarding `.pkg`, but macOS platforms could also use a `.sh` as an alternative. Having the feature for just `.sh` and `.exe` would be really nice. However, I only need to detect silent/batch mode for my current issue (spyder-ide/spyder#22730).

**Comment by jaimergp** [comment]
Added https://github.com/conda/constructor/pull/885
