### ISSUE TITLE
On Windows, constructor-generated installer attempts to make PATH too long

### ISSUE THREAD

**Issue by ceball** [conda/constructor#89]
On a system with a long PATH, I got this strange error message while installation was underway:

<img width="408" alt="abor" src="https://user-images.githubusercontent.com/1929/27886110-94410832-61d2-11e7-989b-cc81e01219a8.png">

I guess this is because of the long PATH and the various restrictions on windows PATH length. Shortening the PATH allowed installation to proceed successfully.

Maybe the installer could check it won't make the path too long?

If I could prevent the prompt about altering the path from appearing (#87), then this would not be an issue for me (I would set 'add python to PATH' to 'no').

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
