### ISSUE TITLE
Windows: anaconda prompt fails to open in some cases (missing activate.bat)

### ISSUE THREAD

**Issue by ceball** [conda/constructor#90]
Using constructor on Windows 10, I created an installer. When installed onto Windows 7 for testing, I got the following error message on opening the anaconda prompt from the start menu:

```'C:\Users\cball\X\Scripts\activate.bat' is not recognized as an internal or external command, operable program or batch file.```

(where X was the installation directory selected). I tried installing on two Windows 7 systems with the same result. There was no ``activate.bat`` at ``C:\Users\cball\X\Scripts\activate.bat``.

The jupyter notebook start menu entry worked each time, though.

Any chance you can guess what I might have done wrong for that to have happened?!

Meanwhile I'll try to find a way to narrow down and reproduce the problem. Sorry not to provide more information for debugging up front.

**Comment by mingwandroid** [comment]
I think you need to run procmon during installation here to see what's removing that file. It's a part of conda, so as long as your installer included that you should have it.

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.
