### ISSUE TITLE
Exclamation points in build numbers for packages are problematic

### ISSUE THREAD

**Issue by larsoner** [conda/constructor#908]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

See this [install error](https://github.com/mne-tools/mne-installers/actions/runs/12121861475/job/33794012776?pr=309) in MNE-Installers after the installer is successfully built:
```
Run sh ./${MNE_INSTALLER_NAME} -b
PREFIX=/home/runner/mne-python/1.8.0_0
Unpacking payload ...
entry_point.py:191: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
entry_point.py:191: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.

Installing base environment...


InvalidMatchSpec: Invalid spec 'https://conda.anaconda.org/conda-forge/linux-64/x264-1%21[16](https://github.com/mne-tools/mne-installers/actions/runs/12121861475/job/33794012776?pr=309#step:5:17)4.3095-h166bdaf_2.tar.bz2 md5=6c99772d483f566d59e25037fea2c4b1': Invalid version '1%21164.3095': invalid character(s)
```
This is because x264 is in the env and it has build numbers [like `1!164.3095`](https://github.com/conda-forge/x264-feedstock/blob/e1af5c4e27635470b5851cb7d21f7c4f64847b21/recipe/meta.yaml#L3).

### Additional Context

[Windows](https://github.com/mne-tools/mne-installers/actions/runs/12121861475/job/33794259526?pr=309) installer runs but exits without issue despite seeming to have failed (based on the missing activation script that was working previously), [macOS](https://github.com/mne-tools/mne-installers/actions/runs/12121861475/job/33794414097?pr=309#step:6:156) fails with a cryptic error. I assume these are all the same error, but it's a bummer the macOS and Windows errors are hidden if that is indeed the case!

It's possible these are also somehow related to the latest release but I doubt it. I'll try stripping the installer down so that `x264` isn't included, we'll see...

**Comment by jaimergp** [comment]
Thanks for the report! Interesting that it got URL-escaped 🤔 We'll need to check whether this is a problem in how we are storing the metadata internally or a bug in conda-standalone.

**Comment by jaimergp** [comment]
conda-libmamba-solver 24.11.1 is now available, which fixes this issue.

**Comment by larsoner** [comment]
Thanks for the quick fix and release @jaimergp !
