### ISSUE TITLE
mkl on Windows - tgz_extract: bad header checksum

### ISSUE THREAD

**Issue by ThomasLecocq** [conda/constructor#92]
when trying to build the Windows installer for ObsPy with @megies (https://github.com/obspy/obspy/pull/1818), all packages are downloaded well, the nsis installer is built well, the installation process goes OK, but the installed numpy is broken due to the missing MKL package (although it's in the downloaded tar.bz2).

The NSIS installation log shows this:
```
Extract: mkl-2017.0.3-0.tar.bz2
untgz::extract -d 'C:\Users\thlec\Desktop\obspy27w64' -zbz2 'C:\Users\thlec\Desktop\obspy27w64\pkgs\mkl-2017.0.3-0.tar.bz2' 
tgz_extract: bad header checksum
Error: Failure reading from tarball.
Execute: "C:\Users\thlec\Desktop\obspy27w64\pythonw.exe" -E -s "C:\Users\thlec\Desktop\obspy27w64\pkgs\.install.py"
Delete file: C:\Users\thlec\Desktop\obspy27w64\pkgs\mkl-2017.0.3-0.tar.bz2
```

Checking in the urls.txt file and downloading the file manually:
http://repo.continuum.io/pkgs/free/win-64/mkl-2017.0.3-0.tar.bz2 (126MB)

gives a file I cannot open as a "tar.bz2", but it looks like it is a "tar.bz2.tar" file
Could this be that the mkl archive file is bad ?

On the installed stuff, doing Scripts\conda.exe install mkl does work:
```
TRACE conda.core.path_actions:execute(807): extracting C:\Users\thlec\Desktop\obspy27w64\pkgs\mkl-2017.0.3-0.tar.bz2 => C:\Users\thlec\Desktop\obspy27w64\pkgs\mkl-2017.0.3-0
DEBUG conda.gateways.disk.create:extract_tarball(103): extracting C:\Users\thlec\Desktop\obspy27w64\pkgs\mkl-2017.0.3-0.tar.bz2
  to C:\Users\thlec\Desktop\obspy27w64\pkgs\mkl-2017.0.3-0
```

So, my bet is that within conda there is a better way of handling boguous archives (https://github.com/conda/conda/blob/master/conda/gateways/disk/create.py#L128) than in the conda-builder nsis stuff (untgz or else?).

The current only alternative is to tell users to do the conda install mkl after install, but it's not super super great :)

Thanks in advance,
Tom

**Comment by megies** [comment]
To reproduce the problem, grab the constructor yamls from here and build installer on windows: https://github.com/obspy/obspy/tree/bb62c779f4e3e0f0e3d35378d104aae7dea53c76/misc/installer/conda-constructor

**Comment by ThomasLecocq** [comment]
FYI Changing the mkl version to 2017.0.1 solves the problem.

**Comment by megies** [comment]
We're a bit puzzled why `tgz_extract` in `nsis` thinks that there's a problem with the checksum.. I can't find anything wrong with the file if I download it and run `bunzip2` on it on Linux..

**Comment by aberres** [comment]
Just stumbled upon this issue as well.

Using mkl 2017.0.1 helped.

**Comment by megies** [comment]
> Just stumbled upon this issue as well.
> 
> Using mkl 2017.0.1 helped.

Yep, that's what we ended up doing..

**Comment by mcg1969** [comment]
Sorry for the form letter here—I'm doing some issue cleanup right now and closing out some stale issues. Constructor 3.x was a significant rewrite, and so many of the issues filed before its release would need to be re-tested / re-verified. If you have good reason to believe this still needs to be addressed in 3.x, please feel free to re-open or file a new issue with additional information on how to reproduce the issue on the latest versions of constructor.

**Comment by ThomasLecocq** [comment]
@megies  do we still make installers? Can't remember why/how this happened

**Comment by megies** [comment]
not making installers right now due to time constraints, but these were always pretty handy
