### ISSUE TITLE
Build windows installers on Linux?

### ISSUE THREAD

**Issue by megies** [conda/constructor#93]
Is there any chance that we'll be able to build Windows installers on Linux?

I gave it a quick shot, following [these instructions](https://blog.alejandrocelaya.com/2014/02/01/compile-nsis-scripts-in-linux/) and finally got hickupped because it couldn't find the UAC plugin stuff defined by constructor (I tried to place that UAC.nsi in the respective nsis directories but it didn't properly use it).. but then again, I'm no nsis expert (actually didn't even know it yesterday).

From what I read on the internet in principle it should be possible to build Windows installers on a Linux machine, and maybe it's only those constructor nsi recipes and maybe the untgz plugin that are missing pieces.

Any opinions on this topic?

(Anyway, I'll probably look into building windows installers using appveyor.. it might not be worth the effort getting it done on Linux)

**Comment by mcg1969** [comment]
Looks like #390 makes this possible
