### ISSUE TITLE
Constructor should use the same solver as Conda

### ISSUE THREAD

**Issue by mrduane** [conda/constructor#95]
per https://github.com/Anaconda-Platform/anaconda-server/issues/4032, Constructor doesn't honor channel priority.

**Comment by jakirkham** [comment]
Seems, at least partially, like a dup of issue ( https://github.com/conda/constructor/issues/54 ).

**Comment by mrduane** [comment]
Agreed on partially. I'm not clear on the resolution, though. Is the answer simply to install the latest constructor in the root env?

**Comment by jakirkham** [comment]
Yes, the resolution is to use 2.0.0 and install it in `root` as it now uses `conda`.
